### ISSUE TITLE
Temp folder containing ambiguous user.input.file.list

### ISSUE THREAD

**Issue by qvrijt** [dita-ot/dita-ot#3051] opened 2018-08-21 15:38 UTC
Context : rendering to PDF out-of-the-box dita-ot-3.1.2 using FOP from commandline on Windows 10 

When using **dita.bat -Dclean.temp=no**, I noticed my temp folder contains two files with identical contents.

- usr.input.file.list
- user.input.file.list

A file search resulted in org.dita.base/build-preprocess(-template).xml:
```
    <job-helper file="user.input.file.list" property="user.input.file"/>
    <job-helper file="usr.input.file.list" property="user.input.file"/>
```

Is this by design, or kept for backward compatibility e.g. for plugins?
As I found no other references, i propose to remove the shorter one.

**Comment by jelovirt** [comment] 2018-08-21 16:07
By design. Poor naming at some point. Closing as not a bug.

**Closed by jelovirt** 2018-08-21 16:07 UTC
