### ISSUE TITLE
Fatal Error! No digits found for colspec with width specified in pts [DOT 2.0.1M1]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1856] opened 2015-02-19 13:27 UTC
I have in a DITA topic a table with a colspec with width specified in PTS:

```xml
<colspec colname="c1" colnum="1" colwidth="171.0pt"/>
```
Running DOT 2.0.1 XHTML I obtain the error:

> [xslt] C:\Users\radu_coravu\Desktop\DOT2.0.1\DITA-OT2.1.0-M1\plugins\org.dita.xhtml\xsl\xslhtml\dita2htmlImpl.xsl:2227: Fatal Error! No digits found

suggested fix:

```xml
<xsl:variable name="thiswidth">            <!-- Width of this column -->
  <xsl:choose>
    <xsl:when test="@colwidth and contains(@colwidth, '*')"><xsl:value-of select="substring-before(@colwidth, '*')"/></xsl:when>
    <xsl:otherwise>1</xsl:otherwise>
  </xsl:choose>
</xsl:variable>
```

**Comment by raducoravu** [comment] 2015-02-23 12:57
I'm using a very recent Saxon 9.6.0.3 version.
And my initial suggested workaround is not good because I'm not sure what the variable should return, only a percent width?

**Comment by drmacro** [comment] 2015-02-23 15:51
I submitted a pull request a couple of weeks ago that completely reworks the HTML table processing so that it correctly handles all units used in table column widths. That fix, if accepted, should address this issue I think.

**Comment by raducoravu** [comment] 2015-03-11 09:33
There are other places also in the same XSLT which do stuff like:

    substring-before($colspec/@colwidth, '*')

and then use the variable at some point in a mathematical expression like:

     ($thiswidth div $totalwidth) * 100

which again results in the same error.

As simple workarounds I surrounded those expressions in a number() cast like:

    <xsl:variable name="relcol" select="number(substring-before($relcolvalues, '*'))"/>

Again, this is with the latest Saxon 9, it's possible a behavior was changed in it.

**Comment by jelovirt** [comment] 2015-03-11 14:13
Duplicate of #1694

**Closed by jelovirt** 2015-03-11 14:13 UTC
Labels: bug, duplicate, P1, xhtml
