### ISSUE TITLE
Support for Landscape Orientation

### ISSUE THREAD

**Issue by rahulraykor** [dita-ot/dita-ot#3125] opened 2018-10-24 14:05 UTC
## Description
DITA Exchange while conversion was showing topic pages in Landscape mode if output class is set in topic.
Can someone suggest a way to add Landscape orientation support in DITA-OT?

**Comment by raducoravu** [comment] 2018-10-24 14:06
The fact that the DITA Open Toolkit does not have support for this is not a bug.
If you want to see an example of a DITA Open Toolkit plugin which implements landscape orientation, you can find one here:
https://github.com/oxygenxml/dita-classic-pdf-landscape-sample

**Comment by rahulraykor** [comment] 2018-10-26 12:00
This plugin converts entire map into landscape.
I need some pages (topics) into Landscape and some normal. Depending on the output class property.
How can I add this support to DITA-OT?

**Comment by raducoravu** [comment] 2018-10-26 12:11
As the description of the plugin says, only for the DITA topics on which you set the outputclass='landscape'' attribute on the root element, the plugin should generate landscape pages.

**Comment by jelovirt** [comment] 2018-11-12 19:38
Feature implemented by a plugin, closing as a question

**Closed by jelovirt** 2018-11-12 19:38 UTC
