### ISSUE TITLE
DITA-OT 1.8 keydef/linktext does not display when keyref is used for topicref in reltable

### ISSUE THREAD

**Issue by jomjohn** [dita-ot/dita-ot#1686] opened 2014-05-29 22:53 UTC
For some reason when a keyref is resolved inside a map reltable, the defined keydef/topicmeta/linktext is not populated into the topicref/topicmeta/linktext. Instead the @href value is used.
I have sample files but I am not sure how to upload them to github.
Thanks for any help you can provide.
-Josh Johnson

**Comment by eerohele** [comment] 2015-05-31 07:52
Closing as duplicate of #1439.

**Closed by eerohele** 2015-05-31 07:52 UTC
Labels: bug
