### ISSUE TITLE
DITA-OT 1.8.X - Chunking causes incorrect CSS path for <link> element in HTML output

### ISSUE THREAD

**Issue by gilyu88** [dita-ot/dita-ot#2114] opened 2015-10-27 18:34 UTC
When you use chunking in a ditamap and build using the xhtml transform, the CSS path is incorrect.
This worked properly in DITA-OT 1.5.3 from what I can tell, but not DITA-OT1.8 or DITA-OT1.8.5.

Here's what the map looks like:

    <topicref href="topic/topicA.xml" type="concept" chunk="to-content" >
        <topicref href="topic/topicB.xml" type="concept"/>
    </topicref>

The output should look  like this:

    <link rel="stylesheet" type="text/css" href="../commonltr.css"/>

Instead, it looks like this, where its missing a "../"

    <link rel="stylesheet" type="text/css" href="commonltr.css"/>

**Comment by eerohele** [comment] 2016-02-07 15:59
Closing as duplicate of #1711 (which also proposes a workaround).

**Closed by eerohele** 2016-02-07 15:59 UTC
Labels: 1.x, duplicate, preprocess/chunking, xhtml
