### ISSUE TITLE
Incorrect replacement text when using category/keyword in map and term/@keyref in topic.

### ISSUE THREAD

**Issue by ianskeaff** [dita-ot/dita-ot#2521] opened 2016-11-16 18:43 UTC
In DITA OT 1.8.5, the keyref preprocessor appears to be adding replacement text based on the first keyword of a category in the ditamap, rather than expected text from the glossary.

For example, with the following ditamap:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
    <title>DITA Topic Map</title>
    <topicmeta>
        <navtitle id="navtitle">Test Instance</navtitle>
        <metadata>
            <category>
                <keyword>Keyword 1</keyword>
                <keyword>Keyword 2</keyword>
            </category>
        </metadata>
    </topicmeta>
    <topichead>
        <topicmeta>
            <navtitle>Here's the navtitle</navtitle>
        </topicmeta>
        <topicref href="topic.dita" format="dita"/>
    </topichead>
    <glossref keys="gl_tt" href="glossary.dita"/>
</map>
```

... glossary:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glossgroup PUBLIC "-//OASIS//DTD DITA Glossary Group//EN" "glossgroup.dtd">
<glossgroup id="gg_glossary">
    <title>Glossary Terms</title>
    <glossentry id="gl_term">
        <glossterm>The Term</glossterm>
        <glossdef><p>The definition.</p></glossdef>
        <glossBody>
            <glossSurfaceForm>The Term (TT)</glossSurfaceForm>
            <glossAlt>
                <glossAcronym>TT</glossAcronym>
            </glossAlt>
        </glossBody>
    </glossentry>
</glossgroup>
``` 

... and topic:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="topic_test">
  <title>Topic Title</title>
  <body>
      <p>Words leading up to a glossary term <term keyref="gl_tt"/>. 
          Abbreviated form: <abbreviated-form keyref="gl_tt"/></p>
  </body>
</topic>
```

... will produce the following output in XHTML (similar results in PDF and EPUB outputs.):
```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xml:lang="en-us" lang="en-us">
...
<body id="topic_test">
  <h1 class="title topictitle1">Topic Title</h1>
  <div class="body">
      <p class="p">Words leading up to a glossary term 
<a href="glossary.html" title="The definition."><dfn class="term">Keyword 1</dfn></a>. 
          Abbreviated form: 
<a href="glossary.html" title="The definition."><dfn class="term abbreviated-form">Keyword 1</dfn></a></p>
  </div>
</body>
</html>
```

Expected output would be: `<dfn class="term">The Term (TT)</dfn>` and `<dfn class="term abbreviated-form">TT</dfn>`

Attachment: GlossaryTermTestCase.zip containing `glossary.dita`, `topic.dita`, `withcategory.ditamap`
[GlossaryTermTestCase.zip](https://github.com/dita-ot/dita-ot/files/595591/GlossaryTermTestCase.zip)

**Comment by jelovirt** [comment] 2016-11-17 06:10
Probably a duplicate of #1990.

DITA-OT 1.x is end-of-life and is no future bug fix releases are expected.

**Closed** 2016-11-17 06:10 UTC
Labels: 1.x, bug, duplicate
