### ISSUE TITLE
Zero-width spaces rendered incorrectly for htmlhelp

### ISSUE THREAD

**Issue by sverhagen** [dita-ot/dita-ot#1383] opened 2012-09-13 20:15 UTC
When creating a document that has zero-width spaces (```&#8203;```), those are rendered incorrectly for ```transtype=htmlhelp```. They are rendered correctly for XHTML (removed from output) and FO/PDF (invisible).

Perhaps other high Unicode characters may experience the same problem. Did not test that.

Tested this with DITA OT 1.5.4.

**Comment by robander** [comment] 2016-04-25 19:45
Trying to consolidate older problem reports - I think this one really covers two issues, both of which are open separately:

- Non-breaking-space is corrupted in HTML Help content files (also true for any other character not in the Windows or ISO character set of the CHM language). This is covered by #2020 which will hopefully be resolved by leaving those files as Unicode.
- The same characters are corrupted in the HTML TOC / Index / Search panels. This is a tougher issue because by default it relies on the system language when compiling. This issue is covered by #1271.

I'm going to close this one as a duplicate of those two, hoping that we'll finally have a good solution for the first one, but less sure about the second one.

**Closed by robander** 2016-04-25 19:45 UTC
Labels: bug, duplicate, htmlhelp
