### ISSUE TITLE
dita.xsl.xhtml feature extension point effects engaging beyond expected scope

### ISSUE THREAD

**Issue by jrhooker** [dita-ot/dita-ot#3519] opened 2020-05-27 22:43 UTC
## Expected Behavior
Defining a feature extension of the dita.xsl.xhtml extension within a javahelp or eclipsehelp  plugin should affect only xhtml output for the javahelp or eclipsehelp plugin defined.

## Actual Behavior
The changes defined using the dita.xsl.xhtml extension point within a javahelp or eclipsehelp plugin appear in all xhtml output, regardless of the transtype called.

## Steps to Reproduce
1. Add the two plugins in the attached zip file to the 3.4.1 version of the OT.
2. Use some sample files to generate javahellp using the mchp_javahelp transtype and the xhtml transtype.
3. Both the javahelp and xhtml output will have the footer content in the output html which is only defined in the javahelp plugin.

[Javahelp.zip](https://github.com/dita-ot/dita-ot/files/4692143/Javahelp.zip)

## Environment

* DITA-OT version: 3.4.1
* Operating system and version:
  Windows 10
* How did you run DITA-OT?
  `dita` command, 
* Transformation type:
  mchp_javahelp, xhtml

**Comment by raducoravu** [comment] 2020-05-28 04:31
The extension point is global and it works as documented, indeed affecting all XHTML-based outputs:
https://www.dita-ot.org/dev/extension-points/extension-points-in-org.dita.xhtml.html#ariaid-title1
Maybe you can control the XSLT with parameters (using the "dita.conductor.xhtml.param" extension point), parameters which could be set for one transformation but not for the others.

**Comment by jelovirt** [comment] 2020-05-28 05:50
Closing as works as intended.

**Closed by jelovirt** 2020-05-28 05:50 UTC

**Comment by jrhooker** [comment] 2020-05-28 16:13
Ok, so it's working as it should. That's surprising. At this point we're just using our pre-existing plugin extending the xhtml plugin and using the transtype parameter to distinguish when the templates should be applied to the various outputs. 

Radu, are you suggesting that if I defined a parameter in the javahelp plugin using the dita.conductor.xhtml.param then I could define a parameter that would be passed to the xhtml plugin when the content being processed is destined for the javahelp plugin? In this application, I expect that would be redundant, but I can see that being useful for other purposes.

Are all extension points applied globally this way? I would have expected extension points defined within a plugin to be applied within the plugin.

**Comment by raducoravu** [comment] 2020-05-29 04:29
The "dita.xsl.xhtml" extension point is defined in the "org.dita.xhtml" plugin (you can open the "org.dita.xhtml/plugin.xml" to see its definition). Both the XHTML plugin and all other plugins which extend this plugin (including Java Help Eclipse Help, Windows Help) will use your extra XSLT stylesheets defined for this extension point.
One thing the JavaHelp plugin could have probably done (but it did not) would have been to define its own separate XSLT extension point, so that when a plugin wanted to customize only JavaHelp it could have extended only that particular extension point. As far as I know the DITA OT organization no longer maintains the JavaHelp plugin.

If you use the "dita.conductor.xhtml.param" extension point in your plugin (not in the JavaHelp plugin), like for example we do for this plugin:
https://github.com/oxygenxml/dita-plant-uml/blob/master/com.oxygenxml.plantuml.svg/plugin.xml

you could pass a parameter from the transformation command line to the XSLT.
For example if this parameter would be "javaHelpTransformation", from the command line when you invoke the JavaHelp transtype you could also set this parameter to "yes", so that it reaches the custom stylesheet and can be used in the custom stylesheet to decide if the custom processing should be done or not.
