### ISSUE TITLE
NullPointerException when Publishing a Learning Group Map

### ISSUE THREAD

**Issue by smmcintire** [dita-ot/dita-ot#2700] opened 2017-05-22 18:20 UTC
I'm using DITA OT 2.4.6 and when I attempt to publish a Learning Group Map to PDF or HTML5, I'm getting this error below. I tested with DITA OT 2.0 and it is working fine.

[LearningMap.zip](https://github.com/dita-ot/dita-ot/files/1019705/LearningMap.zip)

chunk:
[chunk] Processing file:A$L000022.ditamap

BUILD FAILED
The following error occurred while executing this line:

lib\dita-ot\plugins\org.dita.base\build_preprocess.xml:308: java.lang.NullPointerException
at org.dita.dost.writer.AbstractChunkTopicParser.generateOutputFile(AbstractChunkTopicParser.java:340)
at org.dita.dost.writer.ChunkTopicParser.processChunk(ChunkTopicParser.java:149)
at org.dita.dost.writer.ChunkTopicParser.write(ChunkTopicParser.java:60)
at org.dita.dost.reader.ChunkMapReader.processCombineChunk(ChunkMapReader.java:536)
at org.dita.dost.reader.ChunkMapReader.processTopicref(ChunkMapReader.java:341)
at org.dita.dost.reader.ChunkMapReader.processChildTopicref(ChunkMapReader.java:513)
at org.dita.dost.reader.ChunkMapReader.processTopicref(ChunkMapReader.java:366)
at org.dita.dost.reader.ChunkMapReader.process(ChunkMapReader.java:142)
at org.dita.dost.writer.AbstractDomFilter.read(AbstractDomFilter.java:55)
at org.dita.dost.reader.ChunkMapReader.read(ChunkMapReader.java:118)
at org.dita.dost.module.ChunkModule.execute(ChunkModule.java:80)
at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:70)
at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:222)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:435)
at org.apache.tools.ant.Target.performTasks(Target.java:456)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:435)
at org.apache.tools.ant.Target.performTasks(Target.java:456)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
at org.apache.tools.ant.Main.runBuild(Main.java:854)
at org.apache.tools.ant.Main.startAnt(Main.java:236)
at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

**Comment by jelovirt** [comment] 2017-05-23 04:20
Unable to reproduce with `develop`.

**Comment by smmcintire** [comment] 2017-05-23 19:25
Are you able to try it using 2.4.6?

**Comment by raducoravu** [comment] 2018-06-29 05:02
One of our clients encountered the same problem using the DITA OT 2.5.2 bundled with Oxygen:

https://www.oxygenxml.com/forum/post48110.html#p48110

If I manage to put together some samples, I will add them on the opened issue.

**Comment by raducoravu** [comment] 2018-06-29 05:09
I also cannot reproduce the problem with the samples which are now attached on the issue.

**Comment by raducoravu** [comment] 2019-02-12 05:34
Closing this one as both me and @jelovirt could not reproduce the problem with the attached samples. I last tried with DITA OT 3.2.1

**Closed by raducoravu** 2019-02-12 05:34 UTC
Labels: bug, needs reproduction, preprocess/chunking, priority/high
