### ISSUE TITLE
Wrong parameter is used in task-elements.xsl

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2216] opened 2016-02-02 13:34 UTC
branch: `develop`

The template [task-elements.xsl#L150](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/xsl/fo/task-elements.xsl#L150) uses the parameter `task_result` instead of `task_results`, therefore the string is not correctly resolved.

```xml
    <xsl:template match="*[contains(@class, ' task/result ')]">
        <fo:block xsl:use-attribute-sets="result">
            <xsl:call-template name="commonattributes"/>
            <xsl:apply-templates select="." mode="dita2xslfo:task-heading">
                <xsl:with-param name="use-label">
                    <xsl:apply-templates select="." mode="dita2xslfo:retrieve-task-heading">
                      <xsl:with-param name="pdf2-string">Task Result</xsl:with-param>
                      <xsl:with-param name="common-string">task_result</xsl:with-param>
                    </xsl:apply-templates>
                </xsl:with-param>
            </xsl:apply-templates>
            <fo:block xsl:use-attribute-sets="result__content">
              <xsl:apply-templates/>
            </fo:block>
        </fo:block>
    </xsl:template>
```

Correct string in [strings-en-us.xml#L69](https://github.com/dita-ot/dita-ot/blob/develop/src/main/xsl/common/strings-en-us.xml#L69) is `task_results`:

```xml
<str name="task_results">Results</str>
```

**Comment by jelovirt** [comment] 2016-02-02 13:35
Duplicate of #2203

**Closed by jelovirt** 2016-02-02 13:35 UTC
Labels: duplicate
