### ISSUE TITLE
DITA + Markdown publishing fail - "No renderer configured for com.vladsch.flexmark.ext.typographic.TypographicSmarts"

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2866] opened 2017-12-19 10:25 UTC
Using DITA OT 3.0.1 to publish a small DITA project which contains a markdown topic to PDF fails with:

            BUILD FAILED
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\build.xml:45: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\plugins\org.dita.base\build_preprocess2.xml:176: java.lang.RuntimeException: No renderer configured for com.vladsch.flexmark.ext.typographic.TypographicSmarts
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.renderNode(DitaRenderer.java:498)
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.renderChildrenNode(DitaRenderer.java:512)
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.renderChildren(DitaRenderer.java:504)
            	at com.elovirta.dita.markdown.renderer.CoreNodeRenderer.printTag(CoreNodeRenderer.java:1321)
            	at com.elovirta.dita.markdown.renderer.CoreNodeRenderer.render(CoreNodeRenderer.java:772)
            	at com.elovirta.dita.markdown.renderer.CoreNodeRenderer.lambda$getNodeRenderingHandlers$42(CoreNodeRenderer.java:186)
            	at com.elovirta.dita.markdown.renderer.NodeRenderingHandler.render(NodeRenderingHandler.java:16)
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.renderNode(DitaRenderer.java:491)
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.renderChildrenNode(DitaRenderer.java:512)
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.renderChildren(DitaRenderer.java:504)
            	at com.elovirta.dita.markdown.renderer.CoreNodeRenderer.render(CoreNodeRenderer.java:323)
            	at com.elovirta.dita.markdown.renderer.CoreNodeRenderer.lambda$getNodeRenderingHandlers$20(CoreNodeRenderer.java:164)
            	at com.elovirta.dita.markdown.renderer.NodeRenderingHandler.render(NodeRenderingHandler.java:16)
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.renderNode(DitaRenderer.java:473)
            	at com.elovirta.dita.markdown.DitaRenderer$MainNodeRenderer.render(DitaRenderer.java:386)
            	at com.elovirta.dita.markdown.DitaRenderer.render(DitaRenderer.java:150)
            	at com.elovirta.dita.markdown.MarkdownReader.parseAST(MarkdownReader.java:273)
            	at com.elovirta.dita.markdown.MarkdownReader.parse(MarkdownReader.java:184)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.dita.dost.module.reader.AbstractReaderModule.readFile(AbstractReaderModule.java:356)
            	at org.dita.dost.module.reader.AbstractReaderModule.processWaitList(AbstractReaderModule.java:285)
            	at org.dita.dost.module.reader.TopicReaderModule.execute(TopicReaderModule.java:71)

Attached samples:

[testFailMDTypographic.zip](https://github.com/dita-ot/dita-ot/files/1571261/testFailMDTypographic.zip)

**Comment by raducoravu** [comment] 2017-12-19 10:27
This worked with the previous version of the Markdown plugin (the one before using the flexmark libs).

**Comment by robander** [comment] 2018-01-02 17:18
I'm guessing this should be reported at https://github.com/jelovirt/org.lwdita

**Comment by raducoravu** [comment] 2018-01-03 06:40
I added an issue for it also on the separate project. But as this plugin is now distributed with the DITA OT I somehow now see it part of the DITA OT and its issues list.

**Comment by robander** [comment] 2018-01-03 17:05
> I added an issue for it also on the separate project. But as this plugin is now distributed with the DITA OT I somehow now see it part of the DITA OT and its issues list.

Yeah I think that's one problem we're likely to encounter a lot with separate repositories for part of the code (most people just see it as "one project" regardless of where the parts come from).

Regardless - closing this one now that the issue is open in the other repo, which is where the fix will need to happen.

**Closed by robander** 2018-01-03 17:05 UTC

**Comment by StanDoherty** [comment] 2018-02-07 16:48
FWIW -- the same error messages appears in 3.0.2 when I attempt to build any map with <topicref>s to Markdown files.

**Comment by StanDoherty** [comment] 2018-02-07 16:49
. . . with topicrefs . . .

**Comment by infotexture** [comment] 2018-02-07 22:56
I am not able to reproduce this with 3.0.2. 

Markdown topics are now properly built with the `dita` command, even when they contain typographic quotation marks, so the changes for LwDITA plug-in v2.0.2 in jelovirt/org.lwdita@2c01572 are effective.

@StanDoherty How are you running the build? — Perhaps with Ant?

P.S. I edited your comment to display the `<topicref>` part _(and removed the followup comment)_.

**Comment by dxcook5** [comment] 2018-02-28 17:24
I still see this issue building with 3.0.2 with Oxygen (running Ant). I get the same error as that in the original post.

**Comment by grundrauschen** [comment] 2018-03-09 14:44
I got the same issue in 3.0.2 depending on the format flag.
When using `format="mdita"` in the map everything worked fine. When I used `format="markdown"` though, the same error as above appeared.
