### ISSUE TITLE
The 'onlytopic.in.map' parameter should also work for image links

### ISSUE THREAD

**Issue by balasaalin** [dita-ot/dita-ot#3311] opened 2019-05-27 12:59 UTC
This issue is related with this one: https://github.com/dita-ot/dita-ot/issues/1734
The `onlytopic.in.map=true` parameter appears to stop following down every `<xref>` element, but it does not prevent chasing down every `<image>` element. 
In the example listed in the [1734 issue](https://github.com/dita-ot/dita-ot/issues/1734) if you replace the xref link with an image reference, the image should not be copied in the output directory.
Maybe this parameter should have the same behavior for all kind of links, rather than just `<xref>`.

**Comment by robander** [comment] 2019-09-23 14:42
The `onlytopic` parameter was only meant to change how topics are processed, so I'm worried a change to make it apply to images would break a lot of assumptions. We use `onlytopic.in.map=true` as the default for all of our output types.

If I understand the request - I think what you're suggesting would mean that we have to list our images in the map, in order for them to be copied to the output directory?

**Comment by robander** [comment] 2019-11-07 10:38
Closing - the `onlytopic.in.map` parameter is working as intended for images, the parameter is only intended to change which topics generate output files.

**Closed by robander** 2019-11-07 10:38 UTC
