### ISSUE TITLE
NullPointerException when linking to topic which was copied using copy-to

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2767] opened 2017-08-23 09:31 UTC
Tested with DITA OT 2.5.2.
My DITA Map looks like this:

      <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
      <map title="Growing Flowers">
        <topicref href="topics/flowers/iris.dita" copy-to="topics/flowers/iris2.dita"/>
        <topicref href="topics/flowers/test.dita"/>
      </map>

and my "test.dita" refers directly to the copied topic like this:

            <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
            <topic id="test">
                <title>test</title>
                <body>
                    <p><xref href="iris2.dita"/></p>
                </body>
            </topic>

When publishing to either XHTML or PDF besides the error that the "iris2.dita" cannot be found we also get a NPE:

                BUILD FAILED
                D:\projects\eXml\frameworks\dita\DITA-OT2.x\build.xml:45: The following error occurred while executing this line:
                D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.base\build_preprocess.xml:299: java.lang.NullPointerException
                	at org.dita.dost.module.CopyToModule.performCopytoTask(CopyToModule.java:162)
                	at org.dita.dost.module.CopyToModule.execute(CopyToModule.java:75)
                	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:80)
                	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:230)
                	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
                	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
                	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                	at java.lang.reflect.Method.invoke(Unknown Source)
                	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)

With DITA OT 1.8 the NPE was not obtained and the link worked both in the XHTML and PDF-based output. 
The problem seems to exists also in older DITA OTs (I tested also with 2.4.4).

**Comment by gguillotte** [comment] 2017-08-23 18:06
Is this related to (or a dupe of) #2733?

**Comment by jelovirt** [comment] 2017-08-23 18:37
Seem to be a duplicate. Good catch.

**Closed by jelovirt** 2017-08-23 18:37 UTC
Labels: duplicate
