### ISSUE TITLE
NullPointerException in org.dita.dost.util.KeyScope

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2804] opened 2017-10-03 07:45 UTC
Reproduced with DITA OT 2.5.2, end user has not yet provided samples.

     keyref:
          [keyref] Reading file:/.../mapName.ditamap

    BUILD FAILED
    /Applications/oxygen19.1/frameworks/dita/DITA-OT2.x/build.xml:45: The following error occurred while executing this line:
    /Applications/oxygen19.1/frameworks/dita/DITA-OT2.x/plugins/com.jeppesen.webhelp/build_dita.xml:63: The following error occurred while executing this line:
     /Applications/oxygen19.1/frameworks/dita/DITA-OT2.x/plugins/org.dita.base/build_preprocess.xml:279: java.lang.NullPointerException
                at org.dita.dost.util.KeyScope.lambda$getChildScope$32(KeyScope.java:47)
                at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
                at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
                at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
                at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
                at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
                at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
                at org.dita.dost.util.KeyScope.getChildScope(KeyScope.java:47)
                at org.dita.dost.module.KeyrefModule.walkMap(KeyrefModule.java:258)
                at org.dita.dost.module.KeyrefModule.walkMap(KeyrefModule.java:293)
                at org.dita.dost.module.KeyrefModule.walkMap(KeyrefModule.java:293)
                at org.dita.dost.module.KeyrefModule.walkMap(KeyrefModule.java:293)
                at org.dita.dost.module.KeyrefModule.collectProcessingTopics(KeyrefModule.java:164)
                at org.dita.dost.module.KeyrefModule.execute(KeyrefModule.java:121)
                at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:80)
                at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:230)
                at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
                at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                at org.apache.tools.ant.Task.perform(Task.java:348)
                at org.apache.tools.ant.Target.execute(Target.java:435)
                at org.apache.tools.ant.Target.performTasks(Target.java:456)
                at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
                at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
                at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
                at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
                at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
                at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
                at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                at org.apache.tools.ant.Task.perform(Task.java:348)
                at org.apache.tools.ant.Target.execute(Target.java:435)
                at org.apache.tools.ant.Target.performTasks(Target.java:456)
                at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
                at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
                at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
                at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
                at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
                at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
                at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                at org.apache.tools.ant.Task.perform(Task.java:348)
                at org.apache.tools.ant.Target.execute(Target.java:435)
                at org.apache.tools.ant.Target.performTasks(Target.java:456)
                at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
                at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
                at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
                at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
                at org.apache.tools.ant.Main.runBuild(Main.java:857)
                at org.apache.tools.ant.Main.startAnt(Main.java:236)
                at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
                at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

**Comment by jelovirt** [comment] 2017-10-16 14:47
Are you able to reproduce this with `develop`?

**Comment by raducoravu** [comment] 2017-10-17 08:07
I will ask our client to do that, I do not have the samples myself.

**Comment by raducoravu** [comment] 2017-10-24 20:30
End user tested the latest development version from the download page and obtained the same stack trace.

**Comment by raducoravu** [comment] 2017-11-13 08:35
End user did not provide the samples. Maybe you could guard the situation and show a logger.error if you find null child scopes in the list. Or look in all places where the list of child scopes is populated and see if there are places where a null can be added to it.

**Comment by raducoravu** [comment] 2019-11-19 06:52
I'm not sure what to do with bugs like this, the problem definitely exists, the end user cannot provide samples, we can guard the error in the code but we'll not understand how the error came to be because we guard the side effect and not the origin of the problem. I would still keep this open though.

**Comment by jelovirt** [comment] 2020-08-30 09:07
Closing this, because we have now way of reproducing and fixing this. If the same issue is encountered, hopefully next time we can get a sample set for reproduction.

**Closed by jelovirt** 2020-08-30 09:07 UTC
Labels: bug, preprocess/keyref
