### ISSUE TITLE
Standalone Java jar for PDF/HTML conversion

### ISSUE THREAD

**Issue by boudhayan-dev** [dita-ot/dita-ot#3488] opened 2020-03-27 14:09 UTC
## Description
Hi,

It would be really helpful if we can have a Java library downloadable via Maven that can do the DITA to PDF/HTML conversion. I have a web application that makes use of DITA files to render some UIs. We are currently looking for possible ways to provide DITA to PDF conversion from the web application. The current setup for achieving the same involves the presence of local installation of the DITA-OT tool along with the dost.jar. This would be quite challenging, if not impossible to set-up in a PaaS application environment like Cloud Foundry.

## Possible Solution

Standalone Java library that does not require any local DITA tool installation.

## Potential Alternatives
I have not come across any libraries that accomplishes DITA to PDF conversion.

**Comment by jelovirt** [comment] 2020-05-16 07:43
This is a feature that's been in the wish list for ages. Due to plugin backwards compatibility and dependency to Ant, this has been difficult to achieve. Closing this issue because implementing the requested feature is an epic/project level effort.

**Closed by jelovirt** 2020-05-16 07:43 UTC

**Comment by jelovirt** [comment] 2020-05-16 07:49
Duplicate of #3513

**Comment by jelovirt** [comment] 2020-05-16 07:51
Created project https://github.com/orgs/dita-ot/projects/23 for this.
