### ISSUE TITLE
Resolve coderef before conref

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2141] opened 2015-11-19 20:50 UTC
Currently, the preprocessing order of operations resolves coderefs late — after conref resolution is complete. This can result in coderefs not being resolved. For example:

* Topic A contains an example with a coderef in it.
* Topic B conrefs the example from topic A.

At the time the file lists are generated, Topic B doesn't have a coderef in it, so the coderef never gets resolved in topic B, only in topic A.

This can easily be fixed by moving coderef resolution before conref resolution. A coderef will never require conref resolution of its contents, so changing the order won't result in conrefs not being resolved.

**Comment by eerohele** [comment] 2015-11-20 07:09
Can reproduce on the `develop` branch and [this set of files](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/2141).

**Comment by jelovirt** [comment] 2015-11-20 10:15
The answer is not to resolve conref before conref, but rather just make sure conref process will update job configuration. Resolving coderef before conref is one option, but not the only one.

**Comment by jelovirt** [comment] 2015-11-20 10:22
Looking at the code and I wonder if we should just merge coderef into same topic fragment (STF) processing, since STF as has already been extended to also handle table normalization. Coming up with a module/target name is kinda challenging since completely different processing takes place in the same SAX pipe, but I think it's more important to yield correct results and be fast than to have a separate step for everything.

**Closed** 2016-02-25 09:49 UTC
Labels: bug, preprocess
