### ISSUE TITLE
Broken library references in org.dita.pdf2 in DITA-OT 3.1

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2997] opened 2018-06-12 13:56 UTC
Publication throws:

```
dropping ...\dita-ot-3.1\lib\saxon.jar from path as it doesn't exist
dropping ...\dita-ot-3.1\lib\saxon-dom.jar from path as it doesn't exist
dropping ...\dita-ot-3.1\lib\resolver.jar from path as it doesn't exist
dropping ...\dita-ot-3.1\lib\icu4j.jar from path as it doesn't exist
dropping ...\dita-ot-3.1\lib\saxon.jar from path as it doesn't exist
dropping ...\dita-ot-3.1\lib\saxon-dom.jar from path as it doesn't exist
dropping ...\dita-ot-3.1\lib\resolver.jar from path as it doesn't exist
dropping ...\dita-ot-3.1\lib\icu4j.jar from path as it doesn't exist
```

Because of org.dita.pdf2/build.xml

```xml
<path id="project.class.path">
      <pathelement path="${java.class.path}"/>
      <pathelement location="${lib.dir}/saxon.jar"/>
      <pathelement location="${lib.dir}/saxon-dom.jar"/>
      <pathelement location="${lib.dir}/resolver.jar"/>
      <pathelement location="${lib.dir}/icu4j.jar"/>
      <pathelement location="${fo.lib.dir}/fo.jar"/>
</path>
```

And those jars do not exist

**Comment by jelovirt** [comment] 2018-06-13 09:54
`project.class.path` is not actually being used for anything. It will be removed in 3.2.

**Comment by jelovirt** [comment] 2018-06-13 09:59
Duplicate of #2832

**Closed by jelovirt** 2018-06-13 09:59 UTC
Labels: P3, enhancement, good first issue, pdf
