### ISSUE TITLE
Logs many FOP DEBUG messages

### ISSUE THREAD

**Issue by c-kunz** [dita-ot/dita-ot#3000] opened 2018-06-15 13:21 UTC
## Expected Behavior
Rendering a PDF using DITA-OT 3.1 will not show any FOP logging messages, as described in *FOP debug logging* (http://www.dita-ot.org/3.1/topics/log-files.html).

## Actual Behavior
Logs many FOP `DEBUG` messages, siginificantly slowing down build time.

For comparison: build time using DITA-OT 2.4.6 was 4-5 times quicker.

## Copy of the error message, log file or stack trace

Small excerpt of the logs, notice the small increments in time (since it logs so much):
```
[...]
      [fop] 14:00:41.561 [main] DEBUG org.apache.fop.pdf.PDFObject - Embedded Tr
ueType/OpenType font
      [fop] 14:00:41.563 [main] DEBUG org.apache.fop.pdf.PDFObject - Writing 263
84 bytes of TTF font data
      [fop] 14:00:41.565 [main] DEBUG org.apache.fop.pdf.PDFObject - Embedded Tr
ueType/OpenType font
[...]
```

## Environment

* DITA-OT version: 3.1
* Operating system and version:
  Windows 7 x64
* How did you run DITA-OT?
  `"%DITA_HOME%/bin/ant" -f "%DITA_HOME%/build.xml" -Dbasedir="." -Dargs.input="path/to/file.ditamap" -Doutput.dir="pdf" -Dtranstype=pdf`
* Transformation type:
  _PDF_

**Comment by jelovirt** [comment] 2018-06-17 15:03
What's your classpath? Did you use `startcmd.bat` to open a new console and used the `CLASSPATH` it defines?

**Comment by c-kunz** [comment] 2018-06-19 08:15
> Did you use startcmd.bat to open a new console and used the CLASSPATH it defines?

I just opened a new `cmd.exe` *without* startcmd.bat and run DITA-OT with
```
"%DITA_HOME%/bin/ant" -f "%DITA_HOME%/build.xml" -Dbasedir="." -Dargs.input="path/to/file.ditamap" -Doutput.dir="pdf" -Dtranstype=pdf
```

I noticed that when running DITA-OT without ANT but with the `dita` CLI tool, there are no FOP messages as expected, so I'm using this as a workaround now:
```
"%DITA_HOME%/bin/dita.bat" -f pdf -i "path/to/file.ditamap" -o "pdf"
```

**Comment by jelovirt** [comment] 2018-06-19 08:43
If you run DITA-OT via Ant command line tool, you have to set the classpath somewhere, e.g. in `CLASSPATH` system variable or with `-l` arguments to Ant. Without the classpath none of the DITA-OT libraries are available to the process and DITA-OT cannot be ran. If you _are_ able to run DITA-OT without setting the classpath, this means you may have a global `CLASSPATH` configured with an older version of DITA-OT.

**Comment by c-kunz** [comment] 2018-06-20 06:47
I neither have a global `CLASSPATH` set nor `ANT_HOME`. As far as I'm concerned I'm solely relying on running DITA-OT using the Batch script `%DITA_HOME%/bin/ant.bat`.

I've looked into that script, and found the following section, which I can confirm is being called:
https://github.com/dita-ot/dita-ot/blob/bfba3b912c35dc58686c3a2b168e41f5b7c82c77/src/main/bin/ant.bat#L137-L138

These are the environment variables in the above command and its values at runtime:

| Environment variable | Value |
|----------------------|---------------------------------------------------|
| %_JAVACMD% | C:\Program Files\Java\jdk1.8.0_162\bin\java.exe |
| %ANT_OPTS% |  |
| %ANT_HOME% | C:\Program Files\dita-ot-3.1\bin\.. |
| %ANT_ARGS% |  |
| %ANT_CMD_LINE_ARGS% |  -f "C:\Program Files\dita-ot-3.1/build.xml" -Dbasedir "." -Dargs.input "path\to\file.ditamap" -Doutput.dir "pdf" -Dtranstype pdf |

I hope that helps :smile:

**Comment by jelovirt** [comment] 2018-06-20 15:46
Ok, so the reason is that while Ant is able read the libraries from `lib` directory, it doesn't have the `config/logback.xml` configuration that's needed to configure the logging levels.

The `bin/ant` and `bin/ant.bat` are distributed just for backward compatibility and we really should remove them because they cause problems like these when ran without correct configuration.

Closing this as not a bug, the log configuration works as expected when used with e.g. `-lib %DITA_HOME%\config`

**Closed by jelovirt** 2018-06-20 15:46 UTC
