### ISSUE TITLE
Images referenced in conref source copied to output

### ISSUE THREAD

**Issue by easirois** [dita-ot/dita-ot#1364] opened 2012-08-20 19:56 UTC
I was doing some testing with some of our production content and noticed something wonky in the output when publishing XHTML content.

We have a common file that contains all of common content that gets used as part of a conref.  Common content include product names etc.  So we never have a topicref of xref to it, just conrefs for now.  The content is in a sibling directory to the one being processed.

What happens is the image.list file get a list of images that includes the whole directory structure:

```
common.doc/doc/common.gif
test.doc/doc/topic.gif
```

And the files copied directly as listed in the image.list file into the output directory.  Though the file common.dita is referenced, it's dependencies should not be included in the output.  

Here is what the source directory structure looks like:

```
common.doc
  |
   -- doc
         |
         -- common.dita
         -- common.gif

test.doc
 |
 -- aMap.ditamap
 -- doc
       |
       -- aTopic.dita
       -- topic.gif
```

**Comment by jelovirt** [comment] 2017-05-20 06:22
We already run image metadata collection after preprocessing. In order to fix this, we would need to move image copy from beginning of preprocessing to HTML5 and XHTML specific code. It might be safest to do this at 3.0 because it can break custom Ant configurations.

**Comment by jelovirt** [comment] 2017-05-20 06:24
Duplicate of #1988

**Closed by jelovirt** 2017-05-20 06:24 UTC
Labels: bug, preprocess/conref, xhtml
