### ISSUE TITLE
"An empty sequence is not allowed" XSLT error [DITA OT 2.2.2 and older]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2212] opened 2016-01-29 11:53 UTC
In my DITA topic I have a CALS table like this:

``` xml
<table frame="none">
    <title>Flowers</title>
    <tgroup cols="3">
        <colspec colname="c1" colnum="1" colwidth="171.0pt"/>
        <colspec colname="c2" colnum="2" colwidth="99.0pt"/>
        <colspec colname="c3" colnum="3" colwidth="99.0pt"/>
        <thead>
            <row>
                <entry colname="c2">Flower</entry>
                <entry>Flower</entry>
                <entry colname=" c3 ">Type</entry>
            </row>
        </thead>
        <tbody>
            <row>
                <entry>Snowdrop</entry>
                <entry>perennial</entry>
                <entry>perennial</entry>
            </row>
        </tbody>
    </tgroup>
</table>
```

and I publish to XHTML. The publishing breaks with:

> D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.xhtml\build_general.xml:182: Fatal error during transformation using D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.xhtml\xsl\dita2xhtml.xsl: An empty sequence is not allowed as the value of variable $colspec; SystemID: file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl; Line#: 2106; Column#: -1

**Comment by raducoravu** [comment] 2016-01-29 11:56
But probably the problem resides in the code which rewrites the table colspecs, the initial columns named "c1", "c2"... seem to be rewritten as "col1", "col2".. but not everywhere. The table in the example is probably not valid according to the specs but it's very hard to detect the problem from the error message.

**Comment by raducoravu** [comment] 2016-01-29 12:00
For the same sample the PDF generation complains with:

     D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2\build.xml:297: Fatal error during transformation using D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2.fop\xsl\fo\topic2fo_shell_fop.xsl: An empty sequence is not allowed as the value of variable $entryNumber; SystemID: file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/plugins/org.dita.pdf2/xsl/fo/tables.xsl; Line#: 426; Column#: -1

**Comment by raducoravu** [comment] 2016-01-29 12:22
Another example of invalid CALS table which breaks the XHTML generation:

            <table frame="none">
                <title>Flowers</title>
                <tgroup cols="1">
                    <thead>
                        <row>
                            <entry>Flower1</entry>
                            <entry>Flower2</entry>
                        </row>
                    </thead>
                    <tbody>
                        <row>
                            <entry>Snowdrop</entry>
                            <entry>perennial</entry>
                        </row>
                    </tbody>
                </tgroup>
            </table>

but this one works in the PDF output.

**Comment by jelovirt** [comment] 2016-01-29 14:32
Does this occur with `develop` code?

**Comment by raducoravu** [comment] 2016-02-01 08:18
I can still reproduce the problem with both samples when publishing to XHTML, the error is at an identical location for both cases:

          [xslt] C:\Users\radu_coravu\Documents\dot-develop\src\main\plugins\org.dita.xhtml\xsl\xslhtml\dita2htmlImpl.xsl:2094: Fatal Error! An empty sequence is not allowed as the value of variable $colspec

**Comment by eerohele** [comment] 2016-02-02 15:34
I can also reproduce the issue.

I guess the problem is really that both of these examples are really content issues. I at least don't really know how the incongruous colspec names in the first tables should be interpreted. The second table has the wrong `@cols` value.

I suppose the `NormalizeTableFilter` class could print a warning or throw an error in both of these cases, but I there might be a pretty big number of cases like that to account for. Schematron would probably be a good fit for this sort of "error" checking.

The shortcut is to make DITA-OT ignore errors like these like this (I think this has been proposed as a solution in other related issues, as well):

```diff
diff --git a/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl b/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl
index d7b47b9..438806e 100644
--- a/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl
+++ b/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl
@@ -2091,7 +2091,7 @@
   <xsl:variable name="row" select=".." as="element()"/>
   <xsl:variable name="body" select="../.." as="element()"/>
   <xsl:variable name="group" select="../../.." as="element()"/>
-  <xsl:variable name="colspec" select="../../../*[contains(@class, ' topic/colspec ')][@colname and @colname = $this-colname]" as="element()"/>
+  <xsl:variable name="colspec" select="../../../*[contains(@class, ' topic/colspec ')][@colname and @colname = $this-colname]" as="element()?"/>
   <xsl:variable name="table" select="../../../.." as="element()"/>

   <xsl:variable name="framevalue">
```

**Comment by raducoravu** [comment] 2016-02-03 06:06
@eerohele I agree with everything, actually in Oxygen XML Editor 18.0 we'll have table layout validation done automatically as the user is editing each topic. Also agree with fixing the XSLT stylesheets to make the publishing succeed. Because XSLT errors like the ones reported now "An empty sequence is not allowed...." don't help anyone and the same samples worked with DITA OT 1.8. Indeed some proper table validation done in a certain stage of the DITA OT processing could be interesting (although it should probably be done on DOM and not SAX) but it's something not very easy to do.

**Comment by raducoravu** [comment] 2016-02-03 06:07
By the way, for the first example the PDF processing also fails at:

     An empty sequence is not allowed as the value of variable $entryNumber; ...........  org.dita.pdf2/xsl/fo/tables.xsl; Line#: 426

**Comment by jelovirt** [comment] 2016-02-26 20:07
Related to this, I'm actually not sure if we want to have the column name normalization code. Since the transtype specific code should not rely on the column names to be the source of which column index the column is part of. Thus, I would prefer to keep the column names the same as before and then just use the custom attributes to provide additional information to make transtype processing easier.

**Comment by robander** [comment] 2016-05-02 20:22
This one's tagged as 2.2.3 but was not fixed there - removing the tag.

**Comment by robander** [comment] 2016-05-02 20:23
(But didn't mean to close it, hit the wrong button.)

**Comment by robander** [comment] 2016-05-06 16:29
The just-closed issue #1715 is another instance of bad CALS markup (`@colnum` values in the wrong order) that throws off table processing. If we ever update our table processing to add any of the CALS validation mentioned above, this is another thing to check for.

**Comment by deegle** [comment] 2016-08-18 13:56
Thanks. Solved the issue after much head scratching. I will propagate out to our team. One small thing, in OT 2.2, line number is 2108.

**Closed** 2017-03-28 04:24 UTC
Labels: bug, P1, xhtml

**Comment by raducoravu** [comment] 2017-05-08 16:54
There is also this problem when two cells overlap on the same row:

        <table id="table_mlp_h1w_tz">
          <tgroup cols="7">
            <colspec colnum="1" colname="col1"/>
            <colspec colnum="2" colname="col2"/>
            <colspec colnum="3" colname="col3"/>
            <colspec colnum="4" colname="col4"/>
            <colspec colnum="5" colname="col5"/>
            <colspec colnum="6" colname="col6"/>
            <colspec colnum="7" colname="col7"/>
            <tbody>
              <row>
                <entry>
                  <p> </p>
                  <p>K2</p>
                </entry>
                <entry namest="col2" nameend="col3">K3</entry>
                <entry namest="col3" nameend="col4">K4</entry>
                <entry>
                  <p> </p>
                  <p>K5</p>
                </entry>
                <entry/>
              </row>
            </tbody>
          </tgroup>
        </table>

and the publishing breaks with an error like:

    /Applications/Oxygen XML Editor/frameworks/dita/DITA-OT2.x/plugins/org.dita.xhtml/xsl/xslhtml/tables.xsl:370:2: Fatal Error! An empty sequence is not allowed as the value of variable $colspec

which could either be more precise, have a better message or we could relax the checks.

**Comment by pwright73** [comment] 2018-01-17 20:36
Can this repair be retrofitted to OT 2.3.1? Stuck on that version for the time being.

**Comment by raducoravu** [comment] 2018-01-18 05:41
You can probably try to open the XSLT "DITA-OT2.3.1/plugins/org.dita.xhtml/xsl/xslhtml/tables.xsl" and apply @robander 's fix on it:

https://github.com/dita-ot/dita-ot/commit/9550f10681f0fa1f8638c44d1c26d4b2cbc66dd1
