### ISSUE TITLE
Keyscope + branch filtering potential bug

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2240] opened 2016-02-24 08:18 UTC
Related to this discussion I had no the DITA specs list:

https://lists.oasis-open.org/archives/dita-comment/201602/msg00001.html

So in one place of the DITA Map I have:

            <topichead navtitle="Test" collection-type="choice">
                <ditavalref href="topics/getting_started/install_windows.ditaval">
                    <ditavalmeta>
                        <dvrResourcePrefix>windows-</dvrResourcePrefix>
                        <dvrKeyscopePrefix>windows_scope-</dvrKeyscopePrefix>
                    </ditavalmeta>
                </ditavalref>
                
                <topicref href="topics/install.dita"
                    keys="topicref_install"
                    keyscope="scope_install"/>
         </topichead>

and in some other place I have a keyref like:

        <topicref
          keyref="windows_scope-scope_install.topicref_install"/>

From what I understand the keyref is invalid because the "windows_scope-" prefix must only be applied on the @keyscope attribute specified on the topichead in which the ditavalref is placed. 
But the DITA OT 2.x processes the keyref as valid and finds the target topic.

As the @keyscope is missing on the topichead, according to the specs the @keyscope on the topichead will become "windows-" so the proper way to have the keyref would be:

        <topicref
          keyref="windows_scope-.scope_install_select_parallel.topicref_install_select_parallel"/>

which currently does not work using DITA OT 2.x.

What's your opinion on this?

**Comment by jelovirt** [comment] 2016-02-24 08:32
@robander @drmacro @keberlein TC members, you call which is the correct behaviour.

**Comment by raducoravu** [comment] 2016-02-24 08:49
@jelovirt are you right now using the dvrKeyscopePrefix on all key scopes defined inside the topicref which contains the ditavalref?

**Comment by jelovirt** [comment] 2016-02-24 09:50
@raducoravu I don't remember any more and I don't have time to check the code right now. Once the TC members comment on what is the correct behaviour, we can verify whether the implementation needs fixing.

**Comment by jelovirt** [comment] 2016-02-24 13:57
Checked the code and OT indeed does cascade the prefix to all descendant keyscopes.

**Comment by drmacro** [comment] 2016-02-24 16:55
Reading the spec I think I have to agree that it specifies that keyscope prefixes and suffixes are applied to all keyscopes in the branch, in addition to setting the keyscope on the branch topicref if it does not already specify @keyscope (but not adding @keyscope to descendant topicrefs that do not specify #keyscope.

The phrase "for each key scope in the branch" seems clear. Likewise, the rules for combining multiple prefixes and suffixes clearly imply that ancestor values apply to descendants and that section clearly applies to both kinds of renaming metadata.

Given that understanding, then the effective branch from Radu's example would be:

~~~~
        <topichead keyscope="windows_scope-"
              navtitle="Test" collection-type="choice" >
            <topicref href="topics/install.dita" copy-to="topics/windows-install.dita"
                keys="topicref_install"
                keyscope="windows_scope-scope_install"/>
     </topichead>
~~~~

Meaning that to refer to the key "topicref_install" from outside this branch you would use the key reference `"windows_scope-.windows_scope-topicref_install.topicref_install"`. (Key scopes apply to the keys defined on the scope-defining topicref per this statement: 

"A key scope includes the following components:

- _The scope-defining element_ (italics mine)
-The elements that are contained by the scope-defining element, minus the elements that are contained by child key scopes
-The elements that are referenced by the scope-defining element or its descendants, minus the elements that are contained by child key scopes"

That is, the topicref with the key "topicref_install" is in the direct scope "windows_scope-topciref_install", which is then in the parent scope "windows-scope-".

I think that this is probably not what the spec should specify--I don't see any value in further qualifying descendant scopes--it clearly leads to a surprising and somewhat nonsensical result. 

If this is not what we intended the spec to say then we need to log an errata about it now before too many implementations get this far. If we did intend the spec to work this way then we need to publish a clear example of this case somewhere because if Radu was confused then other implementors will be as well.

It's also slightly ambiguous as to what should happen with descendent topicrefs that have no keyscope specified--do they get the same scope prefix set as their key scope? (I don't think so--that would make absolutely no sense at all.)

Note that it *does* make sense to propagate prefixes and suffixes for *resources* as otherwise you could end up with duplicate filenames.

But I think the spec as written is clear that prefixes and suffixes get applied to all descendant explicitly-specific key scopes.

**Comment by drmacro** [comment] 2016-02-24 18:50
Looking at the reference entry for dvrKeyscopePrefix, it seems to more clearly imply that it only applies to the filtered branch itself:

"For map branches that are implied by <ditavalref> elements, the value of the <dvrKeyscopePrefix> element contributes to the effective key scope names _of the branch_. The effective key scope names start with the value of the <dvrKeyscopePrefix> element. Note that if the branch as authored does not specify a @keyscope value, specifying <dvrKeyscopePrefix> (without also specifying <dvrKeyscopeSuffix>) results in the branch establishing a key scope whose name is the value of the <dvrKeyscopePrefix> element. The full key scope names also will reflect the value of a <dvrKeyscopeSuffix> element if one is specified, regardless of whether the branch as authored specifies a @keyscope value." (Italics added)

That is certainly more in line with how I thought the facility should work, and I think really has to work.

If the key scope prefixes are added to descendant scope names then it's impossible to author a key reference to keys within a peer scope and have them work in the branch as filtered, without, for example, having conditional copies of the reference, one for each filtered copy of the branch, which completely undoes the value of the facility.

For example, if I have two child scopes, "child-01" and "child-02", in the context of scope "child-01" I can have a keyref to "child-02.somekey" and it will resolve without branch filtering. But if the rule as implemented by the OT is used, that reference will fail if branch filtering is applied with a prefix or suffix because now the effective key scope name is "prefix-child-02". Obviously there's no way to author a single link that will subsequently work in all such copies of the branch.

I think that argues for clarifying the language in the architectural spec and correcting the OT behavior to reflect what the reference entry says (that is, do not propagate keyspace prefixes to descendant key scopes).

**Comment by drmacro** [comment] 2016-02-24 18:57
I've created  test case for this scenario here:

https://github.com/dita-community/dita-test-cases/tree/master/key-spaces/branch-filtering-name-augmentation-01

I believe this reproduces the conditions Radu reported. 

In my testing, the OT 2.2.2 resolves the link to the child scoped key when there is an explicit @keyscope on the filtered branch but not when there is not. It is implementing the propagation of the key scope prefix to the child scope's name.

**Comment by jelovirt** [comment] 2016-02-24 21:11
Since we're talking about a given DITA implementation and not DITA in general, we can reduce the scope of this issue. Basically, all keyscope processing can be ignored and this issue only deals with branch filtering, since OT will first process branch filtering as a separate step and only then deal with keys. Thus, this is only about whether key scope prefixes and suffixes should be cascaded to children, or only to branch parent.

**Comment by drmacro** [comment] 2016-02-24 21:23
Also the issue of using the prefix and/or suffix as the key scope if @keyscope is not specified on the filtered branch.

The key references in my test case are simply there to demonstrate how the OT is building the key scopes. I don't think the functioning of the key reference resolution is in question.

**Comment by jelovirt** [comment] 2016-02-24 21:25
FYI, the unit tests for branch filtering are at https://github.com/dita-ot/dita-ot/tree/develop/src/test/resources/BranchFilterModuleTest

**Comment by robander** [comment] 2016-02-24 21:26
As I understand it (and as clarified to me by @ctnitchie ) the key scope prefix / suffix should not cascade. This came out of discussions last year where we determined this would not enable anything useful. Chris fortunately remembered a bit more of those discussions and reminded me of them on the dita-comment list: https://lists.oasis-open.org/archives/dita-comment/201602/msg00004.html

The language Eliot highlighted in his first response -- "for each key scope in the branch" -- is confusing but should be read to mean "For each key scope name specified for the current branch". [Remember, you can have `keyscope="one two three"` to give three scope names.] 

As Eliot noted in the second response, the `<dvrKeyscopePrefix>` description is a bit clearer about the intent.

**Comment by drmacro** [comment] 2016-02-24 21:29
Whew--that makes me feel much better. 

In that case, the current OT behavior is in error on two counts:

1. prefix/suffix not used as @keyscope value when @keyscope not specified on filtered branch
2. prefix/suffix propagated to descendant key scopes when it should not be.

I'll update my test case to reflect this understanding since I agree with Robert and Chris N. that it's the only sensible interpretation.

**Comment by jelovirt** [comment] 2016-02-24 23:06
Fixed on `hotfix/2.2.3` branch. Please test to verify the code is now correct.

**Comment by drmacro** [comment] 2016-02-24 23:07
I'll test later this evening.

**Comment by drmacro** [comment] 2016-02-25 00:28
My test passes with hotfix/2.2.3

**Closed** 2016-02-25 05:22 UTC
Labels: bug, needs-reproduction, P2, preprocess/filtering

**Comment by raducoravu** [comment] 2016-02-25 06:41
:+1: Also works with my tests.
