### ISSUE TITLE
Text only in Relationship Tables

### ISSUE THREAD

**Issue by wbrisett** [dita-ot/dita-ot#1987] opened 2015-07-31 08:57 UTC
We have a few instances where we need to have a Related Information point to documents that cannot be obtained on via a URI. In these instances, one would assume that Open Toolkit would simply use the navtitle with no link. However, in my testing, I could never get this work. Instead the navtitle of the <topicref> was simply ignored. One suggestion was to use a <topichead> this too failed to produce any relationship table output. 

If a link doesn't appear in a relationship table via a topicref, can we get just the navtitle to appear? I'm we're not the only people would could use this feature.

**Comment by jelovirt** [comment] 2015-07-31 09:21
There's existing issue for this and IIRC I didn' implement it back then because someone vetoed. I think this is a useful feature and should be implemented. :+1:

**Comment by wbrisett** [comment] 2015-07-31 09:30
Thanks Jarno. I really have a hard time believing that others wouldn't find this a useful feature. I understand there are implications, but depending on the industry people work in, there are times where document A may be available to a certain set of customers, but because they haven't signed the proper licensing, they have no access to document B. However, they could sign licensing if they knew they needed. Unfortunately that means documents just aren't available outside of secure downloading areas and thus the best we can do is point to them with text only. This is the second company I have worked for that has struggled with this issue, so I know it's not uncommon.

**Comment by xephon2** [comment] 2015-07-31 09:42
Maybe you can query the licenses of your customers (or calculate their application context), and then use them as filter parameters for your build scenarios in the meantime.

**Comment by YvesBarbion** [comment] 2015-07-31 09:44
I agree with Jarno and Wayne: this would be a useful feature. :thumbsup:

**Comment by eerohele** [comment] 2015-07-31 09:47
>There's existing issue for this and IIRC I didn' implement it back then because someone vetoed.

#1132 perhaps?

**Comment by jelovirt** [comment] 2015-07-31 10:19
Yep, closing as duplicate of #1132

**Closed by jelovirt** 2015-07-31 10:19 UTC
