### ISSUE TITLE
Conref from less-specialized element to more-specialized is not resolved

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2292] opened 2016-04-09 23:46 UTC
The test here:

https://github.com/dita-community/dita-test-cases/tree/master/content-references/conkeyref

Demonstrates the issue.

Given a task with a step with the ID "step-01" and a generic topic, a conref from a list item to the step is not resolved--the OT reports that the reference cannot be resolved.

But a reference from a <step> element in task topic to the same step works, so the issue appears to be the mismatch of element types.

In this case, the referenced element should be generalized to reflect the type of the referencing element.

**Comment by eerohele** [comment] 2016-04-10 14:43
Sounds like a duplicate of #1884.

**Comment by eerohele** [comment] 2016-04-15 06:49
Closing as duplicate of #1884.

**Closed by eerohele** 2016-04-15 06:49 UTC
Labels: bug, duplicate, preprocess/conref
