### ISSUE TITLE
DITA-OT 2.1 PDF: Short description not rendered in some circumstances

### ISSUE THREAD

**Issue by keberlein** [dita-ot/dita-ot#2023] opened 2015-08-31 09:03 UTC
In the following circumstances, the short description is not rendered:
 * Using a bookmap
 * Setting "args.chapter.layout" to "BASIC"

This can be reproduced using the taskbook.ditamap sample. This is a change in behavior compared to DITA-OT 1.8.5.

Screen capture of PDF generated using DITA-OT 2.1:
![2 1-pdf](https://cloud.githubusercontent.com/assets/1863046/9575422/9d5b35ee-4f9d-11e5-84be-05ca10e2ba80.png)

Screen capture of PDF generated using DITA-OT 1.8.5
![1 8 5-pdf](https://cloud.githubusercontent.com/assets/1863046/9575416/915ce404-4f9d-11e5-8baa-4c3764583307.png)

**Comment by raducoravu** [comment] 2015-08-31 09:22
I can reproduce this also on the latest DITA OT 2.x develop branch.
Probably in the XSLT stylesheet:

      plugins\org.dita.pdf2\xsl\fo\commons.xsl

the xsl:when:

                      <xsl:when test="$chapterLayout='BASIC'">
                          <xsl:apply-templates select="*[not(contains(@class, ' topic/topic ') or contains(@class, ' topic/title ') or
                                                             contains(@class, ' topic/prolog '))]"/>
                          
                      </xsl:when>

should have an extra block inside it which shows the short description content:

                          <fo:block xsl:use-attribute-sets="p">
                              <xsl:apply-templates select="*[contains(@class,' topic/shortdesc ')
                                  or contains(@class, ' topic/abstract ')]/node()"/>
                          </fo:block>

but I'm not sure this is the best solution.

**Comment by raducoravu** [comment] 2015-08-31 09:29
Actually the problem is this template:

    <xsl:template match="*[contains(@class, ' topic/topic ')]/*[contains(@class,' topic/shortdesc ')]" priority="1">

which overrides the shortdesc processing and does not seem to be doing anything for chapter and appendix references.

**Comment by jelovirt** [comment] 2015-08-31 09:30
Chapter and appendix needs to pull-process `shortdesc` and `abstract`.

**Comment by robander** [comment] 2015-11-04 18:48
@jelovirt @raducoravu Can this be merged into 2.2? Looks like it is done, from glancing at the commit, but I have not tested it.

**Comment by raducoravu** [comment] 2015-11-05 06:12
I checked and this fix is not yet integrated in the development branch. I think I closed the pull request before it got accepted. I can try to issue another pull request if Jarno agrees with my possible fix.

**Comment by keberlein** [comment] 2015-11-05 09:36
I'd really appreciate this being fixed in 2.2.
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 11/5/2015 1:12 AM, Radu Coravu
      wrote:
    
    
      I checked and this fix is not yet integrated in the development
        branch. I think I closed the pull request before it got
        accepted. I can try to issue another pull request if Jarno
        agrees with my possible fix.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jelovirt** [comment] 2015-11-05 09:40
I'll cherry-pick c246f33 to `develop` once I get home.

**Comment by keberlein** [comment] 2015-11-05 09:41
Thanks!
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 11/5/2015 4:40 AM, Jarno Elovirta
      wrote:
    
    
      I'll cherry-pick c246f33 to develop
        once I get home.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by infotexture** [comment] 2016-01-10 23:14
Looks like this is still open. Can we get it in for 2.2.2?

**Comment by keberlein** [comment] 2016-01-11 13:01
Please. I've hacked an instance of the DITA-OT for OASIS to deal
    with this, but I am waiting for a fix on this before suggesting to
    any of my clients that they upgrade from 1.8.5.
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 1/10/2016 6:14 PM, Roger Sheen
      wrote:
    
    
      Looks like this is still open. Can we get it in for 2.2.2?
      —
        Reply to this email directly or view
          it on GitHub.

**Closed** 2016-01-12 17:29 UTC
Labels: bug, good first bug, pdf
