### ISSUE TITLE
NPE when generating Eclipse Help [DOT 2.0]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1885] opened 2015-04-02 10:48 UTC
A DITA composite like:

``` xml
<!DOCTYPE dita PUBLIC "-//OASIS//DTD DITA Composite//EN" "ditabase.dtd" []>
<dita>
 <glossentry id="abc123">
    <glossterm>Term 1</glossterm>
    <glossdef>Definition 1</glossdef>
  </glossentry>
</dita>
```

A bookmap with a glossarylist pointing to it:

``` xml
<backmatter>
    <booklists>
    <glossarylist><topicref href="Glossary.dita" print="yes" navtitle="Glossary" type="glossary"/> </glossarylist>
    <indexlist/>
    </booklists>
</backmatter>
```

The NPE:

```
C:\Users\radu_coravu\Desktop\DOT2.0.1\DITA-OT2.0.1\build.xml:41: The following error occurred while executing this line:
C:\Users\radu_coravu\Desktop\DOT2.0.1\DITA-OT2.0.1\plugins\org.dita.base\build_preprocess.xml:78: Failed to run pipeline: null
    at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:199)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: org.dita.dost.exception.DITAOTException
    at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:248)
    at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
    at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
    ... 29 more
Caused by: java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength(Unknown Source)
    at java.util.regex.Matcher.reset(Unknown Source)
    at java.util.regex.Matcher.<init>(Unknown Source)
    at java.util.regex.Pattern.matcher(Unknown Source)
    at java.util.regex.Pattern.split(Unknown Source)
    at java.util.regex.Pattern.split(Unknown Source)
    at org.dita.dost.util.DitaClass.<init>(DitaClass.java:45)
    at org.dita.dost.writer.ExportAnchorsFilter.startElement(ExportAnchorsFilter.java:107)
    at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:90)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startElement(RelaxNGDefaultsComponent.java:200)
    at org.apache.xerces.impl.xs.XMLSchemaValidatorXerces.startElement(XMLSchemaValidatorXerces.java:392)
    at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:107)
    at org.apache.xerces.impl.dtd.XMLDTDValidatorXerces.startElement(XMLDTDValidatorXerces.java:831)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:268)
    at org.apache.xerces.impl.XMLNSDocumentScannerImplXerces$NSContentDispatcher.scanRootElementHook(XMLNSDocumentScannerImplXerces.java:733)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1756)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:150)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
    at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
    at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
    at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
    at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
    at org.dita.dost.module.GenMapAndTopicListModule.processFile(GenMapAndTopicListModule.java:456)
    at org.dita.dost.module.GenMapAndTopicListModule.processWaitList(GenMapAndTopicListModule.java:398)
    at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:238)
    ... 31 more
```

**Comment by raducoravu** [comment] 2015-04-02 10:48
Based on report:

https://groups.google.com/forum/#!topic/dita-ot-users/2NjylTglFb4

**Comment by easirois** [comment] 2015-04-02 12:44
Hmm.. I don't believe that scenario was ever tested. That is producing eclipse help from a bookmap. Regular DITA map or eclipse map should be used.  I'll post a comment in the Google group.

**Comment by easirois** [comment] 2015-12-03 16:12
Coming back to this.  When I was at IBM we just wrapped the glossentry in a reference topic and that worked fine.  I don't think that doing so in a composite document was ever tested or supported.

<reference id="glossary">
   <glossentry id="abc123">
      <glossterm>Term 1</glossterm>
      <glossdef>Definition 1</glossdef>
    </glossentry>
  </reference>

**Comment by easirois** [comment] 2016-01-14 20:44
It looks like IBM DB2 did not use the glossary specialization.  It used definition lists to implement something like a glossary.

**Comment by raducoravu** [comment] 2016-01-15 07:11
I confirm that I can still reproduce it with DITA OT 2.2.1:

                BUILD FAILED
                C:\Users\radu_coravu\Desktop\DOT 2.2\dita-ot-2.2.1\build.xml:41: The following error occurred while executing this line:
                C:\Users\radu_coravu\Desktop\DOT 2.2\dita-ot-2.2.1\plugins\org.dita.base\build_preprocess.xml:42: Failed to run pipeline: null
                	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:199)
                	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
                	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
                	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                	at java.lang.reflect.Method.invoke(Unknown Source)
                	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                	at org.apache.tools.ant.Task.perform(Task.java:348)
                	at org.apache.tools.ant.Target.execute(Target.java:435)
                	at org.apache.tools.ant.Target.performTasks(Target.java:456)
                	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
                	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
                	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
                	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
                	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
                	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
                	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
                	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                	at java.lang.reflect.Method.invoke(Unknown Source)
                	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                	at org.apache.tools.ant.Task.perform(Task.java:348)
                	at org.apache.tools.ant.Target.execute(Target.java:435)
                	at org.apache.tools.ant.Target.performTasks(Target.java:456)
                	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
                	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
                	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
                	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
                	at org.apache.tools.ant.Main.runBuild(Main.java:851)
                	at org.apache.tools.ant.Main.startAnt(Main.java:235)
                	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
                	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
                Caused by: org.dita.dost.exception.DITAOTException
                	at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:246)
                	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
                	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
                	... 29 more
                Caused by: java.lang.NullPointerException
                	at java.util.regex.Matcher.getTextLength(Unknown Source)
                	at java.util.regex.Matcher.reset(Unknown Source)
                	at java.util.regex.Matcher.<init>(Unknown Source)
                	at java.util.regex.Pattern.matcher(Unknown Source)
                	at java.util.regex.Pattern.split(Unknown Source)
                	at java.util.regex.Pattern.split(Unknown Source)
                	at org.dita.dost.util.DitaClass.<init>(DitaClass.java:45)
                	at org.dita.dost.writer.ExportAnchorsFilter.startElement(ExportAnchorsFilter.java:106)
                	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:101)
                	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
                	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startElement(RelaxNGDefaultsComponent.java:200)
                	at org.apache.xerces.impl.xs.XMLSchemaValidatorXerces.startElement(XMLSchemaValidatorXerces.java:392)
                	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:107)
                	at org.apache.xerces.impl.dtd.XMLDTDValidatorXerces.startElement(XMLDTDValidatorXerces.java:831)
                	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:268)
                	at org.apache.xerces.impl.XMLNSDocumentScannerImplXerces$NSContentDispatcher.scanRootElementHook(XMLNSDocumentScannerImplXerces.java:733)
                	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1756)
                	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
                	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
                	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:150)
                	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
                	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
                	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
                	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
                	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
                	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
                	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
                	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
                	at org.dita.dost.module.GenMapAndTopicListModule.processFile(GenMapAndTopicListModule.java:451)
                	at org.dita.dost.module.GenMapAndTopicListModule.processWaitList(GenMapAndTopicListModule.java:392)
                	at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:237)
                	... 31 more

**Comment by easirois** [comment] 2016-01-18 16:04
@raducoravu - Is that with a plain DITA Map, with the bookmap, the Eclipse Map or all three?

**Comment by raducoravu** [comment] 2016-01-19 06:05
@easirois  It's a bookmap, as I stated in the original report.

**Comment by jelovirt** [comment] 2016-01-19 18:16
Can't reproduce with `develop`.

**Comment by raducoravu** [comment] 2016-01-20 08:42
I confirm, I built a DITA OT distribution from develop branch and I can no longer reproduce problem.

**Comment by raducoravu** [comment] 2016-06-28 05:53
Somebody else encountered the same problem on the DITA Users List:

https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/40478

I checked and the problem is not fixed in DITA OT 2.3.

**Comment by raducoravu** [comment] 2016-07-07 10:47
Stack trace obtained with latest DITA OT developer code:

            Caused by: java.lang.NullPointerException
            	at java.util.regex.Matcher.getTextLength(Unknown Source)
            	at java.util.regex.Matcher.reset(Unknown Source)
            	at java.util.regex.Matcher.<init>(Unknown Source)
            	at java.util.regex.Pattern.matcher(Unknown Source)
            	at java.util.regex.Pattern.split(Unknown Source)
            	at java.util.regex.Pattern.split(Unknown Source)
            	at org.dita.dost.util.DitaClass.<init>(DitaClass.java:45)
            	at org.dita.dost.writer.ExportAnchorsFilter.startElement(ExportAnchorsFilter.java:104)
            	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:101)

**Comment by easirois** [comment] 2016-07-07 17:05
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Ahh...it seems the issue is that because <dita> does not have a @class, the code is crapping out.  I can take a peek at what needs to be done to fix it. 

    On Thursday, July 7, 2016 6:47 AM, Radu Coravu <notifications@github.com> wrote:
 

 Stack trace obtained with latest DITA OT developer code:        Caused by: java.lang.NullPointerException
            at java.util.regex.Matcher.getTextLength(Unknown Source)
            at java.util.regex.Matcher.reset(Unknown Source)
            at java.util.regex.Matcher.<init>(Unknown Source)
            at java.util.regex.Pattern.matcher(Unknown Source)
            at java.util.regex.Pattern.split(Unknown Source)
            at java.util.regex.Pattern.split(Unknown Source)
            at org.dita.dost.util.DitaClass.<init>(DitaClass.java:45)
            at org.dita.dost.writer.ExportAnchorsFilter.startElement(ExportAnchorsFilter.java:104)
            at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:101)

**Comment by fviolette** [comment] 2017-01-03 12:57
Any foreseeable update for this one? Would really save the day.

Thanks!

**Comment by jelovirt** [comment] 2017-01-04 05:38
Fixed by testing for null class. Basically the same approach as in #2553, but pushes to class stack on every start element.

**Closed** 2017-01-04 05:39 UTC
Labels: bug, needs reproduction, P1

**Comment by fviolette** [comment] 2017-01-05 12:56
Works on my end!
