### ISSUE TITLE
Update DITA-OT to ship FOP 2.0

### ISSUE THREAD

**Issue by Simalot** [dita-ot/dita-ot#1958] opened 2015-06-30 19:28 UTC
FOP 2.0 was released at the beginning of June. It contains a lot of updates; for me currently, the most important being OpenType CFF font support. I replaced the OT 2.01 and 2.1.0 fop directories with FOP 2.0, and in my limited testing have not found any issues.

Here are the release notes for FOP 2.0: https://xmlgraphics.apache.org/fop/2.0/releaseNotes_2.0.html

**Comment by raducoravu** [comment] 2015-07-01 05:01
I played with FOP 2.0 producing PDF from our user's manual about 1500 DITA topics and it threw a NullPointerException at some point:

https://issues.apache.org/jira/browse/FOP-2479

Users on the Docbook users list have also encountered this exception when producing PDF from Docbook.

So either we ship also a patch for the problem or we might consider waiting for FOP 2.1.

**Comment by geewrites** [comment] 2015-07-27 14:13
Issue FOR-2479 is closed as a duplicate of this issue:

   https://issues.apache.org/jira/browse/FOP-2461

FOR-2461 is still open but has a workaround. FWIW.

**Comment by raducoravu** [comment] 2016-01-15 11:42
Fop 2.1 just came out:

http://apache-fop.1065347.n5.nabble.com/ANN-Apache-FOP-2-1-Released-td43379.html

From what I tested seems to have resolved my NPE problem.

**Comment by jelovirt** [comment] 2016-05-22 16:21
@robander do you want to risk updating FOP for 2.3 release this close to the release?

**Comment by jelovirt** [comment] 2016-09-15 08:00
Skip to upgrade to FOP 2.1 #2399

**Closed by jelovirt** 2016-09-15 08:00 UTC
Labels: feature, P2, pdf
