### ISSUE TITLE
Support table cell entry @rotate attribute

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2717] opened 2017-06-08 11:37 UTC
Based on this [DITA Users List feedback](https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/42339):

>  I have tried text rotation in cells using <entry rotate=”1”> No rotation occurred. Does anyone have any suggestions as to why this might not be working?

As a possible solution in the XSLT stylesheet:

          DITA-OT\plugins\org.dita.pdf2\xsl\fo\tables.xsl

the template with mode "processTableEntry" could be modified as such:

            
                <xsl:template match="*" mode="processTableEntry">
                    <xsl:call-template name="commonattributes"/>
                    <xsl:call-template name="applySpansAttrs"/>
                    <xsl:call-template name="applyAlignAttrs"/>
                    <xsl:call-template name="generateTableEntryBorder"/>
                    <fo:block-container reference-orientation="{if (@rotate eq '1') then 90 else 0}">                
                        <fo:block xsl:use-attribute-sets="tbody.row.entry__content">
                            <xsl:apply-templates select="." mode="ancestor-start-flag"/>
                            <xsl:call-template name="processEntryContent"/>
                            <xsl:apply-templates select="." mode="ancestor-end-flag"/>
                        </fo:block>
                    </fo:block-container>
                </xsl:template>

Only Antenna House seems to have decent support for this from what I tested. Both XEP and Apache FOP do not properly render the table.

**Comment by jelovirt** [comment] 2017-06-08 11:51
We should _not_ generate `fo:block-container` elements unless they are absolutely needed. They will mess up `@start-indent` and other other similar properties. Thus, if something like this is added, we need to only generate the container if it's rotated.

**Comment by raducoravu** [comment] 2017-06-08 12:12
👍

**Comment by ToshihikoMakita** [comment] 2017-06-09 12:29
>  They will mess up @start-indent and other other similar properties.

What the meaning of the phase "mess up"?
Even if `fo:block-container` is located inside the `fo:table-cell`, the `@start-indent` is inherited from `fo:table-caption` to inside the `fo:block-container`. This inheritance should be the feature of XSL-FO specification.

So there should be no influence to generate  redundant `fo:block-container` inside `fo:table-cell`.

**Comment by kirkilj** [comment] 2019-02-08 22:40
How is this issue related to #1778?

**Comment by robander** [comment] 2019-02-09 14:09
@kirkilj this appears to be a duplicate of 1778 - I had not noticed the extra copy, or I would have closed one of them a while back. Thanks for helping to clean up the list of issues.

#3161 is about ready to go, and will handle the `@rotate` attribute in the upcoming 3.3 release for this issue / for 1778.

**Closed** 2019-02-20 18:58 UTC
Labels: dita standard, duplicate, feature, plugin/pdf, priority/medium
