### ISSUE TITLE
depend.preprocess.pre transforms don't resolve doctype on Windows

### ISSUE THREAD

**Issue by simonbate** [dita-ot/dita-ot#3142] opened 2018-11-07 21:43 UTC
## Expected Behavior
An <xslt> target invoked using depend.preprocess.pre should resolve doctypes on Windows.

## Actual Behavior
Works great on Mac. Fails on Windows.
(Also works great on DITA-OT 1.8 and before.)

## Steps to Reproduce

0. On a Windows machine
1. Create plugin using extension depend.preprocess.pre 
2. Ant target should employ &lt;xslt> task to open args.input.
3. &lt;xslt> task should include &lt;xslcatalog refid="dita.catalog"/>
4. When you run the transform, the doctype of args.input does not resolve, causing a fatal error.

This is the my Ant target:
       &lt;!-- [SP] 2018-11-05 sfb: NOTE: the properties file must be stored in the output.dir because there is no temp folder at this point. --> 
       &lt;xslt processor="trax" basedir="${basedir}" destdir="${output.dir}"
            force="true"
            in="${args.input}"
            out="${output.dir}${file.separator}topics.properties"
            style="${common.plugin.xsl.dir}${file.separator}map2topic_list.xsl">
            &lt;param name="TEMPDIR" expression="${source_dir}"/>
            &lt;xmlcatalog refid="dita.catalog"/>
        &lt;/xslt>

## Copy of the error message, log file or stack trace

Relevant content from ant -debug:
     [xslt] Loading stylesheet C:\Users\simonbate\Documents\!SimonWork\Xxx\dita-ot-2.5.4\plugins\com.xxx.XXX_common2\xsl\map2topic_list.xsl
java.lang.NoSuchFieldException: _isNotSecureProcessing
resolveEntity: '-//OASIS//DTD DITA BookMap//EN': 'file:/C:/Users/simonbate/Documents/!SimonWork/Xxx/bookmap.dtd'
Class org.apache.tools.ant.types.resolver.ApacheCatalogResolver loaded from parent loader (parentFirst)
Apache resolver library found, xml-commons resolver will be used
Using catalogpath 'C:\Users\simonbate\Documents\!SimonWork\Xxx\dita-ot-2.5.4\catalog-dita.xml'
Parsing C:\Users\simonbate\Documents\!SimonWork\Xxx\dita-ot-2.5.4\catalog-dita.xml
No matching catalog entry found, parser will use: 'file:/C:/Users/simonbate/Documents/!SimonWork/Xxx/bookmap.dtd'
     [xslt] : Fatal Error! java.io.FileNotFoundException: C:\Users\simonbate\Documents\!SimonWork\Xxx\bookmap.dtd (The system cannot find the file specified) Cause: java.io.FileNotFoundException: C:\Users\simonbate\Documents\!SimonWork\Xxx\bookmap.dtd (The system cannot find the file specified)

## Environment

Windows 7 and Windows 10. Does not happen on MacOS.
Java 1.8.

* DITA-OT version: 2.5.4
* Operating system and version:
Windows 7 and Windows 10
* How did you run DITA-OT?
    Ant
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
* Transformation type:
   Custom
  _(HTML5, PDF, custom, etc.)_

**Comment by jelovirt** [comment] 2018-11-08 06:30
Based on the error messages, the exclamation mark is probably related to the root cause.

**Comment by simonbate** [comment] 2018-11-08 14:23
I think the exclamation point issue is a markdown problem in GitHub. I'm attaching the snippet, rather than using GitHub. 
[resolver_issue.txt](https://github.com/dita-ot/dita-ot/files/2562097/resolver_issue.txt)

I've used exclamation point in my paths for years. I did try it with an OT in the root of my C: drive, but I got the same error.

Simon

**Comment by simonbate** [comment] 2018-11-08 15:10
I made sure both source and OT didn't have ! in their paths. Still got the same error.
[resolver_issue_no_bang.txt](https://github.com/dita-ot/dita-ot/files/2562278/resolver_issue_no_bang.txt)

Simon

**Comment by raducoravu** [comment] 2018-11-09 05:41
I don't quite like this error that @simonbate is obtaining: "java.lang.NoSuchFieldException: _isNotSecureProcessing". That particular field is inside the main ant.jar inside the class "org.apache.tools.ant.taskdefs.optional.TraXLiaison". This might mean there are some incompatibilities between two different used ANT libraries. 
Is that DITA OT 2.5.4 a stock DITA OT distribution (downloaded from the official DITA OT web site) or is it copied from Oxygen and/or with various changes made to it? If

**Comment by simonbate** [comment] 2018-11-12 18:01
Hi Radu,

I just ran it with a clean 2.5.4 OT however, I'm still seeing the "NoSuchFieldException" error.

Your question about "which distribution?" may have a bearing down the road for us, because our client requires us to use the preprocess behavior when building the Oxygen WebHelp Responsive in a stand-alone OT (in their CCMS). Initially, I was running the transform with the Oxygen XML WebHelp Responsive plugin installation kit, however when I encountered the resolver issue, I removed those plugins as part of my testing. That was why I wanted to be sure I was working with a clean OT.

Taking this back to the original preprocessor question, I wonder if there's a correlation between the "NoSuchFieldException" error and the preprocessor error.

Simon

**Comment by simonbate** [comment] 2018-11-13 13:58
Hi Radu,

Using a separate DITA OT distribution with the xhtml plugin and my preprocessing plugin fails with the same issue: the doctype is not resolved.

Simon

**Comment by raducoravu** [comment] 2018-11-13 20:37
@simonbate maybe you could attach a sample DITA OT plugin to the issue along with a sample DITA project. Or send them to support@oxygenxml.com and I could try to take a look at them when I have some time.

**Comment by simonbate** [comment] 2018-12-19 20:56
Hi Radu,

I finally got a chance to reduce this to it's simplest form. 

Using Open toolkits on Windows machines, the attached plugin works on OT 1.8.5, but does not work in 2.5.4 or in 3.2.1. To use it, integrate it into your OT, then try to generate output from docsrc/samples/hierarchy.map (samples/hierarchy.map in 1.8.5). You can use it with any standard OT formatting plugin (such as pdf2 or xhtml), the result is the same. 

Simon
[com.xxx.common.zip](https://github.com/dita-ot/dita-ot/files/2696461/com.xxx.common.zip)

**Comment by simonbate** [comment] 2019-01-09 18:57
Some further input. It occurred to me that processing of depend.preprocess.pre could be occurring before the environment was ready for the resolver to work correctly, so I tried moving the processing to depend.preprocess.topicpull.pre. Unfortunately, the behavior is the same. 

The Ant debug results tell me that the catalogpath is resolving correctly, but that the Public ID for the DITA map is not matching in the catalog.
 
If anyone can give me insight to this, I'd appreciate it. Again, works on OT 1.8; fails on OT 2.x and 3.x on Windows only (but works fine on macOS). 

Puzzled.

**Comment by raducoravu** [comment] 2019-01-10 12:42
@simonbate At some point I found a similar problem with another XSLT stylesheet trying to load an XML document containing a DOCTYPE using the document() function, I'm attaching a plugin which has a patch for one of the ANT Java classes responsible of parsing XML catalogs. Can you try to install this plugin along side yours and see if yours work?

[com.oxygenxml.ant.patches.zip](https://github.com/dita-ot/dita-ot/files/2745305/com.oxygenxml.ant.patches.zip)

**Comment by simonbate** [comment] 2019-01-10 16:59
Hi @raducoravu and thanks for the plugin. The bad news is: it didn't make a difference.

The good news is: I found a work-around, which points clearly to a problem in xml-commons on Windows. 

I changed the xmlcatalog in the Ant xslt task to point _specifically_ to C:/DITA-OT/dita-ot-2.5.4/plugins/org.oasis-open.dita.v1_3/dtd/technicalContent/catalog.xml and it worked. 

I then modified the xmlcatalog so that it pointed to one folder level up (C:/DITA-OT/dita-ot-2.5.4/plugins/org.oasis-open.dita.v1_3/dtd/catalog.xml) and it failed again. So, there seems to be something wrong in handling of nextCatalog in xml-commons in Windows.

I believe my use of the xslt task is the only time xslt is called outside of dost.jar (aka "pipeline"), which may have something to do with the reason the resolver is failing. 

Simon

**Comment by raducoravu** [comment] 2019-01-11 12:02
@simonbate Strange about the plugin not working, I tested it before I uploaded it. I assume you properly integrated the plugin and run from the command line the transformation using the "bin\dita" script. If you copy the JAR library from the plugin directly to the DITA OT "lib" folder does it work?
I investigated this problem some time ago when one of our plugins had the same problem. The problem was with the ANT code which wraps the Apache XML Catalog resolver not properly following the "nextCatalog" entries so this is what the patch tries to address.

**Comment by simonbate** [comment] 2019-01-11 18:42
Thanks @raducoravu, that did solve it. The difference is that I usually run the OT via a Ant project files that are derived from the Ant projects in ant_sample. (This helps ensure repeatability of my test cases, and also helps me retain information about test cases from month to month.)

When I ran the test transform using the bin\dita command, it worked (but only when I used your plugin; if I disabled your plugin it failed again). So your patch is essential to using a preprocessor extension transform.

This might be a separate ticket: As a further test, I ran the ant_sample\sample_pdf.xml Ant project using both your plugin and my preprocessor extension transform. The project failed, just as I've been seeing before. So something is missing or in error in the Windows environment when build.xml is called using the ant task and a preprocessor extension is used.

Thanks again,
Simon

**Comment by raducoravu** [comment] 2019-01-14 07:39
Hi @simonbate, thanks for the update. As things are right now, I do not consider this to be a DITA Open Toolkit bug. Also DITA OT plugins which use XSLT to load DITA topics which still have the DOCTYPE declaration inside are very rare although we also have one on the oxygenxml github organization:
https://github.com/oxygenxml/dita-ot-metrics

So for now I will close this issue. I will try to find some time in the future to look again at why I made that ANT library patch and if I could maybe propose my fix to the ANT project. Also if I come to the conclusion this is a DITA OT bug I will re-open the issue.

**Closed by raducoravu** 2019-01-14 07:39 UTC
Labels: platform/windows

**Comment by raducoravu** [comment] 2019-04-30 05:44
Just to update this thread is somebody else stumbles upon it, there was a similar report on the DITA users list and the replies contain two more possible workarounds:
https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/44670

**Comment by thendarion** [comment] 2020-01-23 12:45
ran into this issue 😢 

the yahoo link's not working

will try one of the workarounds

**Comment by thendarion** [comment] 2020-01-23 13:02
@raducoravu  how's your pull request to Ant is faring? :)

**Comment by raducoravu** [comment] 2020-01-23 13:06
I have this idea of looking more into this and adding an issue on the ANT project as a registered issue on my side.
I wanted to understand better why the problem occurred in order to add an issue on the ANT issues list and I did not find the time to do that.

**Comment by raducoravu** [comment] 2020-01-23 13:12
I think I found the link to the DITA Users List discussion now located on the Groups.io web site:
https://groups.io/g/dita-users/topic/48673261#44287

**Comment by thendarion** [comment] 2020-01-23 13:18
I see
thanks for the link 😊
