### ISSUE TITLE
if parallel=true, some files are not rendered

### ISSUE THREAD

**Issue by thendarion** [dita-ot/dita-ot#3917] opened 2022-04-25 07:29 UTC
## Expected Behavior
all files are rendered

## Actual Behavior
some files are skipped with error "folder could not be created". seemingly randomly in documents, but consistently between builds

## Steps to Reproduce
render a document with a lot of topics in the same subfolder (?)

## Copy of the error message, log file or stack trace
[xslt] Failed to transform document: Failed to transform document: Failed to create directory 

## Environment

* DITA-OT version: 3.7.1, 3.6.1
* Operating system and version:
  Linux, Windows
* How did you run DITA-OT?
  `dita` command
* Transformation type:
  HTML5

**Comment by jelovirt** [comment] 2022-04-25 07:31
@thendarion Could you share at which point in the log are `folder could not be created` output?

**Comment by thendarion** [comment] 2022-04-25 07:41
it happens in "html5.topics.common.inner"

**Comment by thendarion** [comment] 2022-04-25 07:52
I looked at the log more closely and I have a custom plugin that also suffers from  `folder could not be created` when `parallel="true"` so it isn't a HTML5-specific issue but more like a race condition between the XSLT threads it feels like

**Comment by chrispy-snps** [comment] 2022-04-26 15:43
@thendarion - I tried making a synthetic testcase with N topic files (I used N=1000), published with `--parallel=yes` repeatedly in a forever loop, then printing the number of HTML topic files in the output directory after each iteration. For me, I get no loss of topics:

```
$ ./do.sh
1000
1000
1000
1000
1000
...continues many times...
```

I tried two different machines - one 12-core, one 24-core.

Maybe you could try this testcase on your side, with your plugin installed, and see what happens?

[ditaot_parallel.zip](https://github.com/dita-ot/dita-ot/files/8564735/ditaot_parallel.zip)

**Comment by thendarion** [comment] 2022-05-04 08:54
@chrispy-snps thanks for the test case

there's a misunderstanding here though

you have a structure like
```ASCII
-- dita
  |-- map.ditamap
  |-- topic1.dita
  |-- topic2.dita
  ...
```
while I've been encountering the bug when the structure is like
```ASCII
-- dita
  |-- map.ditamap
  |-- subfolder1
  |  |-- topic1.dita
  |  `-- topic2.dita
  |-- subfolder2
  |  |-- topic1.dita
  |  `-- topic2.dita
  ...
```
because it's about XSLT trying to create the same folder twice in parallel and colliding with itself

**Comment by chrispy-snps** [comment] 2022-05-04 13:46
@thendarion, good news - adding directory structure reproduces the issue!

I updated the script to group files into directories. For example, `make_topics.pl 6 2` makes a structure like this:

```
<map>
  <title>Test Map - 6 Topics</title>
  <topicref href="1_to_2/topic1.dita"/>
  <topicref href="1_to_2/topic2.dita"/>
  <topicref href="3_to_4/topic3.dita"/>
  <topicref href="3_to_4/topic4.dita"/>
  <topicref href="5_to_6/topic5.dita"/>
  <topicref href="5_to_6/topic6.dita"/>
</map>
```

Using `make_topics.pl 1000 2`, running `do.sh` gives sporadic directory creation failures:

```
1000
1000
1000
1000
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/1_to_2
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/777_to_778
998
1000
1000
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/843_to_844
999
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/519_to_520
999
1000
1000
1000
1000
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/575_to_576
999
1000
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/671_to_672
999
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/737_to_738
999
1000
1000
1000
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/323_to_324
999
1000
1000
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/671_to_672
999
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/91_to_92
999
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/367_to_368
```

What's strange is, certain failures seem to be more common than others. For example, a failure for "out/671_to_672/" happens noticeably more frequently if I let the script run for awhile. Other certain directory paths are more common too.

I tried both an NFS filesystem and two local disks, and it happens in all three locations. Interestingly, it only happens on a real linux box (the 24-core machine) and not in WSL (Windows Subsystem for Linux in Windows 10/11).

Updated testcase:

[ditaot_parallel2.zip](https://github.com/dita-ot/dita-ot/files/8620836/ditaot_parallel2.zip)

**Comment by chrispy-snps** [comment] 2022-05-04 15:25
It does seem to be a race condition in the XSLT. Here is one of the failures with `-verbose` specified:

```
html5.topics.common.inner:
     [xslt] Transforming into /home/dita/out
     [xslt] Loading stylesheet file:/u/doc/syncrosoft/oxygen-publishing-engine-3.x/plugins/org.dita.html5/xsl/dita2html5.xsl
     [xslt] Processing file:/tmp/tmpdir/893_to_894/topic893.dita to file:/home/dita/out/893_to_894/topic893.html
     [xslt] Processing file:/tmp/tmpdir/741_to_742/topic742.dita to file:/home/dita/out/741_to_742/topic742.html
     [xslt] Processing file:/tmp/tmpdir/199_to_200/topic200.dita to file:/home/dita/out/199_to_200/topic200.html
     [xslt] Processing file:/tmp/tmpdir/335_to_336/topic336.dita to file:/home/dita/out/335_to_336/topic336.html
     [xslt] Processing file:/tmp/tmpdir/467_to_468/topic467.dita to file:/home/dita/out/467_to_468/topic467.html
     [xslt] Processing file:/tmp/tmpdir/147_to_148/topic148.dita to file:/home/dita/out/147_to_148/topic148.html
     [xslt] Processing file:/tmp/tmpdir/935_to_936/topic936.dita to file:/home/dita/out/935_to_936/topic936.html
     [xslt] Processing file:/tmp/tmpdir/581_to_582/topic582.dita to file:/home/dita/out/581_to_582/topic582.html
     [xslt] Processing file:/tmp/tmpdir/311_to_312/topic312.dita to file:/home/dita/out/311_to_312/topic312.html
     [xslt] Processing file:/tmp/tmpdir/769_to_770/topic770.dita to file:/home/dita/out/769_to_770/topic770.html
     [xslt] Processing file:/tmp/tmpdir/765_to_766/topic765.dita to file:/home/dita/out/765_to_766/topic765.html
     [xslt] Processing file:/tmp/tmpdir/271_to_272/topic272.dita to file:/home/dita/out/271_to_272/topic272.html
     [xslt] Processing file:/tmp/tmpdir/993_to_994/topic994.dita to file:/home/dita/out/993_to_994/topic994.html
     [xslt] Processing file:/tmp/tmpdir/725_to_726/topic725.dita to file:/home/dita/out/725_to_726/topic725.html
     [xslt] Processing file:/tmp/tmpdir/471_to_472/topic471.dita to file:/home/dita/out/471_to_472/topic471.html
     [xslt] Processing file:/tmp/tmpdir/969_to_970/topic969.dita to file:/home/dita/out/969_to_970/topic969.html
     [xslt] Processing file:/tmp/tmpdir/747_to_748/topic747.dita to file:/home/dita/out/747_to_748/topic747.html
     [xslt] Processing file:/tmp/tmpdir/671_to_672/topic672.dita to file:/home/dita/out/671_to_672/topic672.html
     [xslt] Processing file:/tmp/tmpdir/671_to_672/topic671.dita to file:/home/dita/out/671_to_672/topic671.html
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /home/dita/out/671_to_672
```

Notice that at first, adjacent files are written to different directories. But just before the message, the last two files are a pair going into the same directory.

I wonder if the reason certain directory names show up in failures more often is because the thread allocation itself is pseudorandom or has some kind of non-uniform distribution, causing certain output file sequences - and thus, certain adjacent pairs - to occur more often?

**Comment by raducoravu** [comment] 2022-05-05 06:01
@chrispy-snps two questions, 

  - if you also set "store-type=memory" can you still reproduce the problem?
  - If in the DITA OT Java code you add a "synchronized" keyword to this method "org.dita.dost.store.StreamStore.getSerializer(URI)" like:
  
          synchronized Serializer getSerializer(final URI dst) throws IOException {
     then re-compile and publish with "store-type=file" can you still reproduce the problem?

**Comment by raducoravu** [comment] 2022-05-05 06:03
Because looking at the method:

     Serializer getSerializer(final URI dst) throws IOException {
        final File outputFile = new File(dst);
        final File dir = outputFile.getParentFile();
        if (!dir.exists() && !dir.mkdirs()) {
            throw new IOException("Failed to create directory " + dir.getAbsolutePath());
        }
        return xmlUtils.getProcessor().newSerializer(outputFile);
    }

this particular " if (!dir.exists() && !dir.mkdirs()) {", it may be possible that two threads enter at the same time inside the method, one of them checks if the directory exists and it does not yet exist, then the other creates the directory, then the first thread checks "dir.mkdirs()" which returns false because the directory was already created. This is why synchronizing the method so that only one thread can enter inside it at a time might help.

**Comment by chrispy-snps** [comment] 2022-05-05 10:36
I found that for _N_ topics, if I edit "do.sh" to put sqrt(_N_) topics in each directory:

```
# change this to the number of topics and topics-in-group you want
./make_topics.pl 1000 33
```

then the probability for collision is maximized:

```
% do.sh
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/826_to_858
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/397_to_429
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/727_to_759
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/397_to_429
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/793_to_825
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/826_to_858
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/1_to_33
993
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/826_to_858
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/397_to_429
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/397_to_429
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/364_to_396
996
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/67_to_99
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/826_to_858
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/826_to_858
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/397_to_429
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/463_to_495
     [xslt] Failed to transform document: Failed to transform document: Failed to create directory /chrispy/dita/out/397_to_429
994
```

thus making a more effective testcase. And with this configuration, even my 12-core machine starts giving occasional failures too.

@raducoravu - with your suggested fix, the issue is completely resolved on both machines:

```
% do.sh
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
...continues...
```

@jelovirt  - Radu's suggested fix is a one-word addition to line 238 at

https://github.com/dita-ot/dita-ot/blob/hotfix/3.7.2/src/main/java/org/dita/dost/store/StreamStore.java#L238

Do you want me to make a pull request, or is this simple enough for you to fix with a bare commit?

**Comment by raducoravu** [comment] 2022-05-05 10:47
In general in our Oxygen user's guide at least the parallel processing has not brought any significant time decrease so I have not used it much. The store-type=memory seems to help quite a lot on Windows though.

**Comment by jelovirt** [comment] 2022-05-11 14:22
@chrispy-snps are you able to test this with  #3925 merged?

**Closed** 2022-05-12 14:17 UTC
Labels: bug

**Comment by thendarion** [comment] 2022-05-24 13:56
thank you :)
