### ISSUE TITLE
Cannot convert string to double: "" [DITA-OT2.0.M3]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1694] opened 2014-06-17 07:33 UTC
Processing a DITA Map to XHTML (it has a topic which has colspecs with fixed widths):

> [xslt] C:\Users\radu_coravu\Desktop\DITA-OT2.0.M3\plugins\org.dita.xhtml\xsl\xslhtml\dita2htmlImpl.xsl:2329: Fatal Error! Cannot convert string to double: ""

The XSLT template:
```xml
<xsl:template match="*[contains(@class, ' topic/colspec ')]" mode="count-colwidth">
```
has a variable, probably the "otherwise" branch of the "xsl:choose" breaks:

```xml
<xsl:variable name="thiswidth">            <!-- Width of this column -->
  <xsl:choose>
    <xsl:when test="@colwidth"><xsl:value-of select="substring-before(@colwidth, '*')"/></xsl:when>
    <xsl:otherwise>1</xsl:otherwise>
  </xsl:choose>
</xsl:variable>
```

**Comment by jelovirt** [comment] 2015-03-11 14:45
In order to fix the code, we need to check what the browser support is for mixing absolute and relative widths.

```html
<table style="table-layout: fixed;
              width:100%;">
  <col style="width: 66%">  
  <col style="width: 40px">
```

Testing a HTML5 table with Chrome, regardless of the `table-layout` property, `width` of the table was always respected. However, when a same table had one table in percentages and one in absolute units, the results varied:

*   `fixed`: the absolute unit overrode the relative unit.
*   `auto`: the relative unit overrode the abolute unit.

The problem with OASIS table model `width="1*" is that it cannot be converted to percentages without knowing the width of the table.


```html
<fo:table table-layout="fixed"
          width="100%;">
  <fo:table-column column-width="proportional-column-width(2)"/>
  <fo:table-column column-width="40px"/>
```

Testing XSL-FO with AHF, table `width` was always respected and in `column-width` and absolute unit always took precedence.

**Comment by maht0rz** [comment] 2015-03-16 13:34
Is there any progress regarding this issue? I've came across is while generating HTML5 output out of DITA map. Would appreciate any help!

**Comment by eerohele** [comment] 2015-04-03 19:08
FWIW, using 2.0M3, I cannot reproduce the issue by simply introducing `<colspec>` elements with fixed widths like this:

```xml
<table>
  <tgroup cols="2">
    <colspec colname="c1" colnum="1" colwidth="171.0px"/>
    <colspec colname="c2" colnum="2" colwidth="171.0px"/>
    ...
```

I *can* reproduce the issue with 2.0M3 if I change the other `<colspec>` element to use
a relative width:

```xml
<table>
  <tgroup cols="2">
    <colspec colname="c1" colnum="1" colwidth="1*"/>
    <colspec colname="c2" colnum="2" colwidth="171.0px"/>
    ...
```

I cannot reproduce the issue using the latest code in the `develop` branch.

**Comment by jelovirt** [comment] 2015-04-04 04:28
@eerohele are you able to reproduce this with `develop` code? I've refactored the code there for cases when relative and absolute columns are mixed.

**Comment by eerohele** [comment] 2015-04-04 06:45
>@eerohele are you able to reproduce this with develop code? I've refactored the code there for cases when relative and absolute columns are mixed.

Nope, can't reproduce it.

**Comment by jelovirt** [comment] 2015-04-05 04:18
Ok, closing as fixed.

**Closed by jelovirt** 2015-04-05 04:18 UTC
Labels: bug, P2, xhtml
