### ISSUE TITLE
Faster implementation for ImgUtils.getWidth/getHeight

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1883] opened 2015-04-02 08:12 UTC
Right now methods like ImgUtils.getWidth load the entire image in memory.

Suggested replacement which does not read the entire image in memory before determining width and height:

        /**
         * Get the image size.
         * 
         * @param uri The systemId of the image.
         * @return A formatted string containing the width and the height, 
         * separated by a comma. If the image could not be read, the returned 
         * string is "-1,-1".
         */
        public static String getImageSize(String uri) {
          int width = -1;
          int height = -1;
          try {
            
            URL url = new URL(uri);
      
            ImageInputStream imageInputStream = ImageIO.createImageInputStream(url.openConnection().getInputStream());
            Iterator<ImageReader> iter = ImageIO.getImageReaders(imageInputStream);
            if (iter.hasNext()) {
              ImageReader reader = iter.next();
              try {
                reader.setInput(imageInputStream);
                width = reader.getWidth(reader.getMinIndex());
                height = reader.getHeight(reader.getMinIndex());
              } catch (IOException e) {
                // Continue with the next reader.
              } finally {
                reader.dispose();
                imageInputStream.close();
              }
            }
      
          } catch (IOException ex) {
            System.err.println("Cannot determine the image size for " + uri + " because of " + ex);
          }
          
          return width + "," + height;
        }

also the replacement returns both width and height in one go avoiding calling two methods, one for width and one for height.

**Comment by jelovirt** [comment] 2015-04-02 08:31
:+1: but ImgUtils isn't really used anymore in the latest code. This fix should go to ImageMetadataFilter, that also reads the DPI of the graphic.

**Comment by jelovirt** [comment] 2015-04-04 05:04
The old `ImgUtils.getHeight` is only used in ODT and possibly custom code. I'm closing this as the main uses are covered. If the ODT  needs to be improved as well, it can be done in a pull request.

**Closed by jelovirt** 2015-04-04 05:04 UTC

**Comment by raducoravu** [comment] 2015-04-06 05:16
In the latest sources you still left the code:

      final BufferedImage img = r.read(0);

which means the image is still loaded. It should probably be removed as this leads to no performance improvement.

**Comment by jelovirt** [comment] 2015-04-06 17:24
I left in the debug code and didn't change the load as a mistake. Corrected in 47a7d1d.

**Comment by ckab74** [comment] 2017-09-27 12:05
Our consultant used the imgUtils:getHeight/Width methods for our customized plug-in. I'm currently trying to update our DITA OT 2.0.1 to DITA OT 2.4.4 for testing purposes, and when I run our transformation in Oxygen, I get the following error message that I cannot resolve:
```
transform.topic2fo.main:
     [xslt] Processing T:\trunk_test\projects\en\temp\pdf\oxygen_dita_temp\stage1.xml to T:\trunk_test\projects\en\temp\pdf\oxygen_dita_temp\stage2.fo
     [xslt] Loading stylesheet T:\trunk_test\xml_framework\framework-oxy19\DITA-OT2_4_4\plugins\org.dita.pdf2.fop\xsl\fo\topic2fo_shell_fop.xsl
     [xslt] T:\trunk_test\xml_framework\framework-oxy19\DITA-OT2_4_4\plugins\com.smtg.pdf\Customization\fo\xsl\commons.xsl:641:84: Fatal Error! XPath syntax error at char 55 on line 641 in {...FileDirectory, $imageFileNa...}:
     [xslt]     Cannot find a matching 2-argument function named {org.dita.dost.util.ImgUtils}getHeight()
     [xslt] T:\trunk_test\xml_framework\framework-oxy19\DITA-OT2_4_4\plugins\com.smtg.pdf\Customization\fo\xsl\commons.xsl:644:83: Fatal Error! XPath syntax error at char 54 on line 644 in {...FileDirectory, $imageFileNa...}:
     [xslt]     Cannot find a matching 2-argument function named {org.dita.dost.util.ImgUtils}getWidth()
     [xslt] Failed to process T:\trunk_test\projects\en\temp\pdf\oxygen_dita_temp\stage1.xml

BUILD FAILED
T:\trunk_test\xml_framework\framework-oxy19\DITA-OT2_4_4\build.xml:45: The following error occurred while executing this line:
T:\trunk_test\xml_framework\framework-oxy19\DITA-OT2_4_4\plugins\org.dita.pdf2\build.xml:140: The following error occurred while executing this line:
T:\trunk_test\xml_framework\framework-oxy19\DITA-OT2_4_4\plugins\org.dita.pdf2\build.xml:276: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 2 errors detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:302)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:319)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:180)
	at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:878)
	at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:416)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:854)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
```

And this is the related code from the stylesheet:
```
<!-- Template for inline images to get the image height via Java function -->
	<xsl:template match="image[@placement = 'inline']" mode="smtg.getInlineImageHeight">
		<xsl:variable name="file-path">
			<xsl:choose>
				<xsl:when test="@scope = 'external'">
					<xsl:value-of select="@href"/>
				</xsl:when>
				<xsl:when test="opentopic-func:isAbsolute(@href)">
					<xsl:value-of select="@href"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="substring(concat($input.dir.url, @href), 7)"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		<xsl:variable name="imageFileName">
			<xsl:call-template name="smtg.getFileNameFromPath">
				<xsl:with-param name="path-snippet">
					<xsl:value-of select="$file-path"/>
				</xsl:with-param>
			</xsl:call-template>
		</xsl:variable>
		<xsl:variable name="imageFileDirectory">
			<xsl:value-of select="substring-before($file-path, $imageFileName)"/>
		</xsl:variable>
		<xsl:variable name="origImageHeight">
			<xsl:value-of select="imgUtils:getHeight($imageFileDirectory, $imageFileName)"/>
		</xsl:variable>
		<xsl:variable name="origImageWidth">
			<xsl:value-of select="imgUtils:getWidth($imageFileDirectory, $imageFileName)"/>
		</xsl:variable>
		<xsl:variable name="imageHeight">
			<xsl:choose>
				<xsl:when test ="@scale">
					<xsl:value-of select="0.01 * @scale * $origImageHeight"/>
				</xsl:when>
				<xsl:when test ="@width">
					<xsl:value-of select="@width * $origImageHeight div $origImageHeight"/>
				</xsl:when>				
				<xsl:when test="number($origImageHeight) &gt; number($maxInlineImageHeight)">
					<xsl:value-of select="$maxInlineImageHeight"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="$origImageHeight"/>
				</xsl:otherwise>
			</xsl:choose>
			<xsl:text>px</xsl:text>
		</xsl:variable>
		<xsl:value-of select="$imageHeight"/>
	</xsl:template>
```

Don't know what's wrong with the XPath, because that stylesheet used to work with our current DITA OT.

**Comment by jelovirt** [comment] 2017-09-27 12:53
@ckab74 the issue you're having has nothing to do with the original feature request. Please file a new bug report if you feel you've found a bug.

The issue you have seems to be caused by your XSLT using Java extension functions `getHeight` and `getWeight` that no longer exist in the version of DITA-OT you're using.

**Comment by ckab74** [comment] 2017-09-27 12:59
@jelovirt Sorry, Jarno, if I put this comment in the wrong place. At the moment, I don't think it's a bug.

Are there alternative functions that we can use for our plug-in?

**Comment by jelovirt** [comment] 2017-09-27 13:01
See http://www.dita-ot.org/contributing for links to support channels, this issue tracker is only meant for feature requests or bug reports.
