### ISSUE TITLE
dita-ot version 1.8 - broken css file path for dita in sub-folders

### ISSUE THREAD

**Issue by dan411** [dita-ot/dita-ot#1920] opened 2015-05-21 14:13 UTC
I use xmetal 10 and dita-ot 1.8 to generate html from a ditamap of topic references. My ditamaps and most of my dita files are in one folder. But some of those dita files are in a sub-folder within the same folder. In those cases, html output for those dita files should have href="../commonltr.css"  as the path to the generated stylesheet. But in dita-ot 1.8, the file path for these html files is simply href="commonltr.css". 

This does not happen when I generate html using other versions of dita-ot.

**Comment by eerohele** [comment] 2015-05-22 06:35
I can't reproduce this issue with [this set of files](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/1920) on DITA-OT 1.8.

@dan411: can you advise how I should change the files to reproduce the issue? Or are you maybe using some additional DITA-OT parameters?

Also, have you tried whether the issue occurs with DITA-OT 2.x?

**Comment by dan411** [comment] 2015-05-22 12:50
Interesting you couldn't reproduce the issue. Using a fresh, unedited install of xmetal 10, with no parameters added to dita-ot, I set up my own generic ditamap and dita topics similar as you have described above. I generated html from the ditamap using both dita-ot 1.8 and 2.0. Under these conditions, csspath for html in subdir is incorrect in 1.8 and correct in 2.0:

dita-ot 1.8: href="commonltr.css
dita-ot 2.0: href="../commonltr.css"

Are you using a clean unedited version of dita-ot 1.8? I ask because dita-ot 1.8 that I use with xmetal 10 was included with the installation, and has been customized a bit to work with their software. I do not know how extensive the customization is, but at this point the only thing I can think of is the bug was introduced by something they did. I have contacted xmetal support about this, waiting to hear back.

**Comment by eerohele** [comment] 2015-05-23 07:54
>Are you using a clean unedited version of dita-ot 1.8?

Yes, totally clean.

>dita-ot 1.8 that I use with xmetal 10 was included with the installation, and has been customized a bit to work with their software.

DITA-OT 1.8 suffers from issue #1639 (which was fixed in DITA-OT 1.8.2), which will cause the path to be `..%5Ccommonltr.css` on Windows. So I suppose it's possible that this issue is a combination of that and some customization in the DITA-OT version bundled with XMetal, but since I don't have access to XMetal, I can't say for sure.

**Comment by dan411** [comment] 2015-05-23 10:36
Thanks Eero. Actually just heard back from xmetal support. They were able
to reproduce the issue on xmetal 10 using 1.8. My guess is they were using
a version prior to 1.8.2. In any case, they sent me a fixed xslt. Hopefully
this will work. Thanks for your help!

**Closed** 2015-05-23 11:25 UTC
Labels: bug, invalid, xhtml
