### ISSUE TITLE
Path to PDF resources referenced through keyref mechanism are not computed correctly in the XHTML output

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2581] opened 2017-01-27 07:09 UTC
We have an issue report from a user that the links to PDF resources are broken in the XHTML output. The PDF references are done using the **keyref** mechanism.

The structure of a sample DITA project to reproduce the issue is:
![image](https://cloud.githubusercontent.com/assets/6837947/22362908/0ed08758-e46f-11e6-978d-4790acfe2200.png)

In the DITA map, the key is defined as follows:
`<keydef  keys="pdf-key" href="pdf/flowers.pdf" format="pdf"/>`

The key reference from **topic.dita** is:
`<p>Reference to the <xref keyref="pdf-key">PDF resource</xref>.</p>`
 
In the HTML document, the path to the PDF resource is generated like:
`<a class="xref" href="pdf/flowers.pdf" target="_blank">PDF resource</a>`

but it should be:
`<a class="xref" href="../pdf/flowers.pdf" target="_blank">PDF resource</a>`

A sample DITA project to reproduce the issue can be found in the next attachment: [pdf-keyref-issue.zip](https://github.com/dita-ot/dita-ot/files/734576/pdf-keyref-issue.zip)

**Comment by robander** [comment] 2017-02-01 16:40
I think this is the same issue that came up in #1951 (originally reported as an issue for peer links with relative paths, but in the comments, it was reproduced with local non-DITA links as well).

**Comment by jelovirt** [comment] 2017-04-24 04:57
From #2667

> Non-image and non-dita links should be resolved [here](https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/writer/KeyrefPaser.java#L427) against the `keyDef.source` as well.

**Comment by robander** [comment] 2019-02-21 15:43
This is a duplicate of #2620 -- local paths for non-DITA key targets are not adjusted when resolving the key.

**Comment by robander** [comment] 2019-02-25 03:51
Fixed with #3234

**Closed by robander** 2019-02-25 03:51 UTC
Labels: bug, preprocess/keyref, priority/medium
