### ISSUE TITLE
Case sensitivity problem in PDF2 customization override string files.

### ISSUE THREAD

**Issue by robertnthomas** [dita-ot/dita-ot#2790] opened 2017-09-19 21:32 UTC
## Expected Behavior
I expect that [customization.dir]/cfg/common/vars/zh_CN.xml will be found when doing a string lookup for xml:lang="zh-cn".

## Actual Behavior
[customization.dir]/cfg/common/vars/zh_CN.xml is not found unless it is renamed as 
[customization.dir]/cfg/common/vars/zh_cn.xml

## Possible Solution
Here are two possible solutions:
1) Change org.dita.dost.pdf2.VariableFileTask.java so that the language portion of the filename is mapped to lowercase.
Change: lang.setAttributeNS(XML_NS_URI, "xml:lang", n.substring(0, i).replace('_', '-'));
To: lang.setAttributeNS(XML_NS_URI, "xml:lang", n.substring(0, i).replace('_', '-').toLowerCase());
2) Change the findString template in dita-utilities.xsl so that the stringfile variable's select statement  uses the matches() function, with the ignore case flag active, rather than the = operator within the predicate portion of the XPath.
Change: <xsl:variable name="stringfile" select="$stringFiles[@xml:lang = $l]/@filename" as="xs:string*"/>
To: <xsl:variable name="stringfile" select="$stringFiles[matches(@xml:lang, $l, 'i')]/@filename" as="xs:string*"/>

## Steps to Reproduce

1. Add a language file to a customization for any of the following languages: pt-br, zh-cn, or zh-tw using file names pt_BR.xml, zh_CN.xml, or zh_TW.xml (these are the same names used in the org.dita.pdf2 plugin).
2. Change the graphic for the caution icon.
3. Run the dita-ot for one of the above languages and watch it ignore the customization file.

## Environment

* DITA-OT version: 2.5.3
* Operating system and version: Windows 10
  _(Linux, macOS, Windows)_
* How did you run DITA-OT?
Oxygen, but it doesn't matter in this case
* Transformation type:
Custom transtype that calls the org.dita.pdf2 plugin.

**Comment by robander** [comment] 2017-09-20 02:50
I'm guessing this is a duplicate of #2226 which I've run into a couple of times, and yeah, it would be good to make this case insensitive.

**Comment by robander** [comment] 2017-10-04 11:42
Fixed in 2.5.4 using a variation on your second suggestion.

**Closed by robander** 2017-10-04 11:42 UTC
Labels: bug, i18n, P3
