### ISSUE TITLE
HTML IDs

### ISSUE THREAD

**Issue by mironovalexey** [dita-ot/dita-ot#2685] opened 2017-05-12 07:42 UTC
Could someone clarify the expected result of HTML IDs generation?
Let's look at the following DITA fragment and the corresponding HTML output (cleaned up).
### XML
```xml
<concept id="roottopic"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="urn:oasis:names:tc:dita:xsd:concept.xsd">
    <title>Root</title>
    <conbody>
        <section id="roottopic-section">
            <title>Root topic section</title>
            <p>Text.</p>
        </section>
    </conbody>
    <concept id="nestedtopic">
        <title>Nested Topic</title>
        <conbody>
            <section id="nestedtopic-section">
                <title>Nested topic section</title>
                <p>Text.</p>
            </section>
        </conbody>
        <concept id="doublenestedtopic">
            <title>Double nested topic</title>
            <conbody>
                <section id="doublenestedtopic-section">
                    <title>Double nested topic section</title>
                    <p>Text.</p>
                </section>
            </conbody>
        </concept>
    </concept>
    <concept id="links">
            <p>Inner links:</p>
            <p><xref href="#roottopic"/></p>
            <p><xref href="#roottopic/roottopic-section"/></p>
            <p><xref href="#nestedtopic"/></p>
            <p><xref href="#nestedtopic/nestedtopic-section"/></p>
            <p><xref href="#doublenestedtopic"/></p>
            <p><xref href="#doublenestedtopic/doublenestedtopic-section"/></p>
         </conbody>
    </concept>
</concept>
```

### HTML
```html
<body id="roottopic">
<main role="main">
    <article>
        <h1>Root</h1>
        <div>
            <section id="roottopic__roottopic-section">
                <h2>Root topic section</h2>
                <p>Text.</p>
            </section>
        </div>
        <article id="roottopic__nestedtopic">
            <h2>Nested Topic</h2>
            <div>
                <section id="nestedtopic__nestedtopic-section">
                    <h3>Nested topic section</h3>
                    <p>Text.</p>
                </section>
            </div>
            <article id="nestedtopic__doublenestedtopic">
                <h3>Double nested topic</h3>
                <div>
                    <section id="doublenestedtopic__doublenestedtopic-section">
                        <h4>Double nested topic section</h4>
                        <p>Text.</p>
                    </section>
                </div>
            </article>
        </article>
        <article id="roottopic__links">
            <h2>Links</h2>
            <div>
                <p>Inner links:</p>
                <p><a href="#roottopic">Root</a></p>
                <p><a href="#roottopic__roottopic-section">Root topic section</a></p>
                <p><a href="#nestedtopic">Nested Topic</a></p>
                <p><a href="#nestedtopic__nestedtopic-section">Nested topic section</a></p>
                <p><a href="#doublenestedtopic">Double nested topic</a></p>
                <p><a href="#doublenestedtopic__doublenestedtopic-section">Double nested topic section</a></p>
            </div>
        </article>
    </article>
</main>
</body>
```
Links to nested topics are broken. Am I not mistaken that nested topic shouldn't inherit id of the parent topic? The links themselves seem to be correct.

The attached example also demonstrates that keyrefed xrefs to the nested topics didn't even resolve their texts.
[test.tar.gz](https://github.com/dita-ot/dita-ot/files/995369/test.tar.gz)

Related to #2443

**Comment by jelovirt** [comment] 2017-05-12 09:06
Duplicate of #2443

**Closed by jelovirt** 2017-05-12 09:06 UTC
Labels: bug, html5, P2

**Comment by mironovalexey** [comment] 2017-05-12 09:16
@jelovirt Jarno,  I just wanted to ask about the right way to generate IDs. I didn't find an answer in #2443. I see this bug in XSLT code, but cannot fix it without without sufficient understanding of ID generation rules.

**Comment by jelovirt** [comment] 2017-05-12 09:18
The rule is pretty simple:

*   for topic the ID is `<topic-id>`
*   for element the Id is `<parent-topic-id>__<element-id>`

**Comment by mironovalexey** [comment] 2017-05-12 09:21
Aha, thank you very much.
