### ISSUE TITLE
Appendix topics are not displayed/included in the PDF if they are wrapped in the <appendices> element

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2416] opened 2016-06-15 12:52 UTC
The PDF output does not display the topics that are wrapped in the `<appendices>` element.

Sample bookmap:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN"
 "http://docs.oasis-open.org/dita/v1.1/OS/dtd/bookmap.dtd">
<!-- (c) Copyright IBM Corp. 2004, 2007 All Rights Reserved. -->
<bookmap id="taskbook">
    <booktitle>
        <booklibrary>Retro Tools</booklibrary>
        <mainbooktitle>Product tasks</mainbooktitle>
        <booktitlealt>Tasks and what they can do</booktitlealt>
    </booktitle>
    
    <chapter href="tasks/configuring.dita"/>
        
    <appendices>
        <appendix href="topics/task_appendix.dita" print="yes"/>
    </appendices>
</bookmap>
```

[taskbook.zip](https://github.com/dita-ot/dita-ot/files/316129/taskbook.zip)

I've tested with DITA-OT 2.3.

**Comment by eerohele** [comment] 2016-06-15 12:54
Sounds like a duplicate of #2092.

**Comment by robander** [comment] 2016-06-15 14:11
Right - in my testing for #2092, it worked if `<appendices>` specifies `@href` but fails if it is just used as a grouping element. I may be able to take a look at this one this week - I was already working on some tweaks to Appendix rendering for some internal use.

**Comment by robander** [comment] 2016-06-15 14:55
Closing as a duplicate - there is a lot of discussion in the other issue.

**Closed by robander** 2016-06-15 14:55 UTC
Labels: bug, duplicate, pdf
