### ISSUE TITLE
2.5.2 DOA?

### ISSUE THREAD

**Issue by StanDoherty** [dita-ot/dita-ot#2760] opened 2017-08-02 22:06 UTC
I created one topic and one map to test whether the 2.5.1 flagging bugs were gone. FWIW, I could build neither PDF nor HTML5 with 2.5.2. Here's where the log reported PDF going off the tracks:

```
      [fop] [ERROR] Anttask - Error rendering fo file: C:\Users\SJD_BA~1\AppData
\Local\Temp\temp20170802180026298\topic.fo <org.apache.fop.apps.FOPException: or
g.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Requir
ed content model: marker* (%block;)+ (See position 1:-1)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationExcep
tion: "fo:flow" is missing child elements. Required content model: marker* (%blo
ck;)+ (See position 1:-1)>org.apache.fop.apps.FOPException: org.apache.fop.fo.Va
lidationException: "fo:flow" is missing child elements. Required content model:
marker* (%block;)+ (See position 1:-1)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationExcep
tion: "fo:flow" is missing child elements. Required content model: marker* (%blo
ck;)+ (See position 1:-1)
```

Could be me . . . I did not see a release note about any config changes that I needed to make locally.

**Comment by jelovirt** [comment] 2017-08-03 13:14
Could you attach the DITA source files for this?

**Comment by infotexture** [comment] 2017-08-03 21:53
I can't reproduce this. 

I was able to build the docs and samples from `docsrc` via Ant and the `dita` command without errors, so I'm guessing it may be an issue with the source files.

**Comment by jelovirt** [comment] 2017-08-22 14:31
Closing as invalid.

**Closed** 2017-08-22 14:31 UTC
Labels: invalid, needs reproduction
