### ISSUE TITLE
Extension point dita.conductor.html5.param declared but not implemented

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2181] opened 2016-01-06 19:07 UTC
The extension point is in org.dita.html5/plugin.xml but no corresponding extension is found in any build file.

**Comment by jelovirt** [comment] 2016-01-07 18:24
IIRC I added the extension point for uniformity, but forgot to actually implement it. The problem is that the Ant targets that actually generate the topic based HTML output are in the XHTML plugin. In order to support the extension point, we'd need to make copies of the targets from XHTML plugin into HMTL5. This is bad for code duplication. The other option is to modularize the XSLT code into an Ant macro. This would allow using the same Ant code in XHTML and HTML5 plugins.

**Comment by jelovirt** [comment] 2016-01-07 18:25
Since we can't make a change like this in a bug release, the safe choice would be to remove the extension point from 2.2.2 release and implement correctly in 2.3.

**Comment by jelovirt** [comment] 2016-01-20 14:52
We cannot remove the extension point in a bug release. I'll revert the deletion and we just have to keep the extension point without an implementation in 2.2.x. We can then implement it in full in 2.3.

**Comment by jelovirt** [comment] 2016-01-20 19:01
Removed commit 47f162f455a95fd61f5753313a6f15d9310d0b6d

**Comment by jelovirt** [comment] 2016-02-27 15:44
Implemented in 1fb295428bad8d495f4f2424bc7888d2ce03f477 @jelovirt jelovirt committed on 7 Jan

**Closed by jelovirt** 2016-02-27 15:44 UTC
Labels: enhancement, html5, P2
