### ISSUE TITLE
mapref's href with external scope is not resolved correctly

### ISSUE THREAD

**Issue by evaEko** [dita-ot/dita-ot#1900] opened 2015-04-27 12:26 UTC
How to reproduce:
In Windows:
1. Create a ditamap with a mapref with an external scope such as:
```<mapref href="../generic/connectors.ditamap" format="ditamap"/>```
2. Build the ditamap with the dita.bat binary, for example:
>```DITA-OT\bin\dita.bat -f myFormat -i myDitamap.ditamap -o output```

Result:
Fails with error:
8<-----------------
Failed to run pipeline: Failed to create output directory C:..
-------------------->8
The output directory directory is resolved a merged string of a temp directory and the resolved output directory, in my case:   C:\Users\EKO~\AppData\Local\Temp\temp20150427140200179\C:\Users\eko.RSD\doc\src\generic\topics
 
I am able to build the document under Linux with the dita binary just fine.

**Comment by evaEko** [comment] 2015-04-27 12:27
I am on DITA-OT version 2.0

**Comment by jelovirt** [comment] 2015-04-28 03:25
Is the error message exactly that,

> Failed to run pipeline: Failed to create output directory C:..

With three dots in the path, or did you shorten it?

**Comment by evaEko** [comment] 2015-04-28 06:43
Hi jelovirt,
the ... sign just shortens the returned error. So for me it was:

Failed to run pipeline: Failed to create output directory C:\Users\EKO~\AppData\Local\Temp\temp20150427140200179\C:\Users\eko.RSD\doc\src\generic\topics

So the path seems to be one sting with two paths merged. like i said, the same map works fine on my linux machine.
BTW: Thanks for the fantastic work you are doing.
Thanks

**Comment by evaEko** [comment] 2015-04-28 08:04
I found also the following happening on Linux:
If I build xhtml from the book, the references to the out-of-scope topics remain the same as in original map in the index.html: so they dont change to the output path, but remain hrefs to the source dita files.
I must be doing something very wrong.

**Comment by jelovirt** [comment] 2015-04-28 15:24
@eerohele would you be able to help with this? Reproduce in `develop` and perhaps debug a bit, because IIRC you had access to a Windows machine?

**Comment by eerohele** [comment] 2015-04-29 07:43
[Fixtures](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/1900).

Can reproduce with 2.0, can **not** reproduce with `develop`. This is fixed by 8b961e5.

**Comment by jelovirt** [comment] 2015-04-29 14:59
Simply cherry picked from 8b961e5 to hotfix/2.0.2. @eerohele would it be too much to ask for a confirmation that this actually works?

**Comment by eerohele** [comment] 2015-04-29 15:05
Tested `hotfix/2.0.2` — can confirm it fixes the issue.

**Closed** 2015-04-29 15:05 UTC
Labels: bug, P2, platform-dependent, preprocess
