### ISSUE TITLE
PDF transtype: flagging issue when using startflag/alt-text only

### ISSUE THREAD

**Issue by blefort** [dita-ot/dita-ot#1454] opened 2013-02-06 18:30 UTC
Version checked: 1.6.3, 1.7.1

When a ditaval is in use and the ditaval use text only and no image for flagging, the build does not work:

## ditaval
```xml
<prop action="flag" att="audience" val="my-audience">
    <startflag>
        <alt-text>my-audience (</alt-text>
    </startflag>
    <endflag>
        <alt-text>)</alt-text>
    </endflag>
</prop>
```

## error
```
org.xml.sax.SAXParseException; 
systemId: file:/var/www/html/http/hr/DITA-OT1.6.3/temp/temp20130206120144412/stage2.fo; 
lineNumber: 4; columnNumber: 6; 
Content is not allowed in prolog.
```

## Possible reason
When an element has a @class  containing 'map/topicref' and an audience is set, the flagging process will output the alt-text before the fo document starts.

Example of stage2.fo document:
```xml
<?xml version="1.0" encoding="utf-8"?>
 my-audience () my-audience ()  

<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format"
```

## Quick solution
Adding the following line works fine for me, but I am not sure of all implication of it. I add it in case someone need a solution until a better one is found.

File: flagging-preprocess.xsl
```xsl
<xsl:template match="*[contains(@class, ' map/topicref ')]" priority="50" />      
```

## Sample
I will try to generate one as soon as possible

**Comment by robander** [comment] 2016-04-25 19:26
I tried again with 2.2.4 using the DITAVAL segment above, placing `audience="my-audience"` on a `<topicref>`, a `<concept>`, and on `<p>. With the new flagging process, the first of those is ignored, and the later two both result in the flag text in the PDF. There are no build errors.

Marking this as closed / obsolete, as we have not been able to reproduce it since @eerohele tried with 1.7.1.

**Closed by robander** 2016-04-25 19:26 UTC
Labels: bug, invalid, obsolete, P2, pdf
