### ISSUE TITLE
Force unique behavior with keyrefs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4170] opened 2023-04-19 13:16 UTC
Tested with DITA OT 4.0.2.
I have a DITA Map which maps two keys to the same referenced topic:

```xml
<topicref href="step.dita" keys="step_a"/>
<topicref href="step.dita" keys="step_b"/>
<topicref href="target.dita" keys="target"/>
<reltable>
  <relrow>
    <relcell>
      <topicref keyref="step_a"/>
      <topicref keyref="step_b"/>
    </relcell>
    <relcell>
      <topicref keyref="target"/>
    </relcell>
  </relrow>
</reltable>
```

and then the reltable adds references between both keys and the `target` key.
I'm using `fource-unique=true` to publish to HTML5.
As force-unique generates two HTML files `step.html` and `step-2.html` on disk from the original `step.dita`, both these generated HTML files should have a related link to `target.html`. But only the first `step.html` does.

Looking at the console output, the copy-to processing which generates the `step-2.dita` takes place after the keyrefs are resolved so the `step_b` key remains mapped to `step.dita`.
But I'm not sure how this could be fixed.

[test_force-unique.zip](https://github.com/dita-ot/dita-ot/files/11273404/test_force-unique.zip)

**Comment by chrispy-snps** [comment] 2023-04-19 14:49
Using [`ditaot_save_preprocessing.pl`](https://github.com/chrispy-snps/DITA-ditaot-utilities#using-ditaot_save_preprocessingpl), I found the output of the `keyref` and `copy-to` preprocessing stages to be as follows:

![4170_keyref](https://user-images.githubusercontent.com/50950969/233112714-50664e82-66d0-4f15-a987-b674bf91318a.svg)

![4170_copy-to](https://user-images.githubusercontent.com/50950969/233112752-82b0b19b-5943-48d4-bbc2-92c64b4652bc.svg)

I tried `preprocess2` but I ran into #4070.

@raducoravu - in your testcase, if I removed the direction-limiting `@linking` attributes:

```
      <relcolspec type="topic" linking="sourceonly"/>
      <relcolspec type="task" linking="targetonly"/>
```

then "target.html" has a link only to "step.html", but not to "step-2.html". Maybe this is also caused by the ordering of map-level keyref resolution before copy-to processing.

It would be interesting to think of some cases that would break if `keyref` and `copy-to` were swapped. I wonder if an iterative solution would ultimately be needed to handle all cases reliably?

**Comment by raducoravu** [comment] 2023-04-19 14:55
@chrispy-snps thanks for the extra details. It seems there are certain cases when you reach these edge cases which would be made better by switching the order of processing steps. But switching the order might break something else :) I think the keyref module also adds for example copy-to attributes to topics which are in key scopes and need to have different contents in different places.

**Comment by jelovirt** [comment] 2023-08-04 06:32
This looks like duplicate of #4070

**Closed** 2023-08-04 06:32 UTC
Labels: bug, duplicate, preprocess/keyref
