### ISSUE TITLE
abbreviated-form and term dont link to entry in PDF output

### ISSUE THREAD

**Issue by hcw70** [dita-ot/dita-ot#4263] opened 2023-08-11 10:11 UTC
## Actual Behavior
If using a `glossref` in the `glossary.ditamap`, in the PDF output the
glossary entry is rendered as italics, but not as a link to the glossary entry.
This is identical if using a `abbreviated-form` or a `term`

## Expected Behavior
When referencing a glossary entry, it should appear as a link,
so reader can check the definition by a simple click.

## Possible Solution
If using a `topicref` in the `glossary.ditamap`, the link is generated.
However, this seems not to be the correct approach (if trying glossary filtering 
by using https://github.com/dita-community/org.dita-community.glossary.preprocess)

## Steps to Reproduce
bookmap.ditamap:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
<bookmap>
  <booktitle>
    <mainbooktitle>test</mainbooktitle>
  </booktitle>
  <chapter href="chapter.dita"/>
  <backmatter>
    <mapref href="glossary.ditamap"/>
  </backmatter>
</bookmap>
```
chapter.ditamap:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="chapter">
  <title>test</title>
  <body>
    <p>
    This is a abbreviated ref to
    <abbreviated-form keyref="GLS_Test"/>.

    This is a term ref to
    <term keyref="GLS_Test"/>.
    
    </p>
  </body>
</topic>
```
glossary.ditamap:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
  <title>Glossary</title>
  <glossref keys="GLS_Test" href="GLS_Test.dita" print="yes"/>
</map>

```
GLS_Test.dita:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glossentry PUBLIC "-//OASIS//DTD DITA Glossary//EN" "glossary.dtd">
<glossentry id="GLS_Test">
  <glossterm>Test</glossterm>
  <glossdef>This is just a test.</glossdef>
  <glossBody>
    <glossSurfaceForm>Test (T)</glossSurfaceForm>
    <glossAlt>
      <glossAcronym>T</glossAcronym>
    </glossAlt>
  </glossBody>
</glossentry>
```
cmd:
`dita -f pdf -o out  --processing-mode=strict -i bookmap.ditamap     
`

Does not produce links to glossary entry.
Replacing the glossref with topicref in glossary.ditamap renders links.

## Environment

* DITA-OT version: 4.1.1, but also in 3.7.2
* Operating system and version:
  Ubuntu Linux 22.04, java 17 (/usr/lib/jvm/java-17-oracle/bin/java)
* How did you run DITA-OT? `dita` command
* Transformation type: PDF

**Comment by chrispy-snps** [comment] 2023-08-11 11:05
@hcw70 - I think this is a duplicate of not-a-bug issue #4026.

In the Attributes section of [3.14.2.2 <glossref>](https://docs.oasis-open.org/dita/dita/v1.3/os/part2-tech-content/langRef/technicalContent/glossref.html), it says:

    @print
    Specifies whether the topic should be included in a print-specific rendition, such as PDF. On this element the value defaults to "no".Unfortunately the `glossref` element has a default `@print` value of `no`:

And because the glossary is excluded from processing for PDF output, the links are not produced.

This default has caught many people unaware, including you and me. :)  It was probably an unintended side effect in the original OASIS DITA schema specification.

**Comment by hcw70** [comment] 2023-08-14 07:31
But as i shown in the example files above, i have set "print=yes".
So it should show up.

**Comment by hcw70** [comment] 2023-08-14 07:40
Ok, after setting `glossref linking="normal"` or `glossref linking="targetonly"` additional to `print="yes"` it works.
Thanks for the hint. 8->

But poor examples for glossaries all over the places.... 8-<

**Closed** 2023-08-14 07:41 UTC
Labels: bug

**Comment by hcw70** [comment] 2023-08-14 09:30
IMHO using a glossary helps in explaining terms in a central place.
And we want to set up a department-shared glossary git repo with such common terms, so  we dont waste
time in re-describing these terms.

**Comment by chrispy-snps** [comment] 2023-08-14 09:33
@hcw70 - oh I certainly believe in glossaries! I am just not sure that a `glossref` glossary inclusion provides value over a `mapref` glossary inclusion, given that my only experience with `glossref` is that it causes confusion due to its defaults.

**Comment by hcw70** [comment] 2023-08-14 10:17
@chrispy-snps 
I am not sure i understand your comment.

i AM using mapref in my example above 

If i use mapref in my bookmap.ditamap:
```
  <backmatter>
    <glossref href="glossary.ditamap"/>
  </backmatter>
```
processing fails with

`chapter.dita:8:42: [DOTX060W][WARN]: Key 'GLS_Test' was used in an abbreviated-form element, but the key is not associated with a glossary entry. Abbreviated-form should ONLY be used to reference to a glossary entry.
`
...

**Comment by chrispy-snps** [comment] 2023-08-14 10:33
@hcw70 - oops yes. Indeed, you were using `<glossref>` for your glossary term _topic_, not the glossary _map_.

What I was trying to say in my original comment was that the `<glossref>` element seems to cause confusion due to its not-well-known default attribute values, and so I think standard reference elements (`<topicref>` in this case) should be used instead.
