### ISSUE TITLE
preprocess2 with html5 transtype does not copy files to correct location

### ISSUE THREAD

**Issue by jomjohn** [dita-ot/dita-ot#3966] opened 2022-07-13 05:00 UTC
## Expected Behavior

The pdf should be copied to the output dir using the following keydef
```
<keydef keys="testPdf" href="attachments/Test_PDF.pdf" format="pdf" print="no"> 
        <topicmeta><navtitle>TEST PDF</navtitle><linktext>TEST PDF</linktext></topicmeta>
 </keydef>
```

As a general question, is preprocess2 appropriate to be using with html5 output or is it too early to expect to use it in a production environment?

## Actual Behavior

Since the ant properties are not yet set, the pdf is saved to `/opt/dita-ot/DITA-OT/src/main/${_dita.map.output.dir}/${uplevels}`

The following is the difference in the dita-ot log when using preprocess vs preprocess2:

preprocess
```
copy-html:
     [copy] Copying 1 file to /opt/dita-ot/out/preprocess2_test
```

preprocess2
```
copy-html:
     [copy] Copying 1 file to /opt/dita-ot/DITA-OT/src/main/${_dita.map.output.dir}/${uplevels}
```

Both complete log files are provided in the zip file (preprocess2_test.zip)

## Possible Solution

In org.dita.base/build_preprocess2.xml the preprocess2 target defines the properties **_dita.map.output.dir** and **uplevels** but by this time it is too late for them to be used in the **copy-files2** target. 

For reference:

```
  <target name="preprocess2" description="Preprocess" depends="preprocess2.init,ditaval-merge,preprocess2.maps,
     preprocess2.topics,map-clean-map,clean-preprocess,copy-files2">
    <dirname property="_dita.map.output.dir" file="${dita.output.dir}/${user.input.file}"/>
    <dirname property="_dita.map.temp.dir" file="${dita.temp.dir}/${user.input.file}"/>
    <property name="uplevels" value=""/>
    <property name="dita.map.output.dir" location="${_dita.map.output.dir}/${uplevels}"/>
  </target>
```

## Steps to Reproduce

Source Files to reproduce:

[preprocess2_test.zip](https://github.com/dita-ot/dita-ot/files/9099007/preprocess2_test.zip)

1. In plugins/org.dita.html5/build_dita2html5.xml change "preprocess" target to "preprocess2" in dita2html5
2. With the attached sample set of files run command similar to `dita -i "/opt/dita-ot/data/preprocess2_test/pp2.ditamap" -o /opt/dita-ot/out/preprocess2_test -f html5 -v -t /opt/dita-ot/temp`
3. You will notice the PDF is copied to the wrong place.
4. Change preprocess2 back to preprocess to see the difference.

## Copy of the error message, log file or stack trace

Included in preprocess2_test.zip

## Environment

* DITA-OT version: 3.7.2
* Operating system and version: Linux
  _(Linux, macOS, Windows)_
* How did you run DITA-OT? dita
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
* Transformation type: html5
  _(HTML5, PDF, custom, etc.)_

**Comment by raducoravu** [comment] 2022-07-13 05:23
Possible duplicate of #3242

**Comment by jelovirt** [comment] 2023-03-05 13:36
@jomjohn 

> The pdf should be copied to the output dir using the following keydef
>
> `<keydef keys="testPdf" href="attachments/Test_PDF.pdf" format="pdf" print="no">`

What catches my attentention is that `print="no"` attribute. The `keydef` should _not_ be used for print media output and you're generating PDF. Doesn't this mean the source explicitly says "when producting PDF, do *not* use this key"?

**Comment by jomjohn** [comment] 2023-03-07 00:59
Hi @jelovirt ,

I probably shouldn't have had the **print="no"** in my example. In this case it does not hold significance. 

I copied it from my source content that we generate both pdf and html. In that context I have the following two keydefs:
```
<keydef keys="testPdf" href="attachments/Test_PDF.pdf" format="pdf" print="no"> 
        <topicmeta><navtitle>TEST PDF</navtitle><linktext>TEST PDF</linktext></topicmeta>
 </keydef>
<keydef keys="testPdf" href="https://fqdn.com/Test_PDF.pdf" format="pdf" print="yes"> 
        <topicmeta><navtitle>TEST PDF</navtitle><linktext>TEST PDF</linktext></topicmeta>
 </keydef>
```
In the pdf, I do not rely on a local copy of the pdf.

**Closed** 2023-04-29 11:26 UTC
Labels: bug
