### ISSUE TITLE
Missing namespace for default attributes from xsd

### ISSUE THREAD

**Issue by PStellmann** [dita-ot/dita-ot#2532] opened 2016-11-29 07:33 UTC
I have a custom preprocess step that evaluates attributes within a specific namesapce. When these attributes are set as defaults by an XSD the namespace is missing. (With RNG it is working fine.)

I attached a minimized sample where I added the attribute @cba:prefix to the title element with a default value. After running DITA-OT (2.4) I find the attribute added to the dita file in the temp folder - but without namespace.
[title-prefix.zip](https://github.com/dita-ot/dita-ot/files/618331/title-prefix.zip)

(I'd guess this could be fixed with a xxx.setNamespaceAware(true); at the right place. But so far I didn't even manage to compile OT...)

**Comment by PStellmann** [comment] 2016-11-30 06:32
I just noticed that this behavior also occurs without any custom schema: For a codeblock element the default attribute xml:space is only added as space="preserve" without the "xml:" namespace prefix.

**Comment by PStellmann** [comment] 2016-12-09 11:51
Just as an update: This seems to be an issue with the Xerces parser. I've sent a message to the mailing list:
http://mail-archives.apache.org/mod_mbox/xerces-j-users/201612.mbox/browser

**Comment by raducoravu** [comment] 2016-12-09 12:35
I can confirm that when a Xerces SAX parser parses an XML document with an associated XML Schema which specifies namespaced attributes, the reported attributes on the "startElement" method have the proper namespace but their qualified name is the local name, not the prefixed name.
Actually one of my colleagues is just working on a Xerces patch for this for Oxygen because the latest Saxon 9 processor also has problems with this Xerces bug.

**Comment by PStellmann** [comment] 2016-12-09 14:23
I got a reply on the Xerces mailing list:
> Not user friendly, but working as designed. No prefix is defined for attribute default values (see schema spec here [1]).
>
>Some of the more recent XML serialization APIs (LSSerializer / XMLStreamWriter) are more namespace-aware and have the ability to fix up namespaces during serialization.
>
>Thanks.
>
>[1] https://www.w3.org/TR/xmlschema-1/#sic-attrDefault
>
>Michael Glavassevich

So no fix to expected from there.

@raducoravu: Will your patch be applicable to DITA-OT as well? (My DITA customizations highly depend on default attributes. And I decided - as Eliot recommended - to put them in a dedicated namespace so they are easily recognized as custom extensions...)

**Comment by raducoravu** [comment] 2016-12-12 14:13
> Will your patch be applicable to DITA-OT as well?

When running the DITA OT publishing from Oxygen the patch will probably work.
When running it as an external process started for example from a command line you may need to create a custom JAR library containing the patched Xerces class and place that in the classpath before the Xerces library is loaded.

**Comment by raducoravu** [comment] 2016-12-12 14:30
Also, what version of Saxon 9 are you using? We noticed this problem in the latest Saxon 9.7.x version...

**Comment by PStellmann** [comment] 2016-12-14 05:20
I'm only using Saxon 9.6 (as embedded into oXygen 18.0) and 9.1 (as embedded in DITA-OT 2.4).

**Comment by raducoravu** [comment] 2016-12-14 13:05
I reproduced the problem with your samples.
So it seems that the serializer (TransformerHandler) in Saxon 9.6 and older (which is used in the DebugAndFilterModule) indeed emits in the serialized XML the default attribute name without a generated prefix.
The next Saxon 9.7 will probably have a fix for this, as Michael agreed to fix the issue I opened:
https://saxonica.plan.io/issues/3068

I tested and the patch we made on our side in the Xerces parser also fixes the problem. I will send you the patch via email.
But the issue cannot be fixed from the DITA OT code, as long as the DITA OT does not have its own serialization of sax events, instead of using Saxon.

**Closed by raducoravu** 2016-12-14 13:05 UTC
Labels: bug, P1
