### ISSUE TITLE
URIResolver throws an exception when resolving custom header files

### ISSUE THREAD

**Issue by Jon-Hill-i2** [dita-ot/dita-ot#4218] opened 2023-06-30 15:22 UTC
## Expected Behavior
Custom headers specified using the `args.hdr` parameter should be applied to HTML output successfully.

## Actual Behavior
The XSLT processor generates the following exception during processing of every source file:

```
[xslt] Failed to transform document: Failed to transform document: Exception thrown by URIResolver resolving `file:/C:\DITA-OT41\docsrc\resources\header.xml` against `file:/C:/Users/WDAGUtilityAccount/AppData/Local/Temp/temp20230630161007977/html/parameters/parameters-base-html.dita'
```

As you can see, this is happening even during processing of the DITA-OT documentation source. The problem is new in DITA-OT 4.1; it does not arise under 4.0.

## Possible Solution
Unknown.

## Steps to Reproduce

1. Start a clean Windows 10 VM
2. Install a Java 17 JRE
3. Download DITA-OT 4.1 and install it at `C:\DITA-OT41`
4. At a command prompt, navigate to `C:\DITA-OT41\docsrc\samples\project-files`
5. Execute `C:\DITA-OT41\bin\dita --project=html.xml`

## Copy of the error message, log file or stack trace
See "Actual Behavior".

## Environment

* DITA-OT version: 4.1
* Operating system and version: Windows 10 Enterprise version 22H2
* How did you run DITA-OT? `dita` command
* Transformation type: HTML

**Comment by Jon-Hill-i2** [comment] 2023-07-01 09:27
Further information: I just tried the same procedure on MacOS Ventura. I _don't_ see the exceptions from URLResolver on that platform. It seems to be specific to Windows.

**Comment by chrispy-snps** [comment] 2023-07-01 17:09
I confirmed the issue in Windows 11 using DITA-OT 4.1 with Java 17/18/19/20. An output directory is still created, but all the HTML files are zero bytes. If I fall back to DITA-OT 4.0.2, the issue no longer occurs.

**Comment by raducoravu** [comment] 2023-07-03 08:59
The stack trace of the error is this one:

                 [xslt] java.lang.IllegalArgumentException: Illegal character in path at index 8: file:/D:\git-projects\dita-ot\src\main\docsrc\resources\header.xml                  [xslt]     at java.base/java.net.URI.create(URI.java:906)                  [xslt]     at java.base/java.net.URI.resolve(URI.java:1089)                  [xslt]     at org.xmlresolver.Resolver.resolve(Resolver.java:127)                  [xslt]     at org.dita.dost.util.ChainedURIResolver.resolve(ChainedURIResolver.java:36)                  [xslt]     at net.sf.saxon.lib.ResourceResolverWrappingURIResolver.resolve(ResourceResolverWrappingURIResolver.java:58)

**Comment by raducoravu** [comment] 2023-07-03 09:10
A quick fix for this would be to probably go in the "org.dita.dost.util.ChainedURIResolver.resolve(String, String)" method and do this:

	  if(href != null) {
		  href = href.replace('\\', '/');
	  }

but probably a fix would need to be done also in the place where this parameter from the DITA OT project file is converted to an URL:

      <param name="args.hdr" href="../../resources/header.xml"/>

**Comment by raducoravu** [comment] 2023-07-04 02:33
@chrispy-snps right at the beginning of the method:

     public Source resolve(String href, String base) throws TransformerException {
	  if(href != null) {
		  href = href.replace('\\', '/');
	  }
	  if(base != null) {
		  base = href.replace('\\', '/');
	  }
	  final Source res = first.resolve(href, base);
	  if (res != null) {
		  return res;
	  }
	  return second.resolve(href, base);
     }

**Comment by chrispy-snps** [comment] 2023-07-04 13:04
Using the following small testcase:

[4218_small.zip](https://github.com/dita-ot/dita-ot/files/11949539/4218_small.zip)

the URIResolver message occurs in a baseline DITA-OT:

```
C:\...\4218>dita-ot-ORIG\build\tmp\dist\bin\dita --project project.xml
     [xslt] Exception thrown by URIResolver resolving `file:/C:\...\4218\header.xml` against `file:/C:/.../temp20230704085748271/html/topic.dita'
     [xslt] Failed to transform document: Failed to transform document: Exception thrown by URIResolver resolving `file:/C:\...\4218\header.xml` against `file:/C:/.../temp20230704085748271/html/topic.dita'

C:\...\4218>
```

and it is resolved with @raducoravu's suggested change:

```
C:\...\4218>dita-ot-RADU\build\tmp\dist\bin\dita --project project.xml

C:\...\4218>
```

There are some other behaviors beyond the URIResolver message that I am looking into.

**Comment by jelovirt** [comment] 2023-07-06 17:48
Debugging this by reading code, it seems that the chain is

1. The `args.hdr` in a project file is relative URI.
2. DITA-OT CLI reads the project file, resolves the URI into an absolute system path.
3. The system path is passed from Ant property `${args.hdr}` into XSLT parameter `HDR`.
4. XSLT has code to recognize whether `$HDR` is a file URI and will prefix with `file:/` if needed.

The problem is that step 4. doesn't convert Windows separator `\` into URI separator `/`.

IMO the best fix would be to convert `${args.hdr}` into a URI in the HTML5 Ant buildscript.

**Comment by jelovirt** [comment] 2023-07-06 18:04
Because we already have a check that `args.hdr` is an absolute path to a file that exists (error code `DOTA008E`), we should be safe to assume that we can use `<makeurl>` Ant task to convert the value to a URL and then pass that to XSLT.

**Comment by jelovirt** [comment] 2023-07-06 18:46
Is someone on Windows able to test with #4226.

**Comment by raducoravu** [comment] 2023-07-07 04:42
I opened an issue also on the XML resolver's issues list: https://github.com/xmlresolver/xmlresolver/issues/149

**Closed** 2023-07-07 06:21 UTC
Labels: bug, platform/windows

**Comment by raducoravu** [comment] 2023-07-07 06:27
@jelovirt should we also attempt to catch an illegal argument exception in the ChainedURIResolver and ignore it to avoiding to break the processing? There may be people encountering such problems from custom DITA OT plugins.

**Comment by Gurushesh-Metapercept** [comment] 2023-08-17 07:16
while using latest bootstrap with ditaOT 3.6.1 encountered following error when I use **nav-toc = collapsible** if I remove or use **list-group-partial** or any other menu style then error does not appear and it runs successfully

[xslt] Type error evaluating ($element/ancestor-or-self::element()[fn:contains(...)][1]) in xsl:variable/@select on line 51 column 124 of functions.xsl:
     [xslt]   XTTE0570: An empty sequence is not allowed as the value of variable $topic
     [xslt] at function dita-ot:generate-stable-id on line 48 of functions.xsl:
     [xslt]      invoked by function call at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#630
     [xslt]   In template rule with match="*[fn:contains(...)][xs:string(@toc) ne "no"][xs:string(@processing-role) ne "resource-only"]" on line 609 of nav.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#329
     [xslt]   In template rule with match="*" on line 327 of nav.xsl
     [xslt]      invoked by built-in template rule (text-only)
     [xslt]   In template rule with match="*" on line 252 of nav.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#239
     [xslt] at template sidebar-content on line 164 of nav.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#159
     [xslt] at template offcanvas-sidebar on line 129 of nav.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#259
     [xslt]   In template rule with match="*" on line 252 of nav.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#2290
     [xslt] at template gen-user-sidetoc on line 2289 of topic.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/xsl/html5-bootstrap.xsl#119
     [xslt]   In template rule with match="*" on line 93 of html5-bootstrap.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#2476
     [xslt] at template chapterBody on line 2475 of topic.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/topic.xsl#61
     [xslt] at template chapter-setup on line 49 of topic.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#206
     [xslt]   In template rule with match="*" on line 205 of topic.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#196
     [xslt]   In template rule with match="*[fn:contains(...)]" on line 193 of topic.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/dita2html5.xsl#22
     [xslt]   In template rule with match="/" on line 21 of dita2html5.xsl
     [xslt] Failed to transform document: Failed to transform document: An empty sequence is not allowed as the value of variable $topic
     [xslt] Type error evaluating ($element/ancestor-or-self::element()[fn:contains(...)][1]) in xsl:variable/@select on line 51 column 124 of functions.xsl:
     [xslt]   XTTE0570: An empty sequence is not allowed as the value of variable $topic

**Comment by Gurushesh-Metapercept** [comment] 2023-08-17 07:17
while using latest bootstrap with ditaOT 3.6.1 encountered following error when I use **nav-toc = collapsible** if I remove or use **list-group-partial** or any other menu style then error does not appear and it runs successfully

[xslt] Type error evaluating ($element/ancestor-or-self::element()[fn:contains(...)][1]) in xsl:variable/@select on line 51 column 124 of functions.xsl:
     [xslt]   XTTE0570: An empty sequence is not allowed as the value of variable $topic
     [xslt] at function dita-ot:generate-stable-id on line 48 of functions.xsl:
     [xslt]      invoked by function call at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#630
     [xslt]   In template rule with match="*[fn:contains(...)][xs:string(@toc) ne "no"][xs:string(@processing-role) ne "resource-only"]" on line 609 of nav.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#329
     [xslt]   In template rule with match="*" on line 327 of nav.xsl
     [xslt]      invoked by built-in template rule (text-only)
     [xslt]   In template rule with match="*" on line 252 of nav.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#239
     [xslt] at template sidebar-content on line 164 of nav.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#159
     [xslt] at template offcanvas-sidebar on line 129 of nav.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/nav.xsl#259
     [xslt]   In template rule with match="*" on line 252 of nav.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#2290
     [xslt] at template gen-user-sidetoc on line 2289 of topic.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/xsl/html5-bootstrap.xsl#119
     [xslt]   In template rule with match="*" on line 93 of html5-bootstrap.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#2476
     [xslt] at template chapterBody on line 2475 of topic.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/net.infotexture.dita-bootstrap/Customization/xsl/topic.xsl#61
     [xslt] at template chapter-setup on line 49 of topic.xsl:
     [xslt]      invoked by xsl:call-template at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#206
     [xslt]   In template rule with match="*" on line 205 of topic.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/topic.xsl#196
     [xslt]   In template rule with match="*[fn:contains(...)]" on line 193 of topic.xsl
     [xslt]      invoked by xsl:apply-templates at file:/C:/Users/Admin/Desktop/DITAOT/dita-ot-3.6.1/plugins/org.dita.html5/xsl/dita2html5.xsl#22
     [xslt]   In template rule with match="/" on line 21 of dita2html5.xsl
     [xslt] Failed to transform document: Failed to transform document: An empty sequence is not allowed as the value of variable $topic
     [xslt] Type error evaluating ($element/ancestor-or-self::element()[fn:contains(...)][1]) in xsl:variable/@select on line 51 column 124 of functions.xsl:
     [xslt]   XTTE0570: An empty sequence is not allowed as the value of variable $topic

**Comment by raducoravu** [comment] 2023-08-22 09:32
@Gurushesh-Metapercept your comment does not seem related to this current issue. DITA OT 3.6 did not contain the library which causes the current problem. Maybe you could remove your comment from this issue.

**Comment by raducoravu** [comment] 2023-08-22 09:33
@jelovirt I see Norm Walsh also decided to catch this runtime exception on the resolver side: https://github.com/xmlresolver/xmlresolver/issues/149
