### ISSUE TITLE
Image with keyref not included in output

### ISSUE THREAD

**Issue by jlowther** [dita-ot/dita-ot#2917] opened 2018-03-16 21:01 UTC
## Expected Behavior
I'm trying to build XHTML output using DITA-OT 3.0.2.

My map contains the following key definition:

     <keydef keys="AddButton" href="images/AddButton.png" format="png"/>

I expect AddButton.png to be copied to the output folder. 

## Actual Behavior
The image is not copied to the output folder and the HTML page displays a broken link. 

## Steps to Reproduce

1. Create a bookmap and insert the keydef in the backmatter element:
<backmatter>
  <keydef keys="AddButton" href="sfos/images/AddButton.png" format="png" />
 </backmatter>
2. Build output using DITA-OT 3.0.2.
3.View output folder. The image file is not present. 

## Copy of the error message, log file or stack trace
No error message present in output log.

## Environment
Windows 10

* DITA-OT version: 3.0.2
* Operating system and version:
Windows 10
* How did you run DITA-OT?
Ant, dita command
* Transformation type:
XHTML

**Comment by raducoravu** [comment] 2018-03-19 08:41
I can reproduce the problem on my side with DITA OT 3.0.2, I'm attaching a sample project.
[imageKeyref.zip](https://github.com/dita-ot/dita-ot/files/1824254/imageKeyref.zip)

Somehow for direct image references (via @href) the "image.list" file in the temp files folder is properly populated. Also the .job.xml uses "format='image'" when referring to the image. 
For indirect images the "image.list" does not contain the image references.
But I'm not sure where the problem is.

**Comment by jelovirt** [comment] 2018-03-20 16:25
I think the cause is that `copy-image` task is ran in the middle of `preprocess`, and at that point the image format is just the file extension, `png`. When image metadata processing is ran and we collect all image references, the format is changed to `image`.

The fix to this would be to move the image copy to the end of preprocessing or beginning of HTML tasks. Issue #1988 is basically about implementing this.

I'm not sure what would be the best fix for this in 3.0.x because we can't really move the responsibility of copying to HTML in a bug fix release. @robander how do you feel about just moving `copy-files` to the end of `preprocess` to remedy this?

**Comment by jelovirt** [comment] 2018-03-20 19:39
Tested this and it's not enough to just move `copy-files` to end of `preprocess`. Copy should take place after `xhtml.image-metadata` and that's part of XHTML tasks. An alternative workaround would be to replace

```xml
<copy todir="${copy-image.todir}" failonerror="false">
  <ditafileset format="image" />
</copy>
```

with

```xml
<copy todir="${copy-image.todir}" failonerror="false">
  <ditafileset format="image" />
  <ditafileset format="jpeg" />
  <ditafileset format="jpg" />
  <ditafileset format="png" />
  <ditafileset format="gif" />
  ...
</copy>
```

This really would be a workaround and something that should be fixed by having transtype be responsible for image copy.

**Comment by raducoravu** [comment] 2018-03-21 06:34
Problem is that there may be more image extensions like SVG, maybe if you create a ditafileset of format="image" it should also look in the "supported_image_extensions" values from the "plugin.properties" and copy also those resources. But ideally the copy image task should not care about image extensions at all, just as it is now, because if you have an image with a keyref, that reference it definitely an image.

**Comment by jelovirt** [comment] 2018-03-21 06:36
Exactly. We may have to revert back to using `supported_image_extensions`, maybe as a set of aliases for `image`. This would be a change only in the Java code and the Ant configuration could remain the same. Good idea. 👍

**Comment by jelovirt** [comment] 2018-03-21 07:15
@raducoravu are you able to review https://github.com/dita-ot/dita-ot/pull/2921?

**Comment by raducoravu** [comment] 2018-03-21 07:17
@jelovirt Do you want only review or also merging of the PR?

**Comment by jelovirt** [comment] 2018-03-21 07:18
@raducoravu if it passes your review, you can merge the PR.

**Closed** 2018-03-21 07:51 UTC
Labels: P1, bug, preprocess, preprocess/keyref

**Comment by ritti** [comment] 2018-03-21 07:54
Is it possible that this issue that "The image is not copied to the output folder" can also have to do with
https://github.com/dita-ot/dita-ot/issues/2899 ?

**Comment by jelovirt** [comment] 2018-03-21 07:55
@ritti are you able to test by building DITA-OT 3.0.4 from Git and testing?

**Comment by ritti** [comment] 2018-03-21 08:42
Unfortunately not. May be you can provide the changed jar file that I replace in 3.0.3 for testing?

**Comment by jelovirt** [comment] 2018-03-21 08:44
Unfortunately not due to lack of resources. It will take less time to test this ourselves than prepare a changed JAR.
