### ISSUE TITLE
@keyref isn't resolved when contained in @conref

### ISSUE THREAD

**Issue by tomorales** [dita-ot/dita-ot#3546] opened 2020-07-14 05:18 UTC
Using DITA-OT versions 3.5 through 3.5.2, @keyrefs contained within @conrefs aren't resolved.

In the attached sample, there are two keys defined: a product name (product-name) and a web site (web-site). The myproduct.dita topic directly references the product-name key and conrefs a <ph> element which references the product-name key.

Similarly, the mysite.dita topic directly references the web-site key and conrefs a <ph> element which references the web-site key.

## Expected Behavior

I expect both pairs of @keyref to resolve to the corresponding key.

## Actual Behavior

Only the direct references to the keys are resolved. The references to the keys from the content which is pulled in via conref are not resolved.

## Possible Solution

This works fine in DITA-OT 3.4.1.

## Steps to Reproduce

The file test.txt in the attached zip is how I run the dita command.

Examining the contents of the temp directory shows that the key references through the conref <ph> elements aren't being resolved, so this is definitely a preprocess bug.

[testconrefkeyref.zip](https://github.com/dita-ot/dita-ot/files/4916653/testconrefkeyref.zip)

**Comment by raducoravu** [comment] 2020-07-14 05:25
Do you get the same problem if in the DITA Map you refer to the common.dita as resource-only?

     <topicref href="topics/common.dita" processing-role="resource-only"/>

**Comment by tomorales** [comment] 2020-07-14 05:31
Adding common.dita to the map with @processing-role="resource-only" yields the correct and expected behavior.

**Comment by tomorales** [comment] 2021-03-25 18:30
Having to add each conref to the map with processing-role set to resource-only just to have key resolution work for keyrefs within conrefs, though, is not an ideal workaround. Particularly when the expected behavior worked in DITA-OT 3.4.1 and earlier.

My testcase still fails in DITA-OT 3.6.1.

**Comment by ToshihikoMakita** [comment] 2021-03-26 13:53
One of my user reported me the same problem. Based on their report, it worked in DITA-OT 3.1.3 but it does not work in DITA-OT 3.5.4. I also confirmed that it does not work in newest DITA-OT 3.6.1. Is it right authoring to include `@keyref` elements that is used as `conref` target? If it satisfies DITA authoring rule, are there any fixes available in the feature?

**Comment by ToshihikoMakita** [comment] 2021-03-26 14:01
In my case, adding conref target topic in the main map as `@processing-role="resource-only"` does not solve this problem. (`keyref` was not resolved at all.)

**Comment by raducoravu** [comment] 2021-03-29 09:15
@ToshihikoMakita maybe your case is different than the original case which is solved by adding @processing-role="resource-only". When you have the time maybe you can attach a small DITA project exemplifying the problem.
In my opinion the cause of the original report is the fact that the default PDF processing uses the "preprocess2" stage which processes only topics referenced directly in the maps and submaps.

**Comment by raducoravu** [comment] 2021-03-29 09:28
Looking closer at the original posted project, no matter if "preprocess" or "preprocess2" is used, the "keyref" stage used to resolve all keyrefs goes only over the topics referenced directly or indirectly in the DITA Map. In very old versions of the DITA OT (https://github.com/dita-ot/dita-ot/issues/2420#issuecomment-227777673) the conrefs were expanded before keyrefs and this situation probably worked then.

**Comment by raducoravu** [comment] 2021-03-31 11:01
I think the cause of this issue was added in this commit by @jelovirt : https://github.com/dita-ot/dita-ot/commit/cf7d7be75f9167dba35259e187e606fbdfd5acc4
In "org.dita.dost.module.KeyrefModule.execute(AbstractPipelineInput)" a collection with all resources having keyrefs is gathered by "Collection<FileInfo> fis" but the collection is not used for anything, the processing relies further on navigating from the main DITA Maps downwards and resolving keyrefs only in the topics which are directly or indirectly referenced in the DITA map. Which makes sense, it's faster to process keyrefs only in the topics which are referenced in the DITA Maps.
But in our case the topic which has a keyref is not referenced in the DITA Map, but content from it is used using "conref" (and not conkeyref) from another topic. And conrefs are resolved later in the publishing process meaning the keyref in this particular topic containing reusable content will never get expanded.
As I mentioned further up in the issue comments, referencing the topic in the DITA Map as a resource-only topic makes the keyref expansion work again inside it.

**Comment by ToshihikoMakita** [comment] 2021-03-31 14:16
@raducoravu Thank you for your deep insight about this. I could not still reproduce this phenomenon with minimum ditamap and topics. I will attach examples when I have finished examining user data.

**Comment by arronvarga** [comment] 2021-04-02 00:29
I am having the same issue and been able to replicate issue in DITA-OT 3.6.1.

Adding the conref topic as a resource-ony to the publication map resovles the issue but is not an ideal solution.

Just wondering if any one has plugin or add-on solution to use until this is resolved within the DITA-OT code.

**Comment by tomorales** [comment] 2021-04-02 01:49
Not only is the workaround impractical, there is no warning/error indicating a keyref within a conref that is not in the map hierarchy won't get resolved. This behavior effectively shuts down our ability to even consider anything later than DITA-OT 3.4.1.

**Comment by raducoravu** [comment] 2021-04-13 09:51
I included a patch for this situation in the DITA OT bundled with the latest Oxygen 23.1 from our web site.

**Comment by ToshihikoMakita** [comment] 2021-04-14 14:08
> I included a patch for this situation in the DITA OT bundled with the latest Oxygen 23.1 from our web site.

Have you also update oxygen-publishing-engine-3.x?

**Comment by raducoravu** [comment] 2021-04-14 14:15
@ToshihikoMakita yes, although the fix is not listed here:
https://www.oxygenxml.com/publishing_engine/build_history.html#2021040717
it should be actually incorporated, it is just a problem of us forgetting to list it on our minor bug fix release changes page.

**Comment by ToshihikoMakita** [comment] 2021-04-14 14:36
@raducoravu unfortunately, trying to build with oxygen-publishing-engine-3.x still outputs the following log and @keyref (in @conref target) are not resolved.

     [keyref] file:/D:/My_Documents/XML2021/support/2021-04-14-acme.com/sample.ditamap/ACMEPay_Arm_MIFARE_collection.dita:7:97: [DOTJ047I][INFO] Unable to find key definition for key reference "RPN2" in root scope. The href attribute may be used as fallback if it exists
     [keyref] file:/D:/My_Documents/XML2021/support/2021-04-14-acme.com/sample.ditamap/ACMEPay_Arm_MIFARE_collection.dita:8:94: [DOTJ047I][INFO] Unable to find key definition for key reference "RPN2" in root scope. The href attribute may be used as fallback if it exists
     [keyref] file:/D:/My_Documents/XML2021/support/2021-04-14-acme.com/sample.ditamap/ACMEPay_Arm_MIFARE_collection.dita:8:117: [DOTJ047I][INFO] Unable to find key definition for key reference "RPN3" in root scope. The href attribute may be used as fallback if it exists
     [keyref] file:/D:/My_Documents/XML2021/support/2021-04-14-acme.com/sample.ditamap/ACMEPay_Arm_MIFARE_collection.dita:8:143: [DOTJ047I][INFO] Unable to find key definition for key reference "RPN4" in root scope. The href attribute may be used as fallback if it exists
     [keyref] file:/D:/My_Documents/XML2021/support/2021-04-14-acme.com/sample.ditamap/ACMEPay_Arm_MIFARE_collection.dita:10:75: [DOTJ047I][INFO] Unable to find key definition for key reference "Platform" in root scope. The href attribute may be used as fallback if it exists

May be the input DITA document has serious problem in it and I still can't find what it is.

**Comment by raducoravu** [comment] 2021-04-14 14:39
Right, as the original workaround "@processing-role="resource-only"" did not work for you, there is probably some other DITA OT bug influencing your problem or as you say a problem in the DITA project.

**Comment by ToshihikoMakita** [comment] 2021-04-20 04:36
Last day I received the DITA-OT difficulty report from existing Oxygen user. They use @keyref for xref that exits imagemap. The situation is as follows:

1. In Oxygen 22.1 (bundle DITA-OT 3.4.1), it works fine. @keyref is resolved.
2. In Oxygen 23.1 (bundle DITA-OT 3.6 build-id 2021030206 ), the keyref is not resolved. DITA-OT displays the error message:
   [DOTX044E][ERROR]: The area element in an image map does not specify a link target. Please add an xref element with a link target to the area element.
3. In Oxygen 23.1 (bundle DITA-OT 3.6 build-id 2021040908), it works fine! @keyref is resolved.

Probably the patch from @raducoravu may works. However I am afraid that this problem will affect not a few DITA-OT customers because:

- They are moving from old DITA-OT to version 3.5 or after to use DITA 1.3 functionality
- I hear that some CCMS users are upgrading DITA-OT in accordance with CCMS version-up

How this problem discussed in DITA-OT development member?

**Comment by raducoravu** [comment] 2021-04-20 05:18
@ToshihikoMakita the next DITA OT meetup is on Thu, May 6, 2021 5:00 PM - 6:00 PM (EEST - eastern european time zone). These meetups are free to join, if you want I can send you the meeting invitation or if not I can try to write the issue down and have it discussed then.

**Comment by ToshihikoMakita** [comment] 2021-04-20 23:54
@raducoravu I think you are the most qualified person to report this issue to DITA-OT meetup. Please attend the meetup and describe to the DITA-OT development team member.

**Comment by ToshihikoMakita** [comment] 2021-05-10 21:48
@raducoravu Are there any updates about this issue? One of my user is facing this problem and they are considering following:
1. Rollback DITA-OT from 3.5.4 to 3.1.3.
2. Or completely change the authoring strategy not to use `@keyref` in the `@conref` target.
The latter is big paradigm change in authoring and they cannot do it in the sort time. However if this problem concerns to DITA-OT "preprocess" architecture that processing `key` first or `conref` first, there may be no method to balance both. Please give me your opinion.

**Comment by ToshihikoMakita** [comment] 2021-05-11 08:37
@raducoravu Thank you for your update. I will try the proposed method once again.

**Comment by ToshihikoMakita** [comment] 2021-05-12 03:57
@raducoravu I have revised the offered data again and finally I could get the expected `@keyref` result. Thank you for your co-operation.

**Comment by pwright73** [comment] 2021-09-10 19:17
Is there any progress on the reported issue?

**Comment by drmacro** [comment] 2021-09-10 22:30
While I think it is best (and, if I had my way, mandatory) practice to include all dependencies needed to process the map's resources in the map (i.e., using resource-only topicrefs to refer to any topics used only as conref targets, keydefs for external resources, images, etc.), the 1.3 spec does suggest that it should be possible to resolve keyrefs in conreffed content even when the target of the content reference is not itself in a map context.

This is because the spec requires key references within referenced content to be resolved in the context of the **referencing** element.

Thus, if the topic making the content reference is used directly via a topicref (and not, for example, via a direct URI reference from an xref in another topic) then there is a map context in which the keyref in the referenced content can (and must) be resolved.

Given that analysis then I think I must reverse my position and agree with the original submitter that the current (as of 3.6.1) behavior is not correct.

Note that the intent of the rule in DITA 1.3 is that when you make a content reference to content that itself has a key reference, that the resolved result will reflect the key space of the referencing topic. This rule ensures that re-use is sensible and controllable in the face of key scopes.

**Comment by drmacro** [comment] 2021-09-10 22:32
All that said, given that there is a simple workaround that reflects best practice, I would not give this issue very high priority.

However, we should verify that resolution of keyrefs in conreffed content does conform to the rules for resolution relative to the key space context of the referencing element--if that is not behaving correctly then it needs to be addressed as quickly as possible, because there's no easy workaround for incorrect behavior in that case.

**Comment by raducoravu** [comment] 2021-10-20 06:16
@mattmenn we also fixed this problem on our side in the DITA OT bundled with Oxygen 23.1 and 24. Ar the same time once you start using keys and keyrefs you may want to move towards using conkeyrefs anyway instead of conrefs for consistency.

**Comment by shaneataylor** [comment] 2022-03-08 15:47
From this thread I get the idea that there's no appetite to fix this issue. I'm not sure how to do so myself.

However, this can still result in unresolved conrefs and links. At least the links can be made to warn users in the logs—the conref failures are entirely silent.

Would the group be receptive to adding a postprocessing step that scans all the temp maps & topics for the following patterns and logs warnings?
* xrefs or links with a @keyref but no @href
* other elements with a @keyref but no content

This is something I'll likely implement for my team, and it would at least warn users about these two scenarios that might often be attributable to this issue.

**Comment by pkowaluk** [comment] 2022-03-23 16:50
Is there some way this could be fixed in an upcoming release in DITA OT? I know there's a workaround, but we have a lot of content that's impacted and it would be great if we could fix our issue by upgrading.

**Comment by raducoravu** [comment] 2022-03-24 05:52
@jelovirt what's your opinion on my proposed code fix and on this issue in general?

**Comment by mgilster** [comment] 2022-03-25 01:29
+1 on the request to fix in an upcoming release. We have a lot of conref content that is potentially impacted, and sometimes need to publish updates for older content, so it would be a lot of effort to add all conref targets to a resource-only map in all of our release branches. It's blocking us from updating the OT. Incorporating the fix from @raducoravu or another solution that doesn't require updating all our maps would help a lot. Thanks for everything, regardless!

**Comment by docdeveloper** [comment] 2022-03-29 08:14
+1 on this request. It'd be great to see a fix for this issue in the upcoming release as lots of our content is impacted.

**Comment by kirkilj** [comment] 2022-04-19 17:46
I'd also like to see this addressed in the main distribution without having to rely on a patch. My manager and our Information Architects have been trying to impress upon our CTO the reuse benefits of DITA compared to Markdown. Any reuse caveats or frailty works against us in this regard. I also don't see a corresponding pull request with Radu's code.

**Comment by ToshihikoMakita** [comment] 2022-04-20 00:30
> My manager and our Information Architects have been trying to impress upon our CTO the reuse benefits of DITA compared to Markdown. 

It's very important point for you and also for me!

**Comment by mgilster** [comment] 2022-05-05 17:19
@raducoravu I created a patched dost.jar incorprating your fix for this issue and it works great. I hope this can make it into a future version, so we can resume using an official release. Can you make a PR with your change? Thanks.

**Comment by raducoravu** [comment] 2022-05-06 05:17
The current behavior is not necessarily a bug, it is considered that only topics referenced directly in the DITA Maps may contain keyrefs so my fix which iterates for keyrefs also on other topics induces a small performance hit as more resources get processed looking for keyrefs. But in a way I'm undoing the current performance optimization, this is why I need @jelovirt 's advice about it. I will try to bring this issue up in the next DITA OT contributors meeting.

**Comment by mgilster** [comment] 2022-05-24 17:45
Thanks @raducoravu. Perhaps this could be controlled by a parameter.

**Comment by raducoravu** [comment] 2022-05-25 03:44
@mgilster I asked about this issue in the DITA OT meetup, @robander  seemed to agree with @drmacro 's evaluation that the current behavior of keyrefs not being resolved would be incorrect.
The code changes I suggested are a patch, they are not what I would consider a final clean version of a solution for this. So I will not create a pull request for this as it would probably not be accepted.

**Comment by chrispy-snps** [comment] 2022-07-08 22:02
We are hitting this too in some older content we authored. We will convert to `@conkeyref` and check the results for correctness.

**Comment by jelovirt** [comment] 2023-08-03 13:27
Duplicate of #3446. Fixed by #4237

**Closed by jelovirt** 2023-08-03 13:27 UTC
