### ISSUE TITLE
java.lang.IllegalArgumentException: URI has a query component

### ISSUE THREAD

**Issue by hongyung** [dita-ot/dita-ot#3717] opened 2021-03-16 10:01 UTC
## Expected Behavior
DITA-OT should be able to produce output with the URI in the example below:
`<xref format="html" href="www.google.com/search?abc=xyz" ixia_locid="292" scope="external">www.google.com/search?abc=xyz</xref>`

## Actual Behavior
dita-ot-3.6\plugins\org.dita.base\build_preprocess2.xml:171: java.lang.IllegalArgumentException: URI has a query component

## Possible Solution
unknown

## Steps to Reproduce
Create a topic with this type of href. Generate output of this topic -> PDF/Webhelp/Htmlhelp

## Copy of the error message, log file or stack trace
Error: The following error occurred while executing this line:
D:\IxiaSoft\OutputGenerator\development\data\dita-ot-3.6\plugins\org.dita.base\build_preprocess2.xml:66: java.lang.IllegalArgumentException: URI has a query component
2021-03-16 10:57:15,920	ERROR	org.apache.tools.ant.taskdefs.ExecTask	Result: 1

## Environment
* DITA-OT version: 3.6
* Operating system and version:
Windows
* How did you run DITA-OT?
Ixiasoft Output Generator
* Transformation type:
PDF, HTML5 etc..

**Comment by raducoravu** [comment] 2021-03-16 10:27
@hongyung can you try also with DITA OT 3.6.1?

**Comment by skulle** [comment] 2021-03-17 12:02
Hi,
I couldn't reproduce this with 3.6.1.

**Comment by raducoravu** [comment] 2021-03-17 12:07
I suspect this was fixed in #3677

**Closed by raducoravu** 2021-03-17 12:07 UTC
Labels: needs reproduction

**Comment by raducoravu** [comment] 2021-06-24 06:25
This was not fixed in #3677 and I consider it kind of critical, if somebody has an xref with scope external to an HTML document with a query component anywhere in the DITA project, the publishing breaks.

**Comment by svccsotest10** [comment] 2021-09-13 09:10
HI,

I can reproduce the error with the relative path:

<xref format="html" href="../some/path/to/file/file.html?" scope="external">text</xref>

Could you please assist to solve this or advise on a workaround? We recently switched to OT 3.6.1 from 3.0.4 and this wasn't an issue with the old version.

Thanks!

**Comment by azvassileva** [comment] 2021-09-13 09:12
HI,

I can reproduce the error with the relative path:

<xref format="html" href="../some/path/to/file/file.html?" scope="external">text</xref>

Could you please assist to solve this or advise on a workaround? We recently switched to OT 3.6.1 from 3.0.4 and this wasn't an issue with the old version.

Thanks!
