### ISSUE TITLE
Suspected memory leak in OT

### ISSUE THREAD

**Issue by sfogel** [dita-ot/dita-ot#1513] opened 2013-05-24 04:26 UTC
We're building a bookmap with just over 1000 topics, and we're seeing what appears to be evidence of a memory leak in the OT 1.7 and 1.7.5. We allocated 5MB in ANT_OPTS. Physical memory usage started at 2GB and then during the gen-list and filter phases it grew linearly to 6MB, then leveled off and started decreasing slightly. We saw a number of instances of the CPU pinned at 100% during this memory climb. If we allocate less than 5MB, the OT spends about half its time at 100% CPU and the build takes very long. Allocating less than 4MB causes the too-much-time-in-garbage-collection abort. Enclosed is a screenshot of the memory usage graph during just the gen-list and filter phases.

This is reproduceable on 3 different machines with this source input.

![leak](https://f.cloud.github.com/assets/2956867/558668/9c90593e-c429-11e2-9a3c-e27af694c6ab.gif)

**Comment by rieztra** [comment] 2015-05-06 20:54
Hi @easirois 

Do you know if this fix ever made it to the DITA OT 1.8.5? We're seeing huge memory usage.

Thanks,
Francisco

**Comment by jelovirt** [comment] 2015-05-07 03:30
It's not in 1.8.

**Comment by easirois** [comment] 2015-05-07 14:21
I can't recall at the moment, but likely not. That said, not sure if there will be a 1.8.6, but I can look a delivering a pull request 1.8.x, 2.0.x and 2.1. I'm setting a new laptop for my new job, so it would likely take me a few days to get everything setup.

**Comment by easirois** [comment] 2015-05-07 15:55
Looks like I created a fix for it in my own repository, but it looks like I didn't do a specific pull request for it.

**Comment by rieztra** [comment] 2015-05-07 20:00
Thanks @easirois getting that fix will help us a lot!

**Comment by easirois** [comment] 2015-05-12 00:56
Looking back that the thread again, Radu ran into an issue with the patch for this issue. https://www.mail-archive.com/j-dev%40xerces.apache.org/msg04996.html  I need to confirm with Radu that the issue he ran into is only limited to oXygen. I'm not sure what issue what Radu was specifically trying to tackle. 

Worst comes to worst I may need to build a separate dost.jar file again.

**Comment by raducoravu** [comment] 2015-05-12 05:35
As far as I know, the current state of things with DITA OT grammar caching and XML Schema-based topics is that grammar caching was disabled by @jelovirt for XML Schema-based topics:

https://github.com/dita-ot/dita-ot/pull/1401

This is the correct approach due to the issues Xerces has with caching multiple schemas with the same target namespace (no namespace in our case). We also have some internal caching in Oxygen for DITA Map-wide validation and again we only provide this caching for DTD-based topics.

So right now processing XML Schema based topics takes longer as the schemas are parsed for each parsed topic but should have no memory issues because no schemas are accumulated anywhere.

**Comment by adauco** [comment] 2015-05-13 16:20
Hi guys,
@easirois and @raducoravu, I have this  book we are using, and we have memory issues, this book has more than 1500 topics, is this good to reproduce the issue?
Thanks
https://drive.google.com/open?id=0B1OYDOsKcxuYVlNTRlhuT1VUd0U&authuser=0

**Comment by adauco** [comment] 2015-05-13 22:22
@easirois,
Could you provide me your email? where I can send you the sources.
Thanks!

**Comment by raducoravu** [comment] 2015-05-14 11:00
I found some time to run some tests on the provided samples.

Preliminary conclusions:

Using DITA Open Toolkit 1.8 I could not produce plain XHTML output from them, no matter what value was set for the parameter "args.grammar.cache".

Using DITA Open Toolkit 2.0.1 with only 256 MBs allocated to the transformation I managed to produce output by setting "args.grammar.cache" to "no". Setting it to "yes" I could no longer produce the XHTML, an out of memory occurred when processing one of the topics.
So there is still a problem with using "args.grammar.cache"="yes" with XML Schema based DITA topics and DITA OT 2.0.1

**Comment by raducoravu** [comment] 2015-05-14 11:21
I added logging to the method:

org.dita.dost.util.XMLGrammarPoolImplUtils.putGrammar(Grammar)

    /**
    * @see org.apache.xerces.util.XMLGrammarPoolImpl#putGrammar(org.apache.xerces.xni.grammars.Grammar)
    */
    @Override
    public void putGrammar(Grammar grammar) {
      System.err.println("PUT GRAMMAR IN " + hashCode());
    super.putGrammar(grammar);
    System.err.println("GC " + fGrammarCount);
    }


and it seems that in the same grammar cache object the grammars keep getting added and accumulated in the [gen-list] stage.

As a possible way of avoiding to cache XML Schema grammars no matter what value the parameter args.grammar.cache has, in the Java class "XMLGrammarPoolImplUtils.java" we could overwrite the method:

    /**
    * @see org.apache.xerces.util.XMLGrammarPoolImpl#putGrammar(org.apache.xerces.xni.grammars.Grammar)
    */
    @Override
    public void putGrammar(Grammar grammar) {
        //Avoid caching any type of XSD grammar
      if(grammar instanceof org.apache.xerces.impl.xs.SchemaGrammar){
        return;
      }
      super.putGrammar(grammar);
    }

If this is done, I think this issue can be closed, real useful grammar caching cannot be done using the Xerces grammar pool, not yet anyway. But the grammar pool will be automatically disabled for xml schema based grammars. So the transformation will take more time but at least it will be successful without out of memory problems.

**Comment by jelovirt** [comment] 2015-05-14 12:44
@raducoravu could you send a pull request for this?

**Comment by jelovirt** [comment] 2015-05-23 04:30
Fixed by disabling XSD grammar caching.

**Closed by jelovirt** 2015-05-23 04:30 UTC
Labels: bug, preprocess
