### ISSUE TITLE
flag as default ditaval action does not work

### ISSUE THREAD

**Issue by mnordseth** [dita-ot/dita-ot#1851] opened 2015-02-13 10:44 UTC
Hi,

I would like to use flag as the default action in a ditaval file, but that does not work. An example ditaval file:

```xml
<val>
   <prop action="flag" color="red" />
</val>
```

If I change the action to "exclude", the content gets removed from the output. I have tested this with OT 2.0.1.

Is this considered a valid usecase? It would be very useful in a review context, be able to see what content does not match the ditaval file.

**Comment by jelovirt** [comment] 2015-02-15 13:40
Probably related to #1415

**Comment by jelovirt** [comment] 2015-02-15 13:49
Closing as duplicate of #1415

**Closed by jelovirt** 2015-02-15 13:49 UTC
Labels: duplicate
