### ISSUE TITLE
DITA-OT 2.0 - Build Error (Windows) - Illegal character - keyref target

### ISSUE THREAD

**Issue by jlowther** [dita-ot/dita-ot#1823] opened 2014-12-12 20:25 UTC
Attempting to produce output using DITA-OT 2.0 on Windows results in build failure with the following message:

> C:\ditaot\plugins\org.dita.base\build_preprocess.xml:285: java.lang.IllegalArgumentException: Illegal character in path at index 3: bcc\concepts\notification_events.dita

The map file is the following:

```xml
<!-- configuration.ditamap -->
<topicref navtitle = "Notification Events"
    href = "../concepts/notification_events.dita" type = "concept">
<topicmeta><navtitle>Notification Events</navtitle></topicmeta></topicref>

<keydef href = "images/notification_events.png"
    keys = "notification_events_image" format = "png"><topicmeta>
<navtitle>NO TITLE</navtitle></topicmeta></keydef>
```
The topic in question:
```xml
<!-- notification_events.dita -->
<fig frame = "all"><image href = "../dhcp/images/notification_events.png"
height="289.440pt" width="281.280pt" placement="break"  keyref =
"notification_events_image" /></fig>
```

**Comment by raducoravu** [comment] 2015-06-11 07:28
The full stack trace is something like:

            BUILD FAILED
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\build.xml:41: The following error occurred while executing this line:
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.base\build_preprocess.xml:285: java.lang.IllegalArgumentException: Illegal character in path at index 6: folder\2.xml
            	at java.net.URI.create(Unknown Source)
            	at java.net.URI.resolve(Unknown Source)
            	at org.dita.dost.writer.KeyrefPaser.startElement(KeyrefPaser.java:404)
            	at org.dita.dost.writer.ConkeyrefFilter.startElement(ConkeyrefFilter.java:90)
            	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
            	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
            	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(RelaxNGDefaultsComponent.java:635)
            	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:260)
            	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1655)
            	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
            	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:150)
            	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
            	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
            	at net.sf.saxon.event.Sender.send(Sender.java:146)
            	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
            	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:188)
            	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:148)
            	at org.dita.dost.module.KeyrefModule.execute(KeyrefModule.java:124)
            	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
            	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
            	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
            	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
            	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
            	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
            	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
            	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
            	at org.apache.tools.ant.Main.runBuild(Main.java:851)
            	at org.apache.tools.ant.Main.startAnt(Main.java:235)
            	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
            	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
            Caused by: java.net.URISyntaxException: Illegal character in path at index 6: folder\2.xml
            	at java.net.URI$Parser.fail(Unknown Source)
            	at java.net.URI$Parser.checkChars(Unknown Source)
            	at java.net.URI$Parser.parseHierarchical(Unknown Source)
            	at java.net.URI$Parser.parse(Unknown Source)
            	at java.net.URI.<init>(Unknown Source)
            	... 54 more

**Comment by raducoravu** [comment] 2015-06-11 07:38
The problem is at this line:

      job.tempDir.toURI().resolve(inputFile.getPath())

When running on Windows, the inputFile.getPath() has "\" in it. So it would at least need to convert "\" to "/" like:

      job.tempDir.toURI().resolve(inputFile.getPath().replace('\\', '/'))

but we might also need to escape other spaces or illegal URI characters.

**Comment by jelovirt** [comment] 2015-06-11 07:42
Seems to be fixed in `develop`, https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/writer/KeyrefPaser.java#L406

**Comment by raducoravu** [comment] 2015-06-11 07:47
Indeed, it looks fixed in the sources. Then you can probably close this one.

**Closed** 2015-09-24 04:54 UTC
Labels: bug, P2, platform-dependent, preprocess/keyref
