### ISSUE TITLE
Images are not displayed when transforming ditamap with chunk="to-content" using HTML5 with preprocess2

### ISSUE THREAD

**Issue by jlacour31** [dita-ot/dita-ot#4042] opened 2022-11-09 15:32 UTC
## Expected Behavior
When transforming ditamap having chunk="to-content" set on it, images should be displayed.

## Actual Behavior
No images are present in the output.

## Steps to Reproduce
[chunk.zip](https://github.com/dita-ot/dita-ot/files/9972528/chunk.zip)

1. Download and unzip the archive
2. Run the HTML5 transformation using preprocess2

## Environment
* DITA-OT version: 3.7.4
* Operating system and version: Windows
* How did you run DITA-OT? oXygen
* Transformation type: HTML5 using preprocess2

**Comment by chrispy-snps** [comment] 2022-11-20 23:21
Using [`ditaot_save_preprocessing.pl`](https://github.com/chrispy-snps/DITA-ditaot-utilities#using-ditaot_save_preprocessingpl), I saved the `preprocess2` results for a "bad" run (with `@chunk="to-content"`) and a "good" run (without it).

Here are the "good" results for `map-clean-map` and `clean-preprocess`:

```
temp_good-21-map-clean-map/dcd333eb80e02f92e4b90d296b1ac6c0bbeea322.dita
4:        <image href="5a1a3b8f8c31f2f6855a2afba26db7a878300d90.png" id="image_wqd_xjs_lvb" placement="inline" class="- topic/image " xtrf="file:/mnt/c/nobackup/4042/chunk/topic.dita" xtrc="image:1;6:57"/>

temp_good-22-clean-preprocess/topic.dita
4:        <image href="image.png" id="image_wqd_xjs_lvb" placement="inline" class="- topic/image " xtrf="file:/mnt/c/nobackup/4042/chunk/topic.dita" xtrc="image:1;6:57"/>
```

Here are the "bad" results for `map-clean-map` and `clean-preprocess`:

```
temp_bad-21-map-clean-map/d8f29e6b55ad3358e63d1ed00f720791b2b083df.dita
6:        <image href="5a1a3b8f8c31f2f6855a2afba26db7a878300d90.png" id="image_wqd_xjs_lvb" placement="inline" class="- topic/image " xtrf="file:/mnt/c/nobackup/4042/chunk/topic.dita" xtrc="image:1;6:57"/>

temp_bad-22-clean-preprocess/d8f29e6b55ad3358e63d1ed00f720791b2b083df.dita
6:        <image href="5a1a3b8f8c31f2f6855a2afba26db7a878300d90.png" id="image_wqd_xjs_lvb" placement="inline" class="- topic/image " xtrf="file:/mnt/c/nobackup/4042/chunk/topic.dita" xtrc="image:1;6:57"/>
```

Somehow the `clean-preprocess` is not resolving the hashed `5a*90.png` filename back to the physical `image.png` filename. The jobs.xml file in both runs has a `<file>` mapping entry:

```
$ grep 5a1a temp_good-21-map-clean-map/.job.xml
187:    <file src="file:/mnt/c/nobackup/4042/chunk/image.png" uri="5a1a3b8f8c31f2f6855a2afba26db7a878300d90.png" path="5a1a3b8f8c31f2f6855a2afba26db7a878300d90.png" result="file:/mnt/c/nobackup/4042/chunk/image.png" format="image"/>
$ grep 5a1a temp_bad-21-map-clean-map/.job.xml
187:    <file src="file:/mnt/c/nobackup/4042/chunk/image.png" uri="5a1a3b8f8c31f2f6855a2afba26db7a878300d90.png" path="5a1a3b8f8c31f2f6855a2afba26db7a878300d90.png" result="file:/mnt/c/nobackup/4042/chunk/image.png" format="image"/>
```

I also noticed #3514, which might or might not be related.

**Comment by raducoravu** [comment] 2022-11-23 15:24
Indeed this looks like a duplicate of #3514

**Comment by raducoravu** [comment] 2022-12-14 05:36
A similar problem can be reproduced with the new chunking processing step, if I force version 2.0 on the map root:

		<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
		<map chunk="combine" ditaarch:DITAArchVersion="2.0">
		    <title>Map</title>
		    <topicref href="parent_topic.dita">
		        <topicref href="topic.dita"/>
		    </topicref>
		</map>

**Comment by raducoravu** [comment] 2022-12-14 05:49
@jelovirt maybe at some point if you will find the time to analyze how this could be fixed...

As a small overview, because the chunk attribute is added directly on the map root element, the method "org.dita.dost.reader.ChunkMapReader.chunkMap(Element)" will add an "href" attribute to it with the new name (which is a hash of the original "mapName.ditamap" with the extension changed).
Afterwards the "org.dita.dost.writer.ChunkTopicParser.processChunk(Element, URI)" method will get called for the &lt;map> element which now has an @href attribute. So it ends up in a special case where it generates a new file on disk with its name hashed:

      if (MAP_MAP.matches(classValue)) {

So the final generated .job.xml will have this entry for the newly generated topic:

		<file uri="0e1db5ab2321bf237615736fcdbad9f6411c730c.dita"
			path="0e1db5ab2321bf237615736fcdbad9f6411c730c.dita" format="dita"/>

which means an HTML document with the name of the hash gets generated. The entry is also missing an @src attribute because the topic was generated, it did not exist in the original DITA Map. Also the artificially generated topic is not processed to replace its image reference with the original image name and to copy the image to the output folder.

Possibly when the method "org.dita.dost.writer.AbstractChunkTopicParser.generateFileInfo(URI)" gets called we need to also generate an "src" field for the fileInfo added to the Job.

**Comment by jelovirt** [comment] 2023-02-09 15:40
Closing as duplicate of #3514

**Closed by jelovirt** 2023-02-09 15:40 UTC
Labels: bug, preprocess2
