### ISSUE TITLE
Compact way of branch filtering with DITA Maps reports error (DOT 2.x develop branch)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1993] opened 2015-08-07 06:08 UTC
If my main DITA Map has something like this:

      <topicref href="flowers.ditamap" format="ditamap">
       <ditavalref href="expert.ditaval"/>
       <ditavalref href="novice.ditaval"/>
      </topicref>

The DITA Open Toolkit publishing reports:

       [DOTX068W]: A topicref element that references a map contains child topicref elements. Child topicref elements are ignored.

**Comment by jelovirt** [comment] 2015-08-07 07:28
This is in effect a duplicate of #1992 as mapref processing doesn't yet support branch filtering

**Closed by jelovirt** 2015-08-07 07:28 UTC
