### ISSUE TITLE
DITA OT does not resolve relative paths

### ISSUE THREAD

**Issue by GosiaR** [dita-ot/dita-ot#2545] opened 2016-12-13 16:17 UTC
When publishing by using oXygen, DITA OT displays conref errors. The issue seems to be related to relative paths that DITA OT does not resolve correctly. 
The erros are e.g.: ```Severity: error
Description: [DOTX031E]: The file file:/C:/Users/ASUS/Documents/Jorsek/WhP/localization-job-109/source-language-reference/repositories/master/documentation/documents/Instructive_Learning_and_Training/Demo_Content/Hardware/temp/webhelp/Hardware/_Global_Shared/../../_Global_Shared/safety.dita is not available to resolve link information. 
Start location: 3:1079
URL: http://www.oxygenxml.com/DITA-messages.html#msgs__DOTX031E```

DITA OT version: DITA-OT-2.3.1. You can replicate the issue by using the attached package and publishing HTML output from `localization-job-109\source-language-reference\repositories\master\documentation\documents\Instructive_Learning_and_Training\Demo_Content\Hardware\Classic_Toaster\classic_toaster_user_guide.ditamap`
[localization-job-109.zip](https://github.com/dita-ot/dita-ot/files/649438/localization-job-109.zip)

**Comment by shaneataylor** [comment] 2016-12-13 17:19
So far as I can tell, this is not a conref issue (I don't find a conref reference to the topic). I didn't try to build, but historically DITA-OT had an issue with referencing topics in parent or sibling directories to the ditamap. If this is happening, it would still be a problem, just not a conref problem.

**Comment by shabanovd** [comment] 2016-12-13 18:59
It most likely to be conref because when I run it locally there are errors similar to this one
```
     [exec] conref:
     [exec]    [conref] Transforming into /var/folders/3m/8g8cqv1n42v2vbh1d7ntp1800000gn/T/temp20161213140935382
     [exec]    [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref] Loading stylesheet /Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conref.xsl
     [exec]    [conref] Processing /var/folders/3m/8g8cqv1n42v2vbh1d7ntp1800000gn/T/temp20161213140935382/_Global_Shared/safety.dita
     [exec]    [conref] Recoverable error on line 180 of conrefImpl.xsl:
     [exec]    [conref]   FODC0002: java.io.FileNotFoundException:
     [exec]    [conref]   /var/folders/3m/8g8cqv1n42v2vbh1d7ntp1800000gn/T/temp20161213140935382/_Global_Shared/../variables_warehouse.dita (No such file or directory)
     [exec]    [conref] Error on line 277 of conrefImpl.xsl:
     [exec]    [conref]   XTTE0570: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#804)
     [exec]    [conref]      processing /reference/shortdesc[1]/ph[1]
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#804)
     [exec]    [conref]      processing /reference/shortdesc[1]
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#34)
     [exec]    [conref]      processing /reference
     [exec]    [conref] Processing /var/folders/3m/8g8cqv1n42v2vbh1d7ntp1800000gn/T/temp20161213140935382/_Global_Shared/notes_warehouse.dita
     [exec]    [conref] Recoverable error on line 180 of conrefImpl.xsl:
     [exec]    [conref]   FODC0002: java.io.FileNotFoundException:
     [exec]    [conref]   /var/folders/3m/8g8cqv1n42v2vbh1d7ntp1800000gn/T/temp20161213140935382/_Global_Shared/../variables_warehouse.dita (No such file or directory)
     [exec]    [conref] Error on line 277 of conrefImpl.xsl:
     [exec]    [conref]   XTTE0570: An empty sequence is not allowed as the value of variable $domains
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#804)
     [exec]    [conref]      processing /topic/body[1]/p[1]/note[1]/ph[1]
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#804)
     [exec]    [conref]      processing /topic/body[1]/p[1]/note[1]
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#804)
     [exec]    [conref]      processing /topic/body[1]/p[1]
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#804)
     [exec]    [conref]      processing /topic/body[1]
     [exec]    [conref]   at xsl:apply-templates (file:/Users/dmitriyshabanov/Projects/dita/rev2/dita-ot-2.4/xsl/preprocess/conrefImpl.xsl#34)
     [exec]    [conref]      processing /topic
```

**Comment by raducoravu** [comment] 2016-12-14 08:21
I looked at the samples and I agree with @shaneataylor in the fact that there are references to resources outside of the folder where the DITA Map is located.
Setting the "generate.copy.outer" parameter to "3" helps.
Also if you are using Oxygen we have another special parameter to fix such references:
https://www.oxygenxml.com/doc/versions/18.1/ug-editor/topics/dita-ot-external-refs.html

**Comment by raducoravu** [comment] 2016-12-14 08:24
I would consider this issue a duplicate of:
https://github.com/dita-ot/dita-ot/issues/1762

**Closed by raducoravu** 2016-12-14 08:24 UTC

**Comment by shabanovd** [comment] 2016-12-14 09:38
`generate.copy.outer=3` didn't help me. Here [full log](https://gist.github.com/shabanovd/59ea04dedf64ab01f43a8daf9009dd1f)

**Comment by raducoravu** [comment] 2016-12-14 10:20
Sorry, tested again and it's my mistake, the problem can still be reproduced with "generate.copy.outer=3".
It is still a problem of references to resources outside of the folder where the DITA Map is located though.

**Comment by shabanovd** [comment] 2016-12-14 10:38
@raducoravu what is possible solution or workaround for it?

**Comment by raducoravu** [comment] 2016-12-14 11:47
Basically both workarounds I listed here work:

https://www.oxygenxml.com/doc/versions/18.1/ug-editor/topics/dita-ot-external-refs.html
