### ISSUE TITLE
Wrong error message in: Error: Failed to run pipeline: [DOTA069F][FATAL] Input file

### ISSUE THREAD

**Issue by philiprbrenan** [dita-ot/dita-ot#2475] opened 2016-09-11 16:26 UTC
In the event that the referenced  DTD file is incorrect the error message reports the source file as non existent.  

In:

![1](https://cloud.githubusercontent.com/assets/7548378/18418662/7848b73a-7842-11e6-9a04-77dc49e4edf2.png)

I was able to convert a file successfully.  

In:

![2](https://cloud.githubusercontent.com/assets/7548378/18418663/784c645c-7842-11e6-9042-32183333c278.png)

I changed the DTD file name from /home to /HOME to make it invalid, but the message that comes back is:

Error: Failed to run pipeline: [DOTA069F][FATAL] **Input file 'file:/home/phil/dita/dita-ot/src/main/docsrc/samples/test.xml'** cannot be located or read.

despite:

```
ls -la /home/phil/dita/dita-ot/src/main/docsrc/samples/test.xml
-rw-rw-r-- 1 phil phil 387 Sep 11 17:02 /home/phil/dita/dita-ot/src/main/docsrc/samples/test.xml
```

This is highly misleading and confusing!

The erroneous message arises because in the Java source, a single try statement wraps far too many statements and then attempts to decode errors via an enormous set of catch blocks.  A better solution would be to use a number of try statements each more local to the statements to be executed to obtain a more granular result.

This error is extremely damaging to the credibility of the DITA OT because new users attempting to use it for the first time become highly frustrated with the time they must waste tracking down this error.  Indeed, it will beyond the capability of most new users to resolve this error  expeditiously because the error message is so misleading.

A better error message such as: "DTD file ... not found" would allow even a novice to resolve this error quickly and in doing so gain confidence in their ability to use this toolkit successfully.

I therefore implore you to fix this error promptly in order to preserve the honor and respect that the Open Source Software process so rightly deserves.

**Comment by eerohele** [comment] 2016-09-11 17:55
Duplicate of #2461.

I do agree that this should be fixed, though -- I've been confused by the same issue myself in the past.

**Closed** 2016-09-21 03:35 UTC
Labels: duplicate
