### ISSUE TITLE
Incorrect entry@colname in merged XML with row and colspan

### ISSUE THREAD

**Issue by mikeewins** [dita-ot/dita-ot#1660] opened 2014-03-20 12:55 UTC
This issue was reported fixed in 1.5.4 under #697, but I am finding that I have the issue in 1.6.2 UNLESS the colname is explicitly specified in the entry element (NB: I've only specified it for c2 in this example because the only problem we had was that c2 was being mistaken for c1 and we format the first column differently):

``` xml
<thead>
      <row>
            <entry ixia_locid="8" morerows="1">Product Name</entry>
            <entry ixia_locid="9">Min. peak output current</entry>
            <entry ixia_locid="10" morerows="1">Output configuration</entry>
            <entry ixia_locid="11">Propagation delay</entry>
            <entry ixia_locid="12">Undervoltage lockout Vcc2</entry>
      </row>
      <row>
            <entry colname="c2" ixia_locid="13">(source / sink) A (PROBLEM CELL)</entry>
            <entry ixia_locid="14">(tpy) ns</entry>
            <entry ixia_locid="15">(off / on) V</entry>
      </row>
</thead>
```

i.e., the first entry in row two has colname=”c2” added to it to clearly identify where it belongs.

Examples of merged xml with and wihout the explicit colname on the entry:

When `<entry ixia_locid="13" colname="c2">(source / sink) A (PROBLEM CELL)</entry>`

``` xml
<row class="- topic/row " xtrc="row:2" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">
<entry class="- topic/entry " colname="col2" ixia_locid="13" xtrc="entry:6" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">(source / sink) A (PROBLEM CELL)</entry>
<entry class="- topic/entry " colname="col3" ixia_locid="14" xtrc="entry:7" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">(tpy) ns</entry>
<entry class="- topic/entry " colname="col4" ixia_locid="15" xtrc="entry:8" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">(off / on) V</entry>
</row>
```

When the colname is not set `<entry ixia_locid="13">(source / sink) A (PROBLEM CELL)</entry>`

``` xml
<row class="- topic/row " xtrc="row:2" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">
<entry class="- topic/entry " colname="col1" ixia_locid="13" xtrc="entry:6" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">(source / sink) A (PROBLEM CELL)</entry>
<entry class="- topic/entry " colname="col2" ixia_locid="14" xtrc="entry:7" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">(tpy) ns</entry>
<entry class="- topic/entry " colname="col3" ixia_locid="15" xtrc="entry:8" xtrf="C:\Program Files\DITA-OT1.6.2\mekon\infenion\ret1387457707174.xml">(off / on) V</entry>
</row>
```

Our users are happy with the workaround short term but would like a permanent fix in the DITA OT.

**Comment by raducoravu** [comment] 2018-12-13 08:53
To me this looks like a duplicate of: https://github.com/dita-ot/dita-ot/issues/1912

**Closed as completed** 2018-12-13 13:26 UTC
Labels: bug, duplicate, plugin/pdf, priority/low
