### ISSUE TITLE
SVG lengths having NaN values when scaling SVG images

### ISSUE THREAD

**Issue by jlacour31** [dita-ot/dita-ot#3785] opened 2021-08-05 12:32 UTC
## Expected Behavior
I have a topic with 2 SVG images, one scaled and one not.
I transform the ditamap containing the topic into an HTML5 output.
I open the result and I am hoping for the scaled SVG to be smaller than the normal one.

## Actual Behavior
I open the result and go to topic.html, both images have the same size.

## Possible Solution
The following template can be modified in org.dita.html5/xsl/topic.xsl as following:
```
<!-- AM: handling for scale attribute -->
<xsl:template match="*[contains(@class, ' topic/image ')]/@scale">
  <xsl:variable name="width-in-pixel">
    <xsl:call-template name="length-to-pixels">
      <xsl:with-param name="dimen" select="../@dita-ot:image-width"/>
    </xsl:call-template>
  </xsl:variable>
  <xsl:variable name="height-in-pixel">
    <xsl:call-template name="length-to-pixels">
      <xsl:with-param name="dimen" select="../@dita-ot:image-height"/>
    </xsl:call-template>
  </xsl:variable>
  <xsl:if test="not(../@width) and not(../@height)">
    <xsl:attribute name="height" select="floor(number($height-in-pixel) * number(.) div 100)"/>
    <xsl:attribute name="width" select="floor(number($width-in-pixel) * number(.) div 100)"/>
  </xsl:if>
</xsl:template>
```

## Steps to Reproduce
1. Download [issue.zip](https://github.com/dita-ot/dita-ot/files/6938590/issue.zip) and unzip it
2. Run the command line and generate HTML5 output
3. Open the topic.html from the output folder

## Environment
* DITA-OT version: 3.6.1
* Operating system and version: Windows 64
* How did you run DITA-OT? Command Line & Oxygen
* Transformation type: HTML5, XHTML

**Comment by raducoravu** [comment] 2021-11-04 05:00
@jelovirt this seems to have been merged but the issue is still opened.

**Closed** 2021-11-08 19:38 UTC
Labels: bug
