### ISSUE TITLE
org.dita.pdf2 misses German variable translations

### ISSUE THREAD

**Issue by nakohdo** [dita-ot/dita-ot#1857] opened 2015-02-20 13:18 UTC
It seems that the translated variables for German:
    `DITA-OT\plugins\org.dita.pdf2\cfg\common\vars\de.xml`
contain less matches than the English ones:
    `DITA-OT\plugins\org.dita.pdf2\cfg\common\vars\en.xml`

The XSLT DITA-OT/plugins/org.dita.pdf2/xsl/fo/links.xsl seems to require certain related-links keys to be translated although they are not used for anything because by default in PDF no related link sections are built.

First reported at http://www.oxygenxml.com/forum/post32843.html#p32843

I will provide the missing translations asap.

**Comment by nakohdo** [comment] 2015-02-20 16:43
I've started updating the German variables file and noticed that there were some variables from the English file missing. However, adding those to the German variables files hasn't solved the problem yet. I will have a closer look and report back.

https://github.com/nakohdo/dita-ot/blob/1857-missing-german-translations/src/main/plugins/org.dita.pdf2/cfg/common/vars/de.xml

**Comment by nakohdo** [comment] 2015-02-23 12:53
The issues seems to be a bit more complicated. JFTR here's the error message again as mentioned in the oXygen forum:

## Error messages
```
[DOTX067E]: No string named 'Related concepts' was found for language 'de-DE'. Add a mapping for the string 'Related concepts'. The location of this problem was at (File = RNG_topic_with_xml-lang.dita, Element = topic:1;4:47)
[DOTX067E]: No string named 'Related tasks'...
[DOTX067E]: No string named 'Related references' ...
[DOTX067E]: No string named 'Related information' ...
```

## Further findings:

* There is a section for related references in ''en.xml'' but not for the other topic types:
```
<!-- The title of the links to Related references -->
<variable id="Related references">Related References</variable>
```
https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/common/vars/en.xml

* Adding this section to ''de.xml'' doesn't solve the problem.

* The responsible XSLT seems to be in ''link.xsl'':

```
<xsl:call-template name="getString">
<xsl:with-param name="stringName" select="'Related concepts'"/>
```
https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/xsl/fo/links.xsl

**Comment by jelovirt** [comment] 2015-02-23 16:14
Some variables are omitted from German variable file because they are obsolete. The ones that are missing are missing because the project has no translation resources and we rely on pull-requests to add those translations.

**Comment by jelovirt** [comment] 2015-02-23 16:24
Can't reproduce the issue with 2.1 code. Note that e.g. "Related concepts" is not part of PDF plugin variables, it's found in the base plugin variable files.

**Comment by raducoravu** [comment] 2015-02-24 09:12
I can also confirm I cannot reproduce the issue with 2.1 code. So somehow the problem is not anymore in 2.1 and the issue can probably be closed.

**Comment by jelovirt** [comment] 2015-02-24 09:14
Closing as obsolete

**Closed by jelovirt** 2015-02-24 09:14 UTC
Labels: bug, obsolete, pdf

**Comment by nakohdo** [comment] 2015-02-24 14:49
Thanks for testing and the feedback.
