### ISSUE TITLE
Term reflects acronym or abbreviation when it should not.

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2788] opened 2017-09-18 02:29 UTC
## Expected Behavior

References from `<term>` elements to glossary entries with abbreviations or acronyms should not reflect the acronym but the base term (behavior is correct in PDF2 transform).

## Actual Behavior

Term reflects the acronym or abbreviation in HTML output (but not in PDF2 output).

## Possible Solution

Remove the check in "topic.term" template that gets the matching acronym. That behavior should be applied to abbreviated-form.

## Steps to Reproduce

1. Process root map https://github.com/dita-community/dita-test-cases/blob/master/glossaries/realistic-glossary/glossary-using-publication-01.ditamap with XHTML or HTML5 transform.
2. Observe that HTML for topic term_references.dita shows "PCT" for the `<term>` reference to the glossary entry wipo-glossary/glossentries/gloss_patent_cooperation_treaty_pct.dita where it should reflect "Patent Cooperation Treaty".

Generate PDF from the same root. Observe that the `<term>` reference correctly reflects the base term.

## Environment

* DITA-OT version: 2.5.3
* Operating system and version: macOS
* How did you run DITA-OT? oXygen
* Transformation type: HTML/HTML5

**Comment by xephon2** [comment] 2017-09-18 06:24
Probably a duplicate of #2173

**Comment by xephon2** [comment] 2017-09-18 06:27
If someone likes to close #2173 , but fix this one, you should consider using [Glossary-Test.zip](https://github.com/dita-ot/dita-ot/files/139646/Glossary-Test.zip) as test data. It's helpful for comparing the output with excepected output, see [this comment](https://github.com/dita-ot/dita-ot/issues/2173#issuecomment-186834447).

**Comment by jelovirt** [comment] 2017-09-18 10:16
@xephon2 If this is a duplicate of #2173, then this one will be closed. I don't have time right now to verify if these are the same bug, are you able to verify?

**Comment by xephon2** [comment] 2017-09-18 10:24
@jelovirt, yes, this is a duplicate. I'll copy @drmacro **'s** **possible solution to** #2173, so this one should be closed.

**Closed** 2017-09-18 10:48 UTC
Labels: duplicate
