### ISSUE TITLE
Space in URL leads to duplicate entry for key-based file reference

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1801] opened 2014-11-24 21:12 UTC
For OT 1.8.5 under OS X:

See https://dl.dropboxusercontent.com/u/20078596/dita-ot-bugs/escaped-url-mismatch.zip for sample data, including generated output and job.xml file.

Given these two topicrefs in a map:

~~~~
    <keydef keys="topic-01" href="../topics/DITAComm%20Topic-dtd.xml"/>
   <topicref keyref="topic-01" keys="chapter-01"/>
~~~~

Where "DITAComm Topic-dtd.xml" is the only topic referenced by the map, the job.xml file has two entries, one with the escaped space in the URL, flagged as resource-only, and one without, flagged as not resource only.

The resulting HTML output has no topic.

So either the URI is not being escaped during the resource-only processing or it's being inappropriately unescaped during key resolution to determine normal-mode topics, resulting in a mismatch that leads to the topic being incorrectly handled as resource-only.

**Comment by eerohele** [comment] 2015-11-21 22:48
Can't reproduce with 2.2, either; closing.

**Closed by eerohele** 2015-11-21 22:48 UTC
Labels: bug, preprocess/keyref
