### ISSUE TITLE
copy-to fails to update image paths

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2486] opened 2016-09-19 17:45 UTC
I have a topic in the directory `topics/` that includes two image references (one with a relative path, one with a key). Both images are located in the peer `images/` directory:
```
<ul>
<li>Image with relatve path: <image href="../images/happycat.jpg" alt="yuk"/></li>
<li>Image with key: <image keyref="flag"/></li>
</ul>
```

In my map, I publish that topic as-is; I also use `@copy-to` to copy it up a directory, down a directory, and to a peer directory.

My rendered HTML5 output has four copies of the topic (original, copied up, copied to peer, copied down). In all 4 versions, the original relative path `../images/` is used. This is true for both the relative-path version and the keyref version. As a result, the rendered topic is only valid in the original and peer directories.
[copyimage.zip](https://github.com/dita-ot/dita-ot/files/480722/copyimage.zip)

**Comment by raducoravu** [comment] 2016-09-20 05:17
Our tech writer also encounters such problem with copy-to. The only way in which this works is if the target copy-to file is targeted to be in the same folder path with the @href value.

**Comment by jelovirt** [comment] 2016-09-20 19:17
@robander are you able to verify that this fixes the issues you had and close the issue?

**Comment by raducoravu** [comment] 2016-09-23 06:58
I first reproduced the initial problem on 2.3.2. The problem could be reproduced in the XHTML outputs, the PDF worked.
I updated to the latest 2.3.3 github branch, run gradle. The XHTML output looks fixed, images appear in all HTML topics. The PDF output is broken though:


            map2pdf2:
            [topic-merge] Processing C:\Users\radu_coravu\Desktop\copy-image\temp\pdf\oxygen_dita_temp\P024801.ditamap
            [topic-merge] Processing C:\Users\radu_coravu\Desktop\copy-image\temp\pdf\oxygen_dita_temp\topics\test.dita
            [topic-merge] Failed to parse topics\test.dita: Illegal character in path at index 6: topics\test.dita
            [topic-merge] Error at xsl:element on line 64 of topicmergeImpl.xsl:
            [topic-merge]   XTDE0820: Invalid element name. Invalid QName {}
            [topic-merge]   in built-in template rule

**Comment by jelovirt** [comment] 2016-09-23 07:01
I think this isn't directly related to the original issue that link-like elements in shortdesc are not adjusted to the new base URI.

**Comment by raducoravu** [comment] 2016-09-23 07:07
Might not be related, I started to dig a little into this, the entire stack trace for PDF failure is:

            [topic-merge] Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 6: topics\test.dita
            [topic-merge] 	at java.net.URI.create(Unknown Source)
            [topic-merge] 	at java.net.URI.resolve(Unknown Source)
            [topic-merge] 	at org.dita.dost.reader.MergeTopicParser.handleID(MergeTopicParser.java:112)
            [topic-merge] 	at org.dita.dost.reader.MergeTopicParser.startElement(MergeTopicParser.java:215)
            [topic-merge] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
            [topic-merge] 	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startElement(RelaxNGDefaultsComponent.java:200)
            [topic-merge] 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:268)
            [topic-merge] 	at org.apache.xerces.impl.XMLNSDocumentScannerImplXerces$NSContentDispatcher.scanRootElementHook(XMLNSDocumentScannerImplXerces.java:733)
            [topic-merge] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1756)
            [topic-merge] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
            [topic-merge] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            [topic-merge] 	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:150)
            [topic-merge] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            [topic-merge] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
            [topic-merge] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
            [topic-merge] 	at org.dita.dost.reader.MergeTopicParser.parse(MergeTopicParser.java:191)
            [topic-merge] 	... 44 more
            [topic-merge] Caused by: java.net.URISyntaxException: Illegal character in path at index 6: topics\test.dita
            [topic-merge] 	at java.net.URI$Parser.fail(Unknown Source)
            [topic-merge] 	at java.net.URI$Parser.checkChars(Unknown Source)
            [topic-merge] 	at java.net.URI$Parser.parseHierarchical(Unknown Source)
            [topic-merge] 	at java.net.URI$Parser.parse(Unknown Source)
            [topic-merge] 	at java.net.URI.<init>(Unknown Source)
            [topic-merge] 	... 60 more

**Comment by raducoravu** [comment] 2016-09-23 08:09
Yup, not related. Problem was added by @eerohele in: https://github.com/eerohele/dita-ot/commit/3cf10d492702c2aab81ec30218081df858ef81e5
in MergeTopicParser he does something like this:

      final URI value = setFragment(dirPath.toURI().resolve(filePath), idValue);

but the "filePath" contains "\" on Windows so the URI resolution fails.

**Comment by jelovirt** [comment] 2016-09-23 09:03
The `clean` function should not be used there. Instead, `toURI` should be used.

**Comment by jelovirt** [comment] 2016-09-23 09:08
@raducoravu are you able to test the e0fba68 fix?

**Comment by raducoravu** [comment] 2016-09-23 09:12
:+1: Tested both fixes, they are good.

**Closed** 2016-09-23 09:12 UTC
Labels: bug, P3, preprocess, ready for review

**Comment by raducoravu** [comment] 2016-09-23 09:28
The issue is fixed but in one of the generated HTML documents "out\xhtml\copyup.html", the link to the CSS is broken, so it would probably need to be fixed as well. Should I open a new issue about this?

**Comment by jelovirt** [comment] 2016-09-23 09:29
@raducoravu yep, a separate issue or PR. Check first that it doesn't work in `develop`.

**Comment by marknyma** [comment] 2018-10-22 14:29
Regarding the original issue, if the file in @href is missing we get a freak "_Error: java.lang.NullPointerException_" and naturally the transformation fails with no info as to what would be the actual problem.

We are using dita-ot v2.5.4 with the [oXygen WebHelp](https://www.oxygenxml.com/xml_webhelp/download_oxygenxml_webhelp.html?os=DITAOT) transformation.
