### ISSUE TITLE
Plugin not called for all pre-process extension points for PDF transform

### ISSUE THREAD

**Issue by cmeister2** [dita-ot/dita-ot#3158] opened 2018-11-23 14:48 UTC
## Desired Goal
I'm attempting to update an old job we have - we have a custom Python script which converts textual instances of `@@VAR:SomeTextHere` into `<keyword keyref="SomeTextHere_first">` the first time the keyword is seen and `<keyword keyref="SomeTextHere_other">` for subsequent uses. These keywords are defined in the ditamap.

I don't want to modify the real source files, and ideally I don't want to have a 2-stage process of:

- Parse ditamap, copy all referred ditas to a temporary location and modify those files
- Run dita over the new files.

So I thought I could hook into the dependency points once the dita files have been copied across to the temporary directory, and modify them there.

## Expected Behavior
Using DITA-OT I expect my plugin to be called for the extension points defined in the docs (https://www.dita-ot.org/3.2/extension-points/plugin-extension-points-pre-processing.html) when performing PDF transform.

## Actual Behavior
It's only called for `depend.preprocess.pre` and `depend.preprocess.post`.

## Possible Solution
- PDF transforms are provided by org.dita.pdf2. 
- https://github.com/dita-ot/dita-ot/blob/3.2/src/main/plugins/org.dita.pdf2/build_template.xml defines the build template used for a transformation. 
- It has `preprocess2` as a target. 
- As far as I can see, https://github.com/dita-ot/dita-ot/blob/3.2/src/main/plugins/org.dita.base/build_preprocess2_template.xml doesn't have the same dita:depends targets as https://github.com/dita-ot/dita-ot/blob/3.2/src/main/plugins/org.dita.base/build_preprocess_template.xml. 
  - For example, `{depend.preprocess.clean-temp.pre}` exists in `build_preprocess_template.xml` but not `build_preprocess2_template.xml`.

Possible solution is to add in the old preprocessing targets.

I'm also open to any other solutions to my problem!

## Environment
* DITA-OT version: 3.2
* Operating system and version:
  _Linux_
* How did you run DITA-OT?
  _`dita` command_
* Transformation type:
  _PDF_

**Comment by Herbert-SDL** [comment] 2018-12-07 14:43
Hi,
I've encountered the exact same issue. The documentation says adding in targets in preprocessing is not recommended. Turns out it is not possible.
Solved it (as suggested above) by adding the **dita:extension="depends org.dita.dost.platform.InsertDependsAction"** and **dita:depends="{depend.preprocess.topicpull.pre}"** attributes to the target that I needed (**topic-topicpull** in this case) in **build_preprocess2_template.xml.**
As this is clearly a hack, I was wondering if there is a different/preferred way to do this? What I need is to do some processing _after_ conrefs have been resolved and _before_ xref/link text is pulled in.

**Comment by robander** [comment] 2018-12-07 15:35
This change was done by design in `preprocess2`, for a few related reasons. When extension points were added to `preprocess` they went into almost every target. That became a big burden on development. As a result:

-  Every time we had to change the order of targets, we potentially broke extensions that went in the middle of `preprocess` and assumed the current order. This has happened a few times to better process new DITA features, or to address defects caused by the original order.
- Every time we merged 2 targets to make them more efficient (like we did with `mappull` and `move-meta`), extensions disappeared and plugins broke.
- Having dealt with those problems, and the broken plugins that came whenever we had to change preprocess, the steps added _later_ in `preprocess` development did not get extensions.

The `preprocess2` is an entire reorganization of the pipeline. With the new start, basically from scratch, there was an explicit decision to avoid these problems by turning the general preprocess into a black box - you can add anything before, and anything after, but making the general preprocessing of DITA features into a black box lets the developers safely update / enhance / maintain the code that handles major DITA features. Jarno went over this in his DITA-OT Day talk introducing `preprocess2` last year, if you want to flip thru the slides or listen to the recording: https://www.oxygenxml.com/events/2017/dita-ot_day.html

If you have a critical need to plug in to a specific point, there are some options:

- You could do what @Herbert-SDL mentioned, but I wouldn't recommend that (that sort of change becomes a real headache as you upgrade DITA-OT releases)
- If we add any of these dependency extensions to `preprocess2` it will be one at a time, and only if we can't see a better way to do it. I haven't thought enough about the original case above to know if that applies here.
- Because I do sometimes do some pretty weird extensions, my approach has been to use my own preprocess pipeline, so I'm building with `mypdf` instead of `pdf`. That calls `my-preprocess` instead of the default; in my copy, I'm free to add whatever targets I need wherever I need them, without relying on DITA-OT extension mechanisms. It's generally been pretty easy to keep up with changes that way as the main process changes, because I can quickly compare my own `preprocess` to the default and see if anything has changed.

@infotexture ... I wonder if we should clarify in the docs that many of the extension points are for `preprocess`, but not for `preprocess2` which is the default for some outputs?

**Comment by infotexture** [comment] 2018-12-07 16:02
> I wonder if we should clarify in the docs that many of the extension points are for `preprocess`, but not for `preprocess2` which is the default for some outputs?

Yes, given the explanation above, I think that makes sense.

It sounds like `depend.preprocess.pre/post` are the only options for `preprocess2`, so we should mention that explicitly.

**Comment by Herbert-SDL** [comment] 2018-12-07 21:19
@robander Thank you for clarifying. As said, I consider my current solution a hack, as I changed one of the standard files of the toolkit. Never considered having a custom preprocessing pipeline, but I'll try that instead.

**Comment by robander** [comment] 2018-12-10 21:17
@Herbert-SDL Just in case my point came across wrong -- I didn't mean to sound like you had done something wrong - just meant to highlight that 1) yes, it would work, but 2) you're also right about it being a hack -- so best avoided when possible. Good luck with the custom pipeline approach...

**Comment by Herbert-SDL** [comment] 2018-12-11 08:10
@robander No problem! In the meantime, I've implemented the custom preprocessing pipeline and it works very well.

**Comment by jelovirt** [comment] 2019-09-24 14:19
Closed as works as described

**Closed by jelovirt** 2019-09-24 14:19 UTC
