### ISSUE TITLE
Use DITA to manage string content and vars?

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#2310] opened 2016-04-18 18:54 UTC
OK, maybe this is just a wild and crazy idea? I don't know enough about XSLT to evaluate the idea fully, nor do I know enough about the processing architecture behind the DITA-OT.

My primary interaction with the DITA-OT is through PDF and the PDF2 plug-in. The following is written with this in mind, but should be suitable for all transforms.

Well, here goes ...

DITA is about documentation and managing content, so why not put the DITA-OT strings and graphics into DITA? Move them from XSLT to DITA.

This would encompass the language dependent strings, language dependent graphics, language agnostic graphics and language agnostic 'string constructs' used in headers and footers. There are no doubt other similar strings for other transforms.

It would require a DITA specialisation. Let's call it 'dotvars'. I'm sure someone can improve on this. 'dotvarstopic' & 'dotvarsmap'.

The content model would be necessarily sparse. Firstly to encourage a good match to XSLT variables and constructs, and secondly because the semantic model is at the text, string, image level. In other words, no rich content model, and minimise confusion.

I would suggest that the content model is primarily based upon a specialisation of `<dl/>`, say:

```
<dotvarsdl>
    <dotvarsdlhead>
        <dotvarsdthd/>
        <dotvarsddhd/>
    </dotvarsdlhead>
    <dotvarsdlentry>
        <dotvarsdt/>
        <dotvarsdd/>
    </dotvarsdlentry>
</dotvarsdl>
```

`<dotvarsdt/>` would provide the XSLT variable name.

Multiple `<dotvarsdd/>` would provide alternative definitions for the XSLT variable.

`<dotvarsdd/>` would have a child element of `<ditaelement/>` to indicate the DITA element that the XSLT transform should choose. In turn, this would have a `<ditaattribute/>` element to indicate the attribute of the DITA element that the XSLT transform should choose. `<ditaelement/>` could also contain itself as a child, to correspond to the DITA element tree.

So, an example for the map title might look like this:

```
<dotvarsdl>
    <dotvarsdlhead>
        <dotvarsdthd>Map title</dotvarsdthd>
        <dotvarsddhd>Alternative definitions</dotvarsddhd>
    </dotvarsdlhead>
    <dotvarsdlentry>
        <dotvarsdt>maptitle</dotvarsdt>
        <dotvarsdd><text conkeyref="document/title"/></dotvarsdd>
        <dotvarsdd>
            <ditaelement>map<ditaelement>title</ditaelement></ditaelement>
        </dotvarsdd>
        <dotvarsdd>
            <ditaelement>map<ditaattribute>title</ditaattribute></ditaelement>
        </dotvarsdd>
    </dotvarsdlentry>
</dotvarsdl>
```

xml:lang would provide i18n support. The process would match the xml:lang defined by the DITA content with equivalent xml:lang variables.

It would be possible to group variables of the same language into a dotvarstopic with xml:lang at the topic level. Alternatively, it would be possible to group variables of the same type into a topic with xml:lang at the `<dotvarsdl/>` or `<dotvarsdd/>` level.

The aim would be to first attempt a match for the specific language, en-GB, or the generic language, en, or with a language agnostic variable.

As an example, there is an international symbol for X-rays that would be language agnostic. However, the Canadians have their own symbol. So if the language of the DITA content were en-CA or fr-CA, then it would pick up the Canadian symbol. Otherwise, it would pick up the international symbol.

How about the string constructs for headers and footers?

Firstly, it is necessary to link variables defined by `<dotvarsdl/>` to their use in a string construct. Maybe `<dotvarsstringvar/>`? The XSLT transform would match `<dotvarsstringvar>maptitle</dotvarsstringvar>` to its definition by `<dotvarsdt>maptitle</dotvarsdt>`, and then pick up the first <dotvarsdd/> that is not empty, and matches xml:lang.

A string construct could have multiple lines. This would be represented not by multiple `<dotvarsdd/>`, but by a series of child 
`<dotvarsblock/>`. The use of 'block' might be too close to XSL:FO language. It would be a specialisation of `<p/>`, but should use naming applicable to a XSLT transform that can produces XSL:FO or XHTML. Therefore, not simply `<dotvarsp/>`. Hmmm? XHTML does use `<p/>`! It would, however, be useful to use an element name that signifies it is part of the transform.

It would be necessary to have a mechanism to pick up XSLT generated standard variables. For example: date and time, page number, current top topic title. These would not really have a content model as they would just be place holders. Element names such as: `<dotvarsdate/>`, `<dotvarspagenum/>`, `<dotvarstoptopic/>`? The assumption is that it would be possible to format these with attribute sets, so the elements would be empty.

An example might be:

```
<dotvarsdl>
    <dotvarsdlhead>
        <dotvarsdthd>Odd page header</dotvarsdthd>
        <dotvarsddhd>Document name and page number on one line, current top topic on second line</dotvarsddhd>
    </dotvarsdlhead>
    <dotvarsdlentry>
        <dotvarsdt>oddpageheader</dotvarsdt>
        <dotvarsdd>
             <dotvarsblock><dotvarsstringvar>maptitle</dotvarsstringvar> | <dotvarspagenum/></dotvarsblock>
             <dotvarsblock><dotvarstoptopic/></dotvarsblock>
    </dotvarsdlentry>
</dotvarsdl>

```

One new attribute would be very useful, to pick up and connect with XSLT attribute sets: @attribute-set. It would need some careful thought about which elements should have this.

The ANT build would require a new variable: `$transformmap` to include the dotvarsmap.

**Comment by xephon2** [comment] 2016-04-19 07:08
Hello David, thank you very much for sharing this idea for improvement. Your recommended change would change a lot and this would lead unknown problems and would break backwards compatibility. Further on, where is the benefit for the user and/or the developer?

**Comment by jelovirt** [comment] 2016-04-19 07:11
I investigated this idea about 3 years ago and found it just made strings management more complex than what it needs to be.

@DJBHollis could you describe what  `<ditaelement>` and `<ditaattribute>` are used for? They look like a verbose XML syntax for XPath. Why does the string variable file need matching functionality?

**Comment by DJBHollis** [comment] 2016-04-19 18:46
String and graphic management with PDF2 is extremely complex for tech authors and information architects faced with a requirement to edit the stylesheets and create a custom plug-in. Handling them in a more familiar environment, that is DITA, seemed like a good idea. Tech authors and information architects typically do not have advanced XML, XSLT, XSL:FO, and XPath experience.

The idea would be to first process the dotvarsmap to extract the strings, variables and graphics. Then use these to process the main map.

For the X-ray symbol example, once the OT processes dotvarsmap, there would be 3 symbols: a language agnostic international symbol, and the Canadian symbol twice, for Canadian English and for Canadian French. Hence the idea of matching the language of the main content to the language of the string or graphic.

Once the OT processes dotvarsmap, there would also be a series of `<ditaelement/> ` and `<ditaattribute/>` which would indicate the elements and attributes from the content to extract to the variables. This would be the equivalent of the XPath constructs.

**Comment by robander** [comment] 2016-04-19 19:51
I'll admit to being a bit nervous ... Like @jelovirt I've thought about using DITA for string files. I eventually ruled it out because I thought I was ending up with something too complicated. (Early on in my DITA days, I did use specialized DITA to author some machine-readable constructs, and ended up backing off as it got harder to maintain.)

> String and graphic management with PDF2 is extremely complex for tech authors and information architects faced with a requirement to edit the stylesheets and create a custom plug-in. Handling them in a more familiar environment, that is DITA, seemed like a good idea. Tech authors and information architects typically do not have advanced XML, XSLT, XSL:FO, and XPath experience.

I certainly can't question the background there. That said, I've found that when I specialize enough to create constructs like to those you've described, authors don't view it as DITA -- it just looks like normal XML. That was what made me back away from the specializations mentioned above. It was easier to create a simple XML and document it, than to create a complex specialization and have to explain that it really was DITA under the covers. So, if this were purely a request for a new format to author the strings, my gut reaction would be to better document the current format.

> Once the OT processes dotvarsmap, there would also be a series of `<ditaelement/>` and `<ditaattribute/>` which would indicate the elements and attributes from the content to extract to the variables. This would be the equivalent of the XPath constructs.

I don't quite understand what the XPath equivalent is used for - is the idea here that the dotvarsmap could say, "Here is a label that I want to appear next to `<section>`", or "Here is a label that I want to appear next to `<note type="attention">`"? So that transform output processing any element would check this map to see if a label was available?

**Comment by DJBHollis** [comment] 2016-04-20 18:34
The idea was to not just generate string and image variables, but also to create header and footer 'string constructs' in DITA. As these could include, for example, metadata, it would need an equivalent to the XPath constructs to indicate which elements and attributes to extract from the DITA content.

>... indicate the elements and attributes from the content to extract to the variables ...

Should have been:

>... indicate the elements and attributes from the content to extract to the headers and footers ...

As headers and footers could be multi-line, the idea was to also include `<dotvarsblock/>`.

I understand what you're saying. Any specialisation would be a 'bridge' into the XSLT, XPath world, and would necessarily need to reflect that world, to some extent.

Also, there isn't a single, standard XPath statement. There would need to be some careful parsing to choose the right one. So, yes, it would increase the complexity for XSLT and XPath. But the benefit would hopefully be a much simpler procedure to set up strings, variables, headers & footers.

What DITA does have, though, is structure. In turn, this can guide the author.

There would need to be a standard or default map and set of topics. These would also provide examples for authors to work with.

Would it be worth flagging this conversation on DITA-Users, and seeing if anyone else has thought along these lines?

**Comment by robander** [comment] 2016-04-20 21:10
> I would hope that there would also be a benefit in removing string and management from the DOT.

Double checking here - how big a scope are you looking for with this? The current string files are really inseparable from DITA-OT. That is, they only exist to define strings used by DITA-OT. Is the suggestion that this format would be used by other tools, not just DITA-OT? Or is the suggestion rather that this would become a source file owned by the author, instead of being under the covers inside the toolkit?

> What DITA does have, though, is structure. In turn, this can guide the author.

It does ... but if all we are looking for is structure, wouldn't another option be to document the current format with a DTD or Schema? 

DITA specialization brings along a lot of requirements. For example, you'd be required to specialize numerous elements just to serve as containers - at a minimum, `<body>`, `<dl>`, and `<dlentry>`. Just thinking about this at a practical level - assuming some method of guided authoring, such as a DTD or Schema, I think all of the extra markup is introducing a lot of complexity to the authoring process. Your sample for `Odd page header` has 11 elements; it would be at least 14 if you include the root element, title, and body container. The current format only has three, plus two attributes: 
```xml
<vars xmlns="http://www.idiominc.com/opentopic/vars">
   <variable id="Body odd header"><param ref-name="prodname"/> | 
             <param ref-name="heading"/> | <param ref-name="pagenum"/></variable>
...
</vars>
```

Your suggested format clearly has features that are missing today (the XPATH-like selection, self-documenting headers, etc). But if the primary goal is easier authoring, I'm not sure this is the right fit.

For what it's worth, I say all this as somebody who has done all kinds of things with specialized DITA. But I've been burned by that as well. As a result, I'm wary of designs where the primary goal is to use DITA. I prefer to get my head around the desired features, and only _then_ try to figure out if using DITA would be a good fit.

**Comment by robander** [comment] 2016-04-20 21:30
Addendum to previous content: 

> I prefer to get my head around the desired features, and only _then_ try to figure out if using DITA would be a good fit.

I do recognize that this may be exactly how you came to the design above, and I'm just missing that fact because I was misled by the title of this issue. So, please continue the discussion...

**Comment by keberlein** [comment] 2016-04-21 00:42
I have to vote -1 for this one. While I'd love to make the PDF2 plug-in easier to work with, really doing so would require rebuilding the entire thing -- a task that no one has been willing to pay for so far.

I think modifying the PDF2 plug-in to handle strings and localized images in a different way would not be worth the considerable time and development effort.

I also suspect that it would not really solve the entire problem that David wants to address, especially the need to override both the strings file and static-content.xml to build custom headers and footers. And honestly, the overriding the default strings file is probably the easiest part of building a custom PDF style sheet.

**Comment by DJBHollis** [comment] 2016-04-21 17:18
> Double checking here - how big a scope are you looking for with this? The current string files are really inseparable from DITA-OT. That is, they only exist to define strings used by DITA-OT. Is the suggestion that this format would be used by other tools, not just DITA-OT? Or is the suggestion rather that this would become a source file owned by the author, instead of being under the covers inside the toolkit?

Apologies for any mis-direction. 'string management' was wrong - more like 'string definition'. Just the DOT.

**Comment by robander** [comment] 2016-04-21 18:56
> I just can't help thinking there has to be an easier way than chasing around multiple files to track down that 'something' that needs tweaking.

That's a goal I think all of us could get behind ... 

The trick is always going to be weighing the balance between a few critical items: 

1. Cost to develop the new feature
1. Impact to existing code / existing customizations
1. Benefit of the change

The suggestion here (in its current form) would rank very high in both development cost and in impact to existing code. If I understand it correctly, this would probably break most existing PDF customizations, as @xephon2 hinted in his response above. [As ever, we are severely limited by design choices made 10 years ago, and the fact that so many people worked off of those designs.] 

I don't think that level of cost is possible except as part of a general from-scratch redesign of the PDF process. We've talked about that repeatedly at our contributor calls, but as @keberlein said, nobody has been willing to take it on. If that ever happens, it will clearly need to have easier customization as one of the primary design points.

**Comment by robander** [comment] 2016-06-20 15:03
This has been open for quite a while now but I think it's time to close it, for the same reasons given in my previous comment:

- This would represent a major architectural change, with major work necessary for implementation. I haven't gotten the impression that any of the current project volunteers are likely to contribute that work.
- If we replace the current string / variable process with your suggestion, the impact to existing code and existing customizations would be tremendous. It would require a migration for virtually every PDF customization in existence. That can't happen, especially for something where the benefit is debatable.
-  In theory, your suggested method could be provided as an alternative string format. However, we're already working to consolidate the two existing methods (string files in `xsl/common` and variable files in `org.dita.pdf2/cfg/common/vars`). We're not going to create and maintain a third method just as we're finally about to merge the existing methods.

The only remaining alternative I can think of is to use a specialization like the one you suggest, and use that to _generate_ the string files using the actual toolkit format, for use with your own plugin or customization. That's a fine way to go about it, if you really find that process easier than the existing one (I personally would not). That sort of process is not going to be part of the shipped toolkit code, but could easily go in its own github project or possibly in @drmacro's DITA community.

**Closed by robander** 2016-06-20 15:03 UTC
Labels: feature, pdf
