### ISSUE TITLE
Remove keydef processing from XHTML rendering code

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#1837] opened 2015-01-08 20:36 UTC
Currently keys are (for the most part) resolved in one preprocessing step. For linking elements, all is good. For phrase elements, it pulls in text when needed.

The XHTML step then does extra processing that probably belongs inside the keyref process. Specifically, for non-linking elements that can't take `@href`, the XHTML code returns to the keydef.xml file to look up targets. This means we resolve the key twice - once when figuring out link text and setting up keydef.xml, then again when publishing XHTML (and any other format that wants to make a link). This is done for `<ph>`, `<keyword>`, `<cite>`, `<dt>`, `<term>`, and `<indexterm>` (when `$INDEXSHOW is active).

Suggestion: when we evaluate these elements during the keyref preprocess, we have easy access to linking information. We should set something like `@dita-ot:href` that can be easily interpreted by any final rendering step. When I suggested this to @jelovirt he pointed out we would also want `@dita-ot:format` and `@dita-ot:scope`

The one element I'm iffy about is the specialized `<abbreviated-form>` element. The source element is EMPTY so if we populate it in the preprocess, later stages that expect normal DITA may be thrown off. Also, we can't know in preprocess whether to use an abbreviation or a long form (that depends on the final rendering context). Potentially, we could put both the long and abbreviated form inside of `<dita-ot:info>` or similar, which is not so risky and more easily ignored by later steps?

**Comment by drmacro** [comment] 2015-01-09 17:41
That all sounds good to me. There's certainly no reason not to determine the ultimate resource for any key-based reference as early in the process as possible.

I like having the abbreviated-form element augmented with the potential replacement text so that final result processors can easily choose the form they want.

**Comment by raducoravu** [comment] 2015-01-12 06:36
+1, the XSLT stylesheets which produce the final output format (the ones which are usually written in order to implement a plugin) should probably receive the DITA content as plain DITA 1.1 content, with all the fancy stuff, keyrefs, conrefs, filters, braches resolved in an earlier stage.

**Comment by drmacro** [comment] 2015-01-12 15:40
The key definitions and references should be retained in the DITA source that goes to the final form: you might want to do something with it (e.g., use keys to generate anchor IDs in some output) but it should be clear in the XML that the key reference has or has not been resolved to a resource.

**Comment by robander** [comment] 2015-01-12 17:15
I'm not sure how it would be clear in the XML that the key has/has not been resolved? Currently, for xref/link, it simply is resolved by the time we get to rendering - but `@keyref` is still specified if you want to use it for something else. Similarly with non-linking elements, you simply know that the text has been resolved; the change here would be to resolve the linking aspect using a dita-ot namespace, so that the XHTML code has it available. So, `<xref>` would remain unchanged (link is updated based on the key), `<ph>` would get a new `dita-ot:href` attribute that has been resolved and can be used as needed.

**Comment by drmacro** [comment] 2015-01-12 19:30
As long as the original @keyref is maintained, then I think I'm fine. The @href value will always be either the resolved resource URI (based on resolving the original @keyref) or will be the @href that was authored (and may or may not be resolvable).

So output processors will still need to handle the possibility that @href values might not resolve but they don't need to worry about resolving key references: if @href is there, try to resolve it and react accordingly.

**Comment by robander** [comment] 2015-01-12 20:10
Sounds right to me.

**Comment by jelovirt** [comment] 2015-01-20 10:34
The code actually already will generate

```xml
<keyword keyref="link" class="- topic/keyword " href="test.dita"/>
```

When the key contains `@href`. See https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/writer/KeyrefPaser.java#L101

I refactored the code way back to use the KeyrefInfo objects for configuration and the code already at that time had this functionality. To keep the code same, we should *not* change the attribute to `@dita-ot:href`.

Should we just generate `@href` to other elements too?

**Comment by robander** [comment] 2015-01-20 13:43
I think that's probably OK, and it does make the doc issue https://github.com/dita-ot/docs/issues/17 a little more critical.

**Comment by jelovirt** [comment] 2015-01-22 15:13
FYI, working on this and the only thing missing is getting glossary terms to work in HTML XSLTs.

**Comment by jelovirt** [comment] 2015-01-23 14:32
The problem with this issue is that it affects basically all other transtypes. When source has

```xml
<keyword keyref="link"/>
``` 

and `link` key is has a URI resource, the preprocessing will resolve it to

```xml
<keyword keyref="link" href="test.dita">
  <?ditaot gentext?>
  title
  <?ditaot genshortdesc?>
  <desc>shortdesc</desc>
</keyref>
```

That is, if the `<keywork>` should be treated as a link, then normal topic pull processing will take place. The normal target title pull processing is exactly what we want, the problem is the desciption processing. It's pulled from target `<shortdesc>` and is something that normal `<xref>` links have. However, HTML, PDF, or any other transtype specific XSLT doesn't expect `<desc>` inside `<keyword>`, `<ph>`, `<term>`, `<cite>`, `<indexterm>`, `<index-base>`, or `<indextermref>` and it's incorrectly output.

We could have topic pull processing skip the description processing, but then we will not be able to get the same link processing as `<xref>`. We could wrap `<desc>` in a `<data>`, but e.g. `<keyword>` doesn't allow it as a child element and we get the same issue. Though, the default processing for `<data>` is to ignore it, so maybe it will be ok.

**Comment by robander** [comment] 2015-01-23 15:26
Interesting ... 

I think `<data>` would probably be reasonable there, because as you say, it's ignored by default. The problem is if/when somebody uses `<xsl:value-of>` or something like that, because they expect just plain text inside the keyword, and they end up with everything.

I haven't checked yet, but I wonder how much it would complicate topicpull to make sure it does not pull in the description. The code already works differently for the linktext, because xref (and now keyword) pull in text, while `<link>` needs the `<linktext>` wrapper.

**Comment by jelovirt** [comment] 2015-01-23 17:07
The code in topicpull can be changed to not pull shortdesc, it's just a matter of deciding whether keyword that's been made a link by keyref is treated exactly like xref or not. DITA itself has no precedent, since xref and link allow desc and there are no other link elements.

The easiest solution is to not pull desc, that way it does not need to be ignored.

**Comment by robander** [comment] 2015-02-16 13:47
I think we should go with the easiest solution - don't pull desc. Can always add that in DITA-OT 3.0 if it becomes necessary....

**Comment by jelovirt** [comment] 2015-02-16 14:54
Ok, I'll implement not pulling desc. That will still be valid WRT spec, as the spec doesn't say a `keyword` turns into an `xref`, just that it become as navigation element.

**Closed** 2015-02-17 10:21 UTC
Labels: feature, P2, preprocess
