### ISSUE TITLE
Can no longer use conref in keydef metadata [DOT 2.3]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2420] opened 2016-06-17 12:47 UTC
If in my DITA Map I define a key which has a keyword with a conref to another one defined in a topic:

```
     <keydef keys="company_name_full">
      <topicmeta>
        <keywords>
          <keyword
            conref="abc.dita#abc/company_full"/>  
        </keywords>
      </topicmeta>
    </keydef>
```

and in some topic I use the key:

```
<ph keyref="company_name_full"/>
```

it no longer gets expanded. Using DITA OT 1.8 the key got expanded.

**Comment by raducoravu** [comment] 2016-06-22 11:51
Any hint in the specs about what stage should be applied first? Conref or keyref?
In what issue was the order of these stages changed?

**Comment by infotexture** [comment] 2016-06-22 15:18
@raducoravu: This was changed for 2.0 with #1631. From the [Release Notes](http://www.dita-ot.org/2.0/readme/changes/rel2.0.html):

> The order of preprocessing stages has been optimized to move keyref processing before conref processing. This provides significant performance gains for source that uses multiple key references within reusable content.

**Comment by robander** [comment] 2016-06-22 17:01
> Any hint in the specs about what stage should be applied first? Conref or keyref?

Because no order was specified way back in 1.0 the spec has had great difficulty giving a mandated processing order for any of the features. Even newer features have trouble, because giving an order like "Between existing features A and B" establishes an order for A and B. An additional complication is that while I think the spec implies you should evaluate keyref before conref, that doesn't rule out "evaluating" as a way of simply moving the conref from the map context into the topic.

**Comment by jelovirt** [comment] 2016-06-23 06:16
I think the cause may be that the key resolution module fails to verify a resolved topic has conrefs.

**Comment by drmacro** [comment] 2016-06-23 11:17
My analysis is that the branch filtering and key scope features effectively require a specific order of processing and that implementations should do preprocessing in a "filtering aware" way. I captured this analysis in a dita-ot wiki page here: https://github.com/dita-ot/dita-ot/wiki/DITA-1.3-Preprocessing-Architecture-proposal

**Comment by jelovirt** [comment] 2017-04-23 09:58
This is something that would require processing keyref and conref in a loop when you keep on resolving them until no keyref or conref remains.

**Comment by drmacro** [comment] 2017-04-24 15:07
Resolution of direct conrefs should be done before any key-based processing is performed, otherwise there is no way to ensure you get the right answer.

Once key spaces are constructed it should then be possible to resolve key references in any context, including in the content of key defining-topicrefs.

**Comment by raducoravu** [comment] 2019-09-03 12:51
👍 We got one more report here:

https://www.oxygenxml.com/forum/viewtopic.php?p=55127#p55094

**Comment by raducoravu** [comment] 2019-09-04 06:01
Attaching samples for both situations (conref inside key definition and conkeyref inside key definition). Both do not work and as @robander  said no error is reported and the text is just not present in the output.

[samples-conkeyref-in-keydef.zip](https://github.com/dita-ot/dita-ot/files/3572924/samples-conkeyref-in-keydef.zip)
[sample-conref-in-keydef.zip](https://github.com/dita-ot/dita-ot/files/3572926/sample-conref-in-keydef.zip)

**Comment by GlennEmerson** [comment] 2019-11-25 16:13
We have a client experiencing this issue. 
Keydef in a ditamap referenced from a bookmap.
Topic with a conref.
Conref source refers to the key using keyword:
<ph id="conrefSource"><keyword keyref="variableTextString"/> ispo facto lorem didum dadum wantum choo.</ph>

In the 2.4.3 OT, this resolves in PDF:
Text of Variable String ipso facto lorem didum dadum wantum choo.

In 3.2 OT, the keyref is dropped:
 ipso facto lorem didum dadum wantum choo.

However, in Oxygen 21.1 with the 3.x OT packaged, using the XSL-FO or CSS flavors of PDF, the keyref does resolve. 

Until this thread was pointed out to me, I thought it was something in the XSLT for the OT Plugin, especially since it worked in Oxygen 21.1 using the default Syncrosoft plugins. So, before I spend a lot of time and energy investigating the XSL for the plugin, Radu, is this something your team optimized in your Oxygen 21 package? If so, should I use that version of the OT in stead of the GitHub 3.2? 
Thanks,
Glenn Emerson

**Comment by raducoravu** [comment] 2019-12-04 12:20
@GlennEmerson this should not work even in Oxygen, I'm attaching a sample DITA project exemplifying my original problem.
[flowers.zip](https://github.com/dita-ot/dita-ot/files/3921755/flowers.zip)

If your problem is different maybe you can also attach a small DITA project exemplifying it.

**Comment by TerryMon20** [comment] 2020-05-15 06:58
I have a use case as well. We publish a document called Day One Impact Overview. This document essentially lists all features (product-wise) that impacts customers on the day 1 of the release. Each chapter in the map represents a product. The introduction topic contains a standard text and only the product names vary for each chapter. We want to create one single topic and utilize the DITA key scope to inject the relevant product name for each chapter during run time. Currently, we have stored all product names as `conrefs `in a ware house file using the `ph `element. Since `keyref `requires a topic ID and since `conrefs ` in keys are not expanded, I was experimenting to use `conkeyrefs` by storing  the product names as Key Definitions. I have a list of key definitions. Each definition contains a product name. Then I defined another key called **product** using key scopes. The **product** key does `conkeyref `to a key in the product list. The product key in the intro topic expands correctly for each chapter in Oxygen. Meaning the reused intro topic now shows relevant product name depending on the chapter it is used in. However, the key does not expand at all in the output. I am attaching a sample. 

[bm_product_names.zip](https://github.com/dita-ot/dita-ot/files/4632721/bm_product_names.zip)

If keys using `conrefs `as in Radu'x example are expanded, we do not have to change our current warehouse file. Or else, if it can at lease expand the conkeyrefs, that would be a great solution.

**Comment by sh511** [comment] 2020-06-16 04:14
I have a use case similar to GlennEmerson. I am trying to insert text based on a keyscoped keydef. Oxygen XML Editor 22.1 can resolve the reference to a keyref that is part of a keyscope (other than root) but DITA-OT looks for it in the root scope and I get the following error:

[DOTJ047I] Unable to find key definition for key reference "myvalue" in root scope. The href attribute may be used as fallback if it exists

I have attached a simple project that generates the error.  When the keyref is not part of a conref, it is resolved correctly (proper keyscope). I am new to DITA but I believe that I used conref and keyref properly.

[my-conref-trouble.zip](https://github.com/dita-ot/dita-ot/files/4784312/my-conref-trouble.zip)

**Comment by raducoravu** [comment] 2023-08-03 14:13
@jelovirt oh so this is also related to the fact that with "preprocess2" all topics are now required to be referenced in the DITA Map.

**Comment by jelovirt** [comment] 2023-08-05 07:59
#4258 is a partial fix to this issue. You no longer need to reference conref targets separately with a `<topicref>`. It doesn't fix this issue completely. A workaround is Instead of

```xml
<keydef keys="company_name_full">
  <topicmeta>
    <keywords>
      <keyword conref="abc.dita#abc/company_full"/>  
    </keywords>
  </topicmeta>
</keydef>
```

you need to use

```xml
<keydef keys="company_name_full">
  <topicmeta>
    <keywords>
      <keyword><text conref="abc.dita#abc/company_full"/></keyword>  
    </keywords>
  </topicmeta>
</keydef>
```

**Comment by raducoravu** [comment] 2023-08-07 05:02
@jelovirt maybe you can still close this issue as a partial fix. There have been quite a number of comments on this issue but the intent of the original issue has been about conrefs placed in keydef.
I do not understand why the case with the conref placed on the keyword does not work though.

**Closed** 2023-08-10 17:07 UTC
Labels: bug, priority/high, preprocess/keyref, preprocess/conref

**Comment by raducoravu** [comment] 2023-08-18 03:55
Thanks @jelovirt
